### ISSUE TITLE
建议2.x版本能够内置一个友链页面，根据配置渲染

### ISSUE THREAD

**Issue by LiJunYi2** [vuepress-reco/vuepress-theme-reco#101]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

目前1.x版本的友链，只有在首页的右下角，如果想要以列表的形式进行展示友链，那就是自定义组件去渲染，既然2.x就要来了，还是希望能够内置一个友链页面

**Describe alternatives you've considered**

**Additional context**

友链页面可以参照这种列表形式渲染，这个看上去还不错，当然如果有更好的方式那就最棒了！谢谢
![image](https://user-images.githubusercontent.com/40384503/180675280-9edd3c8b-df80-4926-9137-18c528008e1a.png)

**Comment by yxzlwz** [comment]
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/75941562/c0000d98-629c-4575-a815-5e1f3a288672)

https://www.yixiangzhilv.com/docs/yxzl/friendlink.html

本人的网站，如果 @recoluan 觉得这个效果可以的话我可以有空写写，提PR

**Comment by Qiu-Jun** [comment]
> ![image](https://user-images.githubusercontent.com/75941562/246592553-c0000d98-629c-4575-a815-5e1f3a288672.png)
> 
> https://www.yixiangzhilv.com/docs/yxzl/friendlink.html
> 
> 本人的网站，如果 @recoluan 觉得这个效果可以的话我可以有空写写，提PR

大佬提pr了吗

**Comment by recoluan** [comment]
已经在 `2.0.0-beta.66` 中增加了友情链接内置页面，[文档](https://vuepress-theme-reco.recoluan.com/docs/theme/builtin-page.html)。

**Comment by recoluan** [comment]
> ![image](https://user-images.githubusercontent.com/75941562/246592553-c0000d98-629c-4575-a815-5e1f3a288672.png)
> 
> https://www.yixiangzhilv.com/docs/yxzl/friendlink.html
> 
> 本人的网站，如果 @recoluan 觉得这个效果可以的话我可以有空写写，提PR

先拟订了一个简单页面，你如果有空可以考虑把分组功能加上。
