### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by skyls03** [vuepress-reco/vuepress-theme-reco#106]
就是我不想使用脚手架，不想去nodemodel那里去改主题，我想直接对主题魔改，应该怎么做呢？

**Comment by recoluan** [comment]
你好，可以有两种办法：
1. 网友提供了很多关于样式方面的 vuepress 插件，可以在 GitHub 搜索，或者去 reco 主题官网加我的微信群，和 reco 主题爱好者交流；
2. vuepress 允许你自定义样式的 [官网 API](https://v1.vuepress.vuejs.org/zh/config/#styling)。
