### ISSUE TITLE
Screenfull component is not register correctly

### ISSUE THREAD

**Issue by yywc** [vuepress-reco/vuepress-theme-reco#107]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?

when set `plugins: [['@vuepress-reco/vuepress-plugin-screenfull', false]]` in themeConfig.

screenfull will not render but there is a warning in console that is `Screenfull` component is not register correctly and the `Screenfull` tag show in html.

#### Other relevant information

![image](https://user-images.githubusercontent.com/18376480/70136307-b557fe80-16c6-11ea-94b2-be0cc03903e2.png)

## Solution

You can add a `fullScreenPicker` like `themePicker` in themeConfig and set it in `Sreenfull` that use `v-if`.

- Your OS: MacOS 10.15.1
- Node.js version: v8.16.2
- VuePress version: v1.2.0
- VuePress-theme-reco version: v.1.14
- Which package manager did you use for the install(npm/cnpm/yarn)? npm

**Comment by recoluan** [comment]
OK, I get it now, I will try to solve it in next version。  
Thanks for your suggestion, you can use 'display: none' to hide it currently 。
