### ISSUE TITLE
theme-reco-1.x 有多余请求，影响了本身的加载速度

### ISSUE THREAD

**Issue by jingjianhai** [vuepress-reco/vuepress-theme-reco#110]
- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version: 
- VuePress-theme-reco version: 
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?

**Comment by recoluan** [comment]
What's the version of theme reco in your project?
