### ISSUE TITLE
文章--日期格式化错误

### ISSUE THREAD

**Issue by XXllXX** [vuepress-reco/vuepress-theme-reco#110]
[util.js 文件 formatDate 函数214行](https://github.com/vuepress-reco/vuepress-theme-reco/blob/develop/helpers/utils.js)
`
'd+': date.getDay(),

应该为

'd+': date.getDate(),
`

**Comment by recoluan** [comment]
好的，非常感谢

**Comment by recoluan** [comment]
已经在最新测试版中修正。
