### ISSUE TITLE
增加文章别名

### ISSUE THREAD

**Issue by Houttuyniae** [vuepress-reco/vuepress-theme-reco#111]
![4Z%T@U4%WZTE{2CNFWLDX9E](https://user-images.githubusercontent.com/35051245/70982580-33b69680-20f2-11ea-8416-eb7fe14730ec.png)

![G3FP(%BI%U(C_A%}GJJ9VAL](https://user-images.githubusercontent.com/35051245/70982657-4fba3800-20f2-11ea-8d1a-c770a829b8b2.png)

因为我是安装分组的方式写文章，这样每篇文章的标题可能就很简短，但是在首页如果这么简短的标题，就看不来是什么了，所以想要一个别名，在首页使用，不知道可以吗

**Comment by recoluan** [comment]
你好，像你这种文章分组的方式一般的是一个系列，比如项目文档。

像这种文档一般只提供一个入口，比如放在 navbar，因为不属于单纯的博文，你可以给他们每一篇`publish: false`， 或者每一篇都不要去设置分类和标签，就不会在首页、分类和标签的列表里显示了。

希望对你有帮助。

**Comment by recoluan** [comment]
还有我看到你的文章标题是重复的，文章内只是用 `front-matter` 来设置标题就可以了，不需要使用一级标题了。
