### ISSUE TITLE
npm ERR! code EINTEGRITY

### ISSUE THREAD

**Issue by ydyi** [vuepress-reco/vuepress-theme-reco#111]
npm install 时
提示：
npm ERR! code EINTEGRITY
npm ERR! Integrity checksum failed when using sha512: wanted sha512-mu/N4uvfDN2zVQQ5AYJI/g4qxn2bHB6521t1UuH09ShNWjebTqN0ZFuYK9uYjcgmI0dTQEs+Owi1EO6U0OkOZQ== but got sha512-iiXaOL2wSbnSY4qg0mFPWJHL9iwyEsoNYwaHF2w58/fsVAQJlj+KUfFAFZu+nzbz+b7dUprJEAc+O9vhHHhQTA==.

**Comment by recoluan** [comment]
This is not a bug of the reco theme, I guess it is a network reason.
