### ISSUE TITLE
时间线页面样式错误

### ISSUE THREAD

**Issue by Taosky** [vuepress-reco/vuepress-theme-reco#112]
直接进入/timeLine/，或在此页面刷新，顶栏会错位，样式不正常。其他页面未见此问题。
![Jietu20191219-215527.png](https://i.loli.net/2019/12/19/IHhbPxwlYfkesXQ.png)

**Comment by recoluan** [comment]
你好，这个问题已经在最新的测试版得到解决，并在下个正式版发布。

**Comment by Taosky** [comment]
> 你好，这个问题已经在最新的测试版得到解决，并在下个正式版发布。

好的，感谢。
