### ISSUE TITLE
app.xxx.js is too large!!!

### ISSUE THREAD

**Issue by laobg** [vuepress-reco/vuepress-theme-reco#118]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
After executing build, all global vars are defined in plugins will be bundled in ``dist/assets/app.xxx.js``, resulting the large size of a single ``js`` and it takes a long time to load the site. ``vuepress-plugin-page`` is mainly.

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version: ^2.0.0-beta.48
- VuePress-theme-reco version: ^2.0.0-beta.30
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?yarn

**Comment by senmu-a** [comment]
A custom packaging configuration will be launched recently, you can pay attention to it.
