### ISSUE TITLE
[1.x] [Vue warn]: injection "Symbol(showModuleSymbol)" not found.

### ISSUE THREAD

**Issue by N-You** [vuepress-reco/vuepress-theme-reco#121]
- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Your OS: 
- Node.js version: 16.15.0
- VuePress version: 1.8.2
- VuePress-theme-reco version: 1.6.14
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? cnpm

**Comment by N-You** [comment]
run build 报错

**Comment by wencwcoder** [comment]
我也发生了，1.6.14

**Comment by breadfruit** [comment]
我也是1.6.15

**Comment by auggieyd** [comment]
我也是

**Comment by duktig666** [comment]
me too

**Comment by duktig666** [comment]
1.6.15

**Comment by recoluan** [comment]
试一下最新的 1.6.17 呢

**Comment by recoluan** [comment]
试一下最新的版本的，还不行的话，周末我看一下

**Comment by duktig666** [comment]
> 试一下最新的 1.6.17 呢

1.6.17 没有这个告警了

**Comment by duktig666** [comment]
但是执行 `npm run bulid` 之后，生成的 index.html访问后失去了 样式。但是 npm run dev是正常的。
情况如下：
![image](https://user-images.githubusercontent.com/53132746/226831014-51d71007-a623-4bf7-9b0b-c178a9354afb.png)
