### ISSUE TITLE
Is it possible to add mutli-language support?

### ISSUE THREAD

**Issue by franklinqin0** [vuepress-reco/vuepress-theme-reco#122]
I want a site in both English and Chinese.

Thanks!

**Comment by recoluan** [comment]
You can imitate the Chinese and English configuration methods of the theme website, but some plugins have not been adapted, and `@vuepress/plugin-blog` has not found a good compatibility method.

I am trying something.

**Comment by CHANist** [comment]
I also want to have a multi-lingual website, as this is a very nice blog theme, which I think everyone would love. But there is a problem in having multi-lingual. Maybe I am wrong, but as see from the code, I see there are certainly some places which hard code the field name, which makes this even harder for foreigners to use it. e.g. in HomeBlog.vue, `分类` is used, but I think it should accept an i18n setup, which allow end user to change it, to whatever they want, in their language. That would be much better.

**Comment by recoluan** [comment]
> I also want to have a multi-lingual website, as this is a very nice blog theme, which I think everyone would love. But there is a problem in having multi-lingual. Maybe I am wrong, but as see from the code, I see there are certainly some places which hard code the field name, which makes this even harder for foreigners to use it. e.g. in both HomeBlog.vue, PersonalInfo.vue `标签` is used, but I think sharing the same variable will be better. Maybe we can use i18n, and specify it with a name on it. So that we can share it across different vue files, and also by providing English, not only Chinese but also Foreigners may contribute it in a easier way.

Thank you very much for your advice.



I couldn't agree with your suggestion more. I'm thinking about it too. In its early stages, the topic was not expected to reach such a large audience, so some aspects were not considered adequately.



Plus, for some personal reasons, coding time has been decreasing recently, so many processes have slowed down.



I will certainly solve this problem later. Thanks again.

**Comment by recoluan** [comment]
The theme itself has been processed in multiple languages, look here [docs](https://vuepress-theme-reco.recoluan.com/views/1.x/local.html#%E7%BD%91%E7%AB%99%E6%94%AF%E6%8C%81%E7%9A%84%E8%AF%AD%E8%A8%80) , and plugins (mainly comment plugin) are not yet compatible.
