### ISSUE TITLE
Must use import to load ES Module: @vuepress\plugin-back-to-top

### ISSUE THREAD

**Issue by shichaohui** [vuepress-reco/vuepress-theme-reco#127]
## Bug report
Must use import to load ES Module: @vuepress\plugin-back-to-top

#### What is actually happening?
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\GitHub\shichaohui\blog\node_modules\@vuepress\plugin-back-to-top\lib\node\index.js
require() of ES modules is not supported.
require() of D:\GitHub\shichaohui\blog\node_modules\@vuepress\plugin-back-to-top\lib\node\index.js from D:\GitHub\shichaohui\blog\node_modules\vuepress-theme-reco\lib\node\recoTheme.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files 
in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\GitHub\shichaohui\blog\node_modules\@vuepress\plugin-back-to-top\package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (D:\GitHub\shichaohui\blog\node_modules\vuepress-theme-reco\lib\node\recoTheme.js:5:30)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
```

#### Other relevant information

- Your OS: Windows 10
- Node.js version: v14.18.3
- VuePress version: 2.0.0-beta.46
- VuePress-theme-reco version: 2.0.0-beta.33
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?
yarn

**Comment by senmu-a** [comment]
So, what is your trouble?

**Comment by Amoyens1s** [comment]
@senmu-a 我和 @shichaohui 遇到的错误一样，换成recoTheme后项目无法启动
![image](https://user-images.githubusercontent.com/37032347/185890403-6c3602ee-3f2a-434c-aecb-1cc93dde6166.png)

**Comment by shichaohui** [comment]
var END = Math.pow(2, 52);
var START = END - 100;
console.log(start)
var count = 0;
for (var i = START; i <= END; i++) { 
console.log(i)
  count++;
}
console.log(count);

**Comment by kongchengji** [comment]
可能与@vuepress/plugin-back-to-top版本有关，我使用的是
- vuepress: 2.0.0-beta.48，
- vuepress-theme-reco: 2.0.0-beta.33
我对一份成功的和一份报此错误的项目**yarn.lock**进行了对比，发现@vuepress/plugin-back-to-top@^2.0.0-beta.48的版本不同，猜测可能是因为这个原因
![image](https://user-images.githubusercontent.com/46988499/188770094-842a5e51-987f-43f6-8290-efd83be52fc9.png)

![image](https://user-images.githubusercontent.com/46988499/188770110-b6ff6d93-3642-43e9-8eea-31bbec64df29.png)

**Comment by recoluan** [comment]
升级到最新版本 `vuepress@2.0.0-beta.51` `vuepress-theme-reco@2.0.0-beta.41`，把 lock 文件和缓存文件删掉，试一下呢

**Comment by shichaohui** [comment]
升级后可以了 `vuepress@2.0.0-beta.51` `vuepress-theme-reco@2.0.0-beta.41`
