### ISSUE TITLE
求问博客主题的网址上的图标文件文件怎么设置

### ISSUE THREAD

**Issue by YBFJ** [vuepress-reco/vuepress-theme-reco#128]
尊敬的开发者您好，博客主题非常棒，
## Feature request
我想请问下这个博客网址上的“favicon.ico”图标文件怎么设置，我看到luan大佬的网址图标是一个圆形黑底上面白字写着reco，我想问下去哪里设置。麻烦了，辛苦啦~

#### What problem does this feature solve?
能够改变网址上显示的图标

#### How should this be implemented in your opinion?
不知道，应该能够在config.js里面设置吧

#### Are you willing to work on this yourself?
我很乐意，，，但是我不知道怎么做

**Comment by franklinqin0** [comment]
应该是在docs/README.md里面的heroImage里设置。

如果我是你，会用Chrome右键inspect，点击左上角的鼠标，可以在页面里指向那个图片，然后Elements会对应的html。你就可以看到图片的名称，然后去源码里面找这个名称就好了。

**Comment by recoluan** [comment]
`favicon.ico` 是在 `head` 标签里进行设置的，`vuepress` 官网有介绍怎么在 `config.js` 设置 `favicon.ico`，你可以找一下.
