### ISSUE TITLE
SyntaxError: Element is missing end tag

### ISSUE THREAD

**Issue by azrng** [vuepress-reco/vuepress-theme-reco#128]
- [ ] I confirm that this is an issue rather than a question.

## Bug report
When I execute "NPM run build", the error Element is missing end tag is displayed. Then I find the error as follows [<p> Func&lt;T&gt; support </p>] code, this is normal writing, it is recognized incorrectly

#### What is actually happening?
Failed to generate a static file. Procedure

#### Other relevant information

- Your OS:  win10
- Node.js version: v16.17.0
- VuePress version: 2.0.0-beta.48
- VuePress-theme-reco version: 2.0.0-beta.30
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? npm

**Comment by azrng** [comment]
I just tested if there is a better solution to this problem, although I could use an escape character

**Comment by azrng** [comment]
I just tested if there is a better solution to this problem, although I could use an escape character

**Comment by recoluan** [comment]
Please upgrade vuepress and vuepress-theme-reco to the latest version.

**Comment by azrng** [comment]
"vuepress": "^2.0.0-beta.51",
    "vuepress-theme-reco": "^2.0.0-beta.41"
Same error when building

**Comment by recoluan** [comment]
You can Try to update to latest version.

**Comment by azrng** [comment]
The upgrade worked out. Forgot to turn it off. Sorry

**Comment by recoluan** [comment]
That's ok.
