### ISSUE TITLE
在文章详情页，back-top 点击无反应！

### ISSUE THREAD

**Issue by waitan2018** [vuepress-reco/vuepress-theme-reco#13]
猜测应该是侧边栏挡住了，如果可以的话，建议 back-top 不要太靠边，放到文章和侧边栏的中间就好了，方便点。

**Comment by GeniyGOD** [comment]
+1

**Comment by GeniyGOD** [comment]
+1

**Comment by recoluan** [comment]
大家试一下 vuepress@2.0.0-beta.60 和 vuepress-theme-reco@2.0.0-beta.44
