### ISSUE TITLE
添加博客配置后vue报错

### ISSUE THREAD

**Issue by ayuan-meng** [vuepress-reco/vuepress-theme-reco#131]
vue.runtime.esm.js?2b0e:4573 [Vue warn]: Error in nextTick: "SyntaxError: Failed to execute 'querySelector' on 'Document': '#%E6%88%91%E6%98%AF%E4%BA%8C%E7%BA%A7%E6%A0%87%E9%A2%98-2' is not a valid selector."

DOMException: Failed to execute 'querySelector' on 'Document': '#%E6%88%91%E6%98%AF%E4%BA%8C%E7%BA%A7%E6%A0%87%E9%A2%98-2' is not a valid selector.

**Comment by recoluan** [comment]
Please submit issue according to the specification.
