### ISSUE TITLE
[1.x] 右侧侧边栏添加后，页面老是自己回滚，有没有什么解决办法

### ISSUE THREAD

**Issue by xiaohuooo** [vuepress-reco/vuepress-theme-reco#134]
- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version: 
- VuePress-theme-reco version: 
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?

**Comment by recoluan** [comment]
Please submit issue according to the specification.

**Comment by xiaohuooo** [comment]
Your OS:window11
Node.js version:v14.16.0
VuePress version:1.9.7
VuePress-theme-reco version:1.6.15
Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?npm

**Comment by recoluan** [comment]
Try to update vuepress-theme-reco to 1.6.16
