### ISSUE TITLE
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

### ISSUE THREAD

**Issue by fanzihui** [vuepress-reco/vuepress-theme-reco#136]
#### What is actually happening?
```
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
```
在 netlify 网站部署后, 网站打不开, 并且出现了上述问题！
#### Other relevant information
网址: https://fanle.netlify.com/

- Your OS: https://app.netlify.com/
- VuePress version: 1.2.0
- VuePress-theme-reco version: 1.2.2

**Comment by recoluan** [comment]
我这目前没有出现过这种问题。你是不是自己增加代码了，代码里有appendChild方法，并且传递的参数不是 Node ？

**Comment by fanzihui** [comment]
> 我这目前没有出现过这种问题。你是不是自己增加代码了，代码里有appendChild方法，并且传递的参数不是 Node ？

没有改代码，只有一些自定义的设置,，[代码地址](https://github.com/fanzihui/gblog)

**Comment by ChouBaoDxs** [comment]
我也出现了这个问题，直接文章链接复制到浏览器打开就会报这个错并且白屏，如果是从主页打开的文章就没问题

**Comment by jialeens** [comment]
我也出现了同样的问题，如果md链接后面不加.html一直会卡在过渡页面

**Comment by TypeInfos** [comment]
我也是遇到了这个问题，指定某个.html页面就可以进去，不然就卡在过渡页面上

**Comment by JohnieXu** [comment]
> 我也出现了同样的问题，如果md链接后面不加.html一直会卡在过渡页面

请问具体是哪里的链接后面要加`.html`？是每个md文件吗？

**Comment by jialeens** [comment]
我编写md文档内链接到另一个md文档时，直接写文档路径（不写`.md`后缀），点击链接，页面url正确跳转，url变成了携带`.html`后缀的页面，但是页面会卡在过渡页面（吃豆子），同时控制台报错：`DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.`，只能再刷新（F5）后，才会正式展示页面内容。

**Comment by WangScaler** [comment]
我刚部署在服务器的时候一切正常，但是当运行了一段时间之后，当我再次访问的时候发现卡在了加载（吃豆子的）页面，当我打开浏览器控制台发现，，出现了上述错误。

**Comment by LuckyRyan-web** [comment]
我的是在dev运行没有问题，但是build打包后运行文件会出现

`app.a9b1d4e8.js:30 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method`

的问题

**Comment by snowinszu** [comment]
找到原因了  需要去cdn配置  404状态码重定向到404.html

**Comment by lvxy-git** [comment]
@recoluan 我也遇到了这个问题，在本地dev没问题，放到githubpage上就一直吃豆子了，有解决了的吗？

**Comment by wencwcoder** [comment]
> 我刚部署在服务器的时候一切正常，但是当运行了一段时间之后，当我再次访问的时候发现卡在了加载（吃豆子的）页面，当我打开浏览器控制台发现，，出现了上述错误。

请问老哥解决了吗，我的也是同样的问题

**Comment by zhoufanglu** [comment]
这个问题最后有解决吗？ 我也是本地没问题，然后打包后发布有问题。

**Comment by wuhou123** [comment]
已收到，谢谢

**Comment by 289373410** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by recoluan** [comment]
> 这个问题最后有解决吗？ 我也是本地没问题，然后打包后发布有问题。

vuepress和主题你分别用的什么版本啊

**Comment by zhoufanglu** [comment]
> > 这个问题最后有解决吗？ 我也是本地没问题，然后打包后发布有问题。
> 
> vuepress和主题你分别用的什么版本啊

"vuepress": "^1.8.0",
 "vuepress-theme-reco": "^1.6.1"
 比较老了， 我是本地开发没问题，打包后就有问题。 
`https://zhoufanglu.github.io/vuepressBlog/categories/%E6%89%93%E5%8C%85/`
你可以试下，上面的tab点击不生效， 然后刷新也有问题

**Comment by recoluan** [comment]
> > > 这个问题最后有解决吗？ 我也是本地没问题，然后打包后发布有问题。
> > 
> > 
> > vuepress和主题你分别用的什么版本啊
> 
> "vuepress": "^1.8.0", "vuepress-theme-reco": "^1.6.1" 比较老了， 我是本地开发没问题，打包后就有问题。 `https://zhoufanglu.github.io/vuepressBlog/categories/%E6%89%93%E5%8C%85/` 你可以试下，上面的tab点击不生效， 然后刷新也有问题

我切换 tab 没问题，点进有些博客会有问题，感觉是中文路径的问题吧。

你这版本也比较老，建议升级：
- vuepress: 1.9.10
- vuepress-theme-reco: 1.6.17

如果还有问题建议升级到 2.0 吧，1.0 已经不维护了。

**Comment by zhoufanglu** [comment]
> > > > 这个问题最后有解决吗？ 我也是本地没问题，然后打包后发布有问题。
> > > 
> > > 
> > > vuepress和主题你分别用的什么版本啊
> > 
> > 
> > "vuepress": "^1.8.0", "vuepress-theme-reco": "^1.6.1" 比较老了， 我是本地开发没问题，打包后就有问题。 `https://zhoufanglu.github.io/vuepressBlog/categories/%E6%89%93%E5%8C%85/` 你可以试下，上面的tab点击不生效， 然后刷新也有问题
> 
> 我切换 tab 没问题，点进有些博客会有问题，感觉是中文路径的问题吧。
> 
> 你这版本也比较老，建议升级：
> 
> * vuepress: 1.9.10
> * vuepress-theme-reco: 1.6.17
> 
> 如果还有问题建议升级到 2.0 吧，1.0 已经不维护了。

感谢回答，我先试试看 ，问题有些插件不支持2.0.。。

**Comment by zhoufanglu** [comment]
> > > > > 这个问题最后有解决吗？ 我也是本地没问题，然后打包后发布有问题。
> > > > 
> > > > 
> > > > vuepress和主题你分别用的什么版本啊
> > > 
> > > 
> > > "vuepress": "^1.8.0", "vuepress-theme-reco": "^1.6.1" 比较老了， 我是本地开发没问题，打包后就有问题。 `https://zhoufanglu.github.io/vuepressBlog/categories/%E6%89%93%E5%8C%85/` 你可以试下，上面的tab点击不生效， 然后刷新也有问题
> > 
> > 
> > 我切换 tab 没问题，点进有些博客会有问题，感觉是中文路径的问题吧。
> > 你这版本也比较老，建议升级：
> > 
> > * vuepress: 1.9.10
> > * vuepress-theme-reco: 1.6.17
> > 
> > 如果还有问题建议升级到 2.0 吧，1.0 已经不维护了。
> 
> 感谢回答，我先试试看 ，问题有些插件不支持2.0.。。

更新了完全跑不起来。。比较难定位，开发环境没问题，打包后就不行了。。
