### ISSUE TITLE
单独一篇文章，如何绝对加密

### ISSUE THREAD

**Issue by nshusr** [vuepress-reco/vuepress-theme-reco#137]
单独文章如何绝对加密，而不是绝页面的密码校验，密码在前端获取到的js文件中都可以直接查看到

**Comment by recoluan** [comment]
这种静态网站做不到那种绝对的加密，后期会将代码中的密文调整为加密后的文本，增强加密性。

**Comment by recoluan** [comment]
最新版本中已经将js中的密码明文变为密文，增加安全性，请看 [文档](https://vuepress-theme-reco.recoluan.com/views/1.x/password.html)。
