### ISSUE TITLE
解析行内元素错误：如<kbd>

### ISSUE THREAD

**Issue by woytu** [vuepress-reco/vuepress-theme-reco#142]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
见截图

#### Other relevant information
见截图

- Your OS: 
- Node.js version: v12.13.0
- VuePress version: 1.3.1
- VuePress-theme-reco version: 1.3.2
- Which package manager did you use for the install(npm/cnpm/yarn)? npm

![image](https://user-images.githubusercontent.com/30252550/76828915-f8e10d80-685c-11ea-88a3-cc1af83dc14b.png)
![image](https://user-images.githubusercontent.com/30252550/76829156-76a51900-685d-11ea-92de-5564039ed023.png)

**Comment by recoluan** [comment]
我测试了一下是没问题的（见下图），你再检查一下是不是其他方面的问题。
<img width="287" alt="WX20200317-174742@2x" src="https://user-images.githubusercontent.com/18067907/76843902-7580e580-6877-11ea-9d93-eb8b580f2307.png">

**Comment by woytu** [comment]
请问这个库中的插件会与官方的插件冲突吗

**Comment by recoluan** [comment]
> 请问这个库中的插件会与官方的插件冲突吗

这个目前还真不清楚，你先通过排除法看看跟哪个插件相关，然后再想解决方案。

**Comment by recoluan** [comment]
我发现最新的 `vuepress` 版本，在写文档的时候写入标签，实时刷新时就会出现你描述的问题，不只是 `<kbd>`
