### ISSUE TITLE
Question - Can we remove the footer from the homepage?

### ISSUE THREAD

**Issue by TheSecEng** [vuepress-reco/vuepress-theme-reco#144]
Are we able to remove this from the footer? How?

<img width="808" alt="2020-03-22_12-14-38" src="https://user-images.githubusercontent.com/32599364/77254325-c194a700-6c36-11ea-8e60-ac103a9d0ce8.png">

**Comment by recoluan** [comment]
Its purpose is to promote the theme, all there is no API to remove it, if you must remove it, you can through CSS or modify the source code.
