### ISSUE TITLE
report an error “localStorage is not defined” when build   version:"vuepress-theme-reco": "2.0.0-beta.41"

### ISSUE THREAD

**Issue by VaCameos** [vuepress-reco/vuepress-theme-reco#144]
## Bug report
 I use a custom components, and i import a TS file in VUE file .  In the TS file , I use the API 'localStorage'. My code works fine locally , 
but it throw a error when i build it. My code is as follows
#### What is actually happening?
error report
![image](https://user-images.githubusercontent.com/103049831/198820634-825306cf-93b0-4aab-954b-c0ecd4848b52.png)

my code
![image](https://user-images.githubusercontent.com/103049831/198820709-c88bb538-eb44-4608-8c5c-ece77ba001ae.png)
![image](https://user-images.githubusercontent.com/103049831/198820735-d0822883-87b9-4fae-a260-f9199097f761.png)

And I found another suspected bug ， but I'm not sure it is .So let me just say that by the way . 
When I first went to the home page, there seemed to be something wrong with the pagination  . as follow
first 
![image](https://user-images.githubusercontent.com/103049831/198820909-91c3643f-85da-42cc-a553-e42428843487.png)

Switch from another page to the home page
![image](https://user-images.githubusercontent.com/103049831/198820965-915f8404-5bf3-4812-a87e-b470882dedce.png)

#### Other relevant information

- Your OS: win10
- Node.js version: v 18.2.0
- VuePress version:  "2.0.0-beta.51"
- VuePress-theme-reco version: "2.0.0-beta.41"
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? yarn

**Comment by VaCameos** [comment]
第一个问题是因为在挂载前使用了localstorage ，在mounted钩子里使用则不报错 ， 第二个问题尚未解决

**Comment by recoluan** [comment]
试一下 vuepress@2.0.0-beta.60 和 vuepress-theme-reco@2.0.0-beta.44
