### ISSUE TITLE
项目安装完依赖后正常运行，但保存就报错怎么回事？

### ISSUE THREAD

**Issue by luoxuancong** [vuepress-reco/vuepress-theme-reco#146]
### 如图：
![1585301336(1)](https://user-images.githubusercontent.com/33108362/77742123-edf25e00-7050-11ea-8bdc-79e25cd34d30.jpg)

**Comment by recoluan** [comment]
这个可能是 `@vuepress/plugin-blog` 这个官方插件的问题，也可能是我配置的问题，我最近也受到了这个问题的困扰，但是还没有找到原因，如果你解决了，欢迎回来说明一下。
