### ISSUE TITLE
2.x项目跑不起来，求助，而且和旧版本的端口冲突

### ISSUE THREAD

**Issue by lty121918** [vuepress-reco/vuepress-theme-reco#146]
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/62701262/202846319-1554b1f8-bd9a-4b18-9646-06160c5021ba.png">
编译如图，网页没有报错，就是白屏，是不是tailwindcss版本问题？

**Comment by zhao-yi-fan** [comment]
我也有一样的问题

**Comment by senmu-a** [comment]
#154 警告问题在这个 issue reco 已经回答，白屏问题的话需要更加详细的信息才能排查

**Comment by recoluan** [comment]
大家试一下 vuepress@2.0.0-beta.60 和 vuepress-theme-reco@2.0.0-beta.44
