### ISSUE TITLE
手机浏览，在首页时，侧边栏的"Home"是否可以不显示

### ISSUE THREAD

**Issue by taojunnan** [vuepress-reco/vuepress-theme-reco#147]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?

![image](https://user-images.githubusercontent.com/18263998/77810738-1c178280-70d1-11ea-97dc-1c0ecd273986.png)

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version: 
- VuePress-theme-reco version: 
- Which package manager did you use for the install(npm/cnpm/yarn)?

**Comment by recoluan** [comment]
因为首页的 markdown 文件也是可以书写内容的，所以当首页有内容时，这里就有必要显示了，这是一个全局的标题显示，所以暂时无法配置显示和隐藏，如果后期我找打更好的解决方案，我会尝试处理的，感谢你的支持。
