### ISSUE TITLE
markdown设置行号不显示无效

### ISSUE THREAD

**Issue by chenweigao** [vuepress-reco/vuepress-theme-reco#148]
#### What problem does this feature solve?
在config.js中设置：

```
  markdown: {
     lineNumbers: false
  },
```
但是界面依旧显示行号
#### How should this be implemented in your opinion?
如上所述

#### Are you willing to work on this yourself?
yes

**Comment by recoluan** [comment]
应该删除掉 `lineNumbers `，而不是将其设置为 `false`，你再试一下。

**Comment by chenweigao** [comment]
> 应该删除掉 `lineNumbers `，而不是将其设置为 `false`，你再试一下。

好的，非常感谢
