### ISSUE TITLE
not respecting palette2.styl codeBGLightColor

### ISSUE THREAD

**Issue by pdimens** [vuepress-reco/vuepress-theme-reco#149]
- [x ] I confirm that this is an issue rather than a question.

#### What is actually happening?
In the theme folder `/styles/palette2.styl` on line 13 is a declaration that the background of code blocks under the light mode should be `#f8f8f8`, however this color is not respected in the rendered pages (or the example website). In general, the code blocks do not change color when switching light and dark modes.

#### Other relevant information

- Your OS: Arch Linux
- Node.js version: 13.11.0
- VuePress version: latest
- VuePress-theme-reco version: latest
- Which package manager did you use for the install(npm/cnpm/yarn)? yarn

**Comment by recoluan** [comment]
I'm really sorry for the trouble this file has brought to you. In fact, this file is to be deleted. Due to my negligence, I have kept it until now, and I will delete this file in the next version.

**Comment by pdimens** [comment]
Thanks. What file/line needs to be changed to use a light theme for code blocks?

**Comment by recoluan** [comment]
Light-colored code blocks do not currently exist, but are planned.
