### ISSUE TITLE
pnpm build error

### ISSUE THREAD

**Issue by zhaopan-pan** [vuepress-reco/vuepress-theme-reco#150]
I clone this project. First, I used pnpm install to install dependencies。When I ran the pnpm build, I found this error：
![error](https://user-images.githubusercontent.com/30975538/205024005-8a336867-9e2c-4e9f-9c8c-85c1cc18b97c.jpg)
After troubleshooting, it is found that @ vuepress reco/vuepress plugin page depends on @ vuepress reco/shared，
![image](https://user-images.githubusercontent.com/30975538/205025793-b62f7876-6894-4c92-aab2-d2ca7d845906.png)
I temporarily solved this problem with a hack method. I executed the @ vuepress reco/shared build command ahead of time. Now I can successfully run the pnpm build. But I don't think this is the best solution.

- OS: mac os
- Node.js version: v14.19.1
- VuePress version: 2.0.0-beta.51
- VuePress-theme-reco version: 2.0.0-beta.41
- pnpm:7.15.0

**Comment by recoluan** [comment]
Please take a look at the commit [8383f94](https://github.com/vuepress-reco/vuepress-theme-reco/commit/8383f940086c527095eca182b94ee7454a4c22d3). There is a dependency error that causes this bug
