### ISSUE TITLE
目前页面留白太多，建议增加这个功能

### ISSUE THREAD

**Issue by jimixy** [vuepress-reco/vuepress-theme-reco#152]
目前的侧栏会把文章和文章下面的标题提取出来放到侧边栏，形成树结构。

但是这样会显得有些混乱，尤其是在层级比较多的情况下。

所以希望提供这样的功能选项：

左侧只显示文章列表，
文章的右侧给一片固定的区域展示文章内部提取出来的标题结果。

有一些例子可以参考一下：
https://d.umijs.org/guide/control-route-generate

https://www.yvescoding.com/rcpress/config/

![image](https://user-images.githubusercontent.com/21176977/77879781-c2a88280-728d-11ea-98c9-65a809967ac0.png)

**Comment by recoluan** [comment]
正有此意，目前 navbar 、sidebar 以及sidebar 的子集是混合在一起的，后期会拆分，正在计划中。

因为需要页面架构需要大动，所以进程会比较缓慢，请继续支持主题。

**Comment by jimixy** [comment]
> 正有此意，目前 navbar 、sidebar 以及sidebar 的子集是混合在一起的，后期会拆分，正在计划中。
> 
> 因为需要页面架构需要大动，所以进程会比较缓慢，请继续支持主题。

太好了，我会继续关注，支持的

**Comment by fanzheming** [comment]
这样就太好拉。我现在都是手动去nav中hard code方式去编辑。每次写一篇就要去动nav配置好麻烦哈哈

**Comment by recoluan** [comment]
`1.5.3` 中已经增加副侧边栏。

**Comment by dennislblog** [comment]
你好，请问如果想保持正文标题和sidebar不分开，请问有option提供吗？
