### ISSUE TITLE
最新版本无法启动

### ISSUE THREAD

**Issue by 1455668754** [vuepress-reco/vuepress-theme-reco#154]
![image](https://user-images.githubusercontent.com/88491446/208399629-f5e759fe-e596-4487-8412-3fb63096147b.png)
启动后，报错该内容

**Comment by recoluan** [comment]
这个只是警告，不影响启动的

**Comment by recoluan** [comment]
提示已经被移除，将在下一个版本中体现

**Comment by Shmaur** [comment]
我也遇到这个问题，预览不成功，是空白页面

**Comment by recoluan** [comment]
谁能提供一下具体代码，我看一下

**Comment by causes-wang** [comment]
我这边也一样。

测试环境为：

- node：`v16.19.1`
- npm：`8.19.3`
- yarn：`1.22.19`
- 华为云服务器：`Linux master 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`，`CentOS 7.5 64bit (64-bit)`

使用快速开始的 yarn 安装：

```yarn
# 初始化，并选择 2.x
yarn global add @vuepress-reco/theme-cli@1.0.7
theme-cli init
```

之后，使用 `yarn dev` 启动后就是白屏。

**Comment by recoluan** [comment]
控制台有具体报错吗

**Comment by causes-wang** [comment]
> 控制台有具体报错吗

控制台没有具体报错，只有启动成功后显示的地址。还有一个状态，就是页面一直没加载出来的样子，F12 无法打开控制台，防火墙是正常放开的，并且我在本地测试了一下也是这个状态（本地也是 Linux，可能和 Linux 有关？），我打算晚上用 windows 测试一下。

![image](https://user-images.githubusercontent.com/44577765/222062521-89eff69c-304e-4db2-8e83-c499cf3077db.png)

![image](https://user-images.githubusercontent.com/44577765/222062592-660b694f-7f44-4107-a05a-bc513fc0ade8.png)

**Comment by causes-wang** [comment]
> 我打算晚上用 windows 测试一下。

windows 启动正常……离谱

**Comment by recoluan** [comment]
感觉是不是爆内存了，卡爆了^_^

**Comment by causes-wang** [comment]
> 感觉是不是爆内存了，卡爆了^_^

按照公司那垃圾电脑真有可能……
