### ISSUE TITLE
[feature request]新增阅读时间

### ISSUE THREAD

**Issue by Leecason** [vuepress-reco/vuepress-theme-reco#155]
#### What problem does this feature solve?

显示该文章大概需要的阅读时间

#### How should this be implemented in your opinion?

在文章头部和在文章列表可以显示该文章阅读时间

#### Are you willing to work on this yourself?

https://github.com/darrenjennings/vuepress-plugin-reading-time 这个插件是不是可以使用

**Comment by recoluan** [comment]
经过调研，此功能并不是影响阅读体验的一个必要元素，所以决定不支持此功能。

**Comment by Leecason** [comment]
> 经过调研，此功能并不是影响阅读体验的一个必要元素，所以决定不支持此功能。

能方便告诉一下调研的具体细节么，我看很多国外文章在文章列表和文章内容里面都会有「阅读时间」的展示，虽然不是必要元素，但还是挺常见的，能在没有看文章的情况下了解到文章大概的篇幅，在心里有个数（很多时候大篇幅的文章在时间不充裕的情况下是不会选择去看的）。

希望支持此功能。

参考:
medium 的文章列表和文章内容：https://codeburst.io/functional-patterns-with-typescript-7fdb4d6afe8a
dev 的文章列表和文章内容：https://dev.to/t/javascript
vuedose 的文章内容 https://vuedose.tips/use-composition-api-to-easily-handle-api-requests-in-vue-js

**Comment by recoluan** [comment]
作为一个作者，写一篇文章就是为了让别人看，那加上这个功能的意义是什么呢？降低一部分曝光率吗？

如果文章一定要篇幅较长的话，作为作者，去编排文章的时候更应该注意结论先行，通过各种写作技巧吸引读者，而不是考虑读者的时间问题。

如果真的觉得这个功能必要，可以考虑 DIY。
