### ISSUE TITLE
Why is there a "/1" at the end of category link?

### ISSUE THREAD

**Issue by franklinqin0** [vuepress-reco/vuepress-theme-reco#156]
https://github.com/vuepress-reco/vuepress-theme-reco/blob/61c8e7a0b8e73ed8d89679c28de5daf764d6f1ff/packages/vuepress-theme-reco/src/client/components/Home/Blog.vue#L17

I find it weird that the "/1" is there. Why don't we just do the following?

```
<router-link class="category-link" :to="`/categories/${key}/`">
```

**Comment by recoluan** [comment]
Because the data is already paged, it jumps to the first page by default.
