### ISSUE TITLE
最新文章怎么跑最后一页面去了怎么配置？

### ISSUE THREAD

**Issue by fanux** [vuepress-reco/vuepress-theme-reco#157]
我刚发了一篇文章 2020/4/1号的 发现被排在了最后。是不是有什么配置可以让最新文章置顶

**Comment by Rackar** [comment]
配置日期时注意要补0，比如2020-04-01 否则解析出的日期是错误的

**Comment by fanux** [comment]
```
title: 傻傻分不清楚的kubernetes证书
date: 2020-04-01
tags:
 - kubeadm
categories:
 - develo
```
应该没有问题

是不是因为我别的博客都没配置日期引起的？

**Comment by Rackar** [comment]
> ```
> title: 傻傻分不清楚的kubernetes证书
> date: 2020-04-01
> tags:
>  - kubeadm
> categories:
>  - develo
> ```
> 
> 应该没有问题
> 
> 是不是因为我别的博客都没配置日期引起的？

😅

**Comment by fanux** [comment]
![image](https://user-images.githubusercontent.com/8912557/78451725-ea4a8100-76b9-11ea-9d03-e608a2ef5df7.png)
![image](https://user-images.githubusercontent.com/8912557/78451737-f7677000-76b9-11ea-99a3-473ddbe02b52.png)


这个四月1号拍到3月1号后面去了

**Comment by recoluan** [comment]
@fanux 按照 Rackar 的说法，你的问题现在解决了吗？

**Comment by fanux** [comment]
没唉，我是没写错的

**Comment by fanux** [comment]
https://github.com/sealyun/blog/tree/master/docs/views/container

**Comment by Rackar** [comment]
尝试把日期全加上再找问题吧
