### ISSUE TITLE
The block of blog is not rendered

### ISSUE THREAD

**Issue by LasyIsLazy** [vuepress-reco/vuepress-theme-reco#157]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?

In production mode, the block of blog in home page is not rendered and the footer is rendered twice .

Everything works fine in development mode.
![image](https://user-images.githubusercontent.com/18400251/212310399-1c78e34c-cdea-43eb-8744-dfa488c2d774.png)

Parts of frontmatter:
```
modules: 
  - Banner
  - Blog
  - Footer
   ```

Additionaly, there is an error in console
```JavaScript
framework-f055c134.js:1 TypeError: (e || []).slice is not a function
    at vs.fn (app-ad323f5e.js:10:38514)
    at vs.run (framework-f055c134.js:1:3894)
    at get value [as value] (framework-f055c134.js:1:11992)
    at Rt (framework-f055c134.js:1:11070)
    at Proxy.<anonymous> (app-ad323f5e.js:10:38861)
    at Bn (framework-f055c134.js:1:15368)
    at de (framework-f055c134.js:1:42866)
    at vs.w [as fn] (framework-f055c134.js:1:42954)
    at vs.run (framework-f055c134.js:1:3894)
    at G.u.update (framework-f055c134.js:1:43258)
```

After some debug, I found the problem
![image](https://user-images.githubusercontent.com/18400251/212308709-25248966-a911-49cc-9889-364938815795.png)
This `e` variable is an `object` which doesn't have a `slice` function.

I searched the source code of reco and found this, the `posts` may be the `e` variable.

https://github.com/vuepress-reco/vuepress-theme-reco/blob/169685daea7927bb711cddda1c93679f47f02e18/packages/vuepress-theme-reco/src/client/components/Home/Blog.vue#L43-L63

This may be the code which throw this error.

After further search, I found the code where the value comes from.

https://github.com/vuepress-reco/vuepress-theme-reco/blob/169685daea7927bb711cddda1c93679f47f02e18/packages/%40vuepress-reco/plugin-page/src/client/composable/usePageData.ts#L6-L14

In production mode, theses three variables will be the same value because `Symbol.for('') === Symbol.for('')`

The `posts` variable may be covered by another variable.

I don't know whether this problem cause the final render error but there must be some problem.

#### Other relevant information

- Your OS: Mac 13.1 (22C65)
- Node.js version: 18.13.0
- VuePress version: 2.0.0-beta.60
- VuePress-theme-reco version: 2.0.0-beta.43
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? pnpm

**Comment by recoluan** [comment]
Try it with 2.0.0-beta.44

**Comment by LasyIsLazy** [comment]
> Try it with 2.0.0-beta.44

Thx, it works.
