### ISSUE TITLE
2.x打包后 页面样式丢失问题

### ISSUE THREAD

**Issue by babalash0728** [vuepress-reco/vuepress-theme-reco#158]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
当我执行npm run build后，控制台会打印以下信息：
⠹ Rendering pages /[Vue warn]: injection "Symbol()" not found.
[Vue warn]: injection "Symbol()" not found.
[Vue warn]: injection "Symbol()" not found.
[Vue warn]: injection "Symbol()" not found.
[Vue warn]: injection "Symbol()" not found.
[Vue warn]: injection "Symbol()" not found.
[Vue warn]: injection "Symbol()" not found.
[Vue warn]: injection "Symbol()" not found.
[Vue warn]: injection "Symbol()" not found.
[Vue warn]: injection "Symbol()" not found.
[Vue warn]: injection "Symbol()" not found.
[Vue warn]: injection "Symbol()" not found.
⠸ Rendering pages /blogs/other/guide.html[Vue warn]: injection "Symbol()" not found.
[Vue warn]: injection "Symbol()" not found.
[Vue warn]: injection "Symbol()" not found.
[Vue warn]: injection "Symbol()" not found.
[Vue warn]: injection "Symbol()" not found.
...
当我运行dist文件夹里的index.html 首页样式全部丢失
请问是什么原因? 有什么解决办法么

#### Other relevant information

- Your OS: win10
- Node.js version: v16.14.0
- VuePress version: 2.0.0-beta.60
- VuePress-theme-reco version: 2.0.0-beta.43
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?
- npm

**Comment by recoluan** [comment]
使用 2.0.0-beta.44 版本试一下

**Comment by babalash0728** [comment]
问题已解决 是我自己的问题 和主题没关系

**Comment by recoluan** [comment]
那些 warning 提示是跟主题有关的
