### ISSUE TITLE
primaryColor配置不生效

### ISSUE THREAD

**Issue by Ucely** [vuepress-reco/vuepress-theme-reco#160]
<img width="991" alt="image" src="https://user-images.githubusercontent.com/92929085/215331054-5e869b3e-7a3e-4ba4-99ea-338e6d226eda.png">

大佬您好，primaryColor 在config文件里修改不生效，依旧是默认配色。谢谢大佬～！鞠躬🙇

**Comment by recoluan** [comment]
版本多少啊

**Comment by recoluan** [comment]
试一下最新版本 2.0.0-beta.48
