### ISSUE TITLE
手机端访问文章404

### ISSUE THREAD

**Issue by sunday521** [vuepress-reco/vuepress-theme-reco#162]
本地运行没问题，远程运行电脑端能跳转文章，手机端跳转报404

注意到官网访问文章时的链接没有添加 https://前缀
![20230202124130](https://cdn.staticaly.com/gh/sunday521/postimg.wyun521.top@main/img/2023/20230202124130.png)

但是我的项目**部分链接**一开始鼠标hover链接没有https://前缀，过了1s又变成了有https://前缀的链接

![20230202124804](https://cdn.staticaly.com/gh/sunday521/postimg.wyun521.top@main/img/2023/20230202124804.png)

等待1s后

![20230202124853](https://cdn.staticaly.com/gh/sunday521/postimg.wyun521.top@main/img/2023/20230202124853.png)

**Comment by recoluan** [comment]
使用 2.0.0-beta.50 试一下
