### ISSUE TITLE
【SEO 优化】请求添加 sitemap2 或其他站点生成插件

### ISSUE THREAD

**Issue by culome** [vuepress-reco/vuepress-theme-reco#163]
大佬您好，我遇到了博客不被搜索引擎收录的问题，请问您有空可否帮忙内置 sitemap 等站点生成的插件，用于SEO优化？非常感谢。

例如：
https://www.npmjs.com/package/vuepress-plugin-sitemap2

https://github.com/ekoeryanto/vuepress-plugin-sitemap (这是历史版本的，目前已经不支持)

灵感来源是：

https://zhuanlan.zhihu.com/p/477185840

**Comment by yxzlwz** [comment]
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/75941562/e5259a9e-aeb2-42b5-aa46-d80751f2ed2a)

可以自己加，框架没必要那么沉
