### ISSUE TITLE
安装主题之后 运行之后浏览器报错 global is not defined

### ISSUE THREAD

**Issue by ShnHz** [vuepress-reco/vuepress-theme-reco#163]
只在config.js配置了theme: 'reco'
![image](https://user-images.githubusercontent.com/34496965/78740422-4991e500-7989-11ea-98c9-94954fcdc94c.png)

**Comment by ShnHz** [comment]
这个是跟我的vuepress版本有关系吗

**Comment by recoluan** [comment]
这个应该就是依赖没有安装完整，删除node_modules重新安装基本就可以解决。
