### ISSUE TITLE
publish为false的文章的分类信息被记录了

### ISSUE THREAD

**Issue by JessenPan** [vuepress-reco/vuepress-theme-reco#164]
```
date: 2020-4-9
tags:
 - 写作技巧
categories:
 - 写作技巧
 - 职业发展
publish: false
```
这样的frontmatter，在发布后。分类和tag都把这篇文章算进去了

**Comment by recoluan** [comment]
我在本地测试着是没有问题的，你的主题版本是不是比较低啊

**Comment by wusisu** [comment]
Same problem.

It seems that following the instruction in [README](https://github.com/vuepress-reco/vuepress-theme-reco) starting a blog via `npx @vuepress-reco/theme-cli init my-blog` and choosing `afternoon-grocery` got a dependency of `"vuepress-theme-reco": "1.0.8-alpha.3"`. In fact, most of the dependencies look outdated.
```
root@home:~/blog# npm outdated
Package                             Current         Wanted  Latest  Location
@vuepress/plugin-medium-zoom  1.0.0-alpha.0  1.0.0-alpha.0   1.5.0  @wusisu/blog
@vuepress/plugin-pwa          1.0.0-alpha.3  1.0.0-alpha.3   1.5.0  @wusisu/blog
vuepress                              1.0.3          1.0.3   1.5.0  @wusisu/blog
vuepress-theme-reco           1.0.8-alpha.3  1.0.8-alpha.3   1.4.5  @wusisu/blog
```

## Fixing
Change dependency as follow and `npm i` to upgrade node_modules works for me.
```
"dependencies": {
    "vuepress": "^1.5.0",
    "vuepress-theme-reco": "^1.4.5",
    "@vuepress/plugin-medium-zoom": "^1.5.0",
    "vuepress-plugin-flowchart": "^1.4.3",
    "@vuepress/plugin-pwa": "^1.5.0"
  }
```

It's time to upgrade `afternoon-grocery` including its [dependency](https://github.com/vuepress-reco/vuepress-theme-reco-demo/blob/demo/afternoon-grocery/package.json#L14-L20).

**Comment by 122177638** [comment]
> Same problem.
> 
> It seems that following the instruction in [README](https://github.com/vuepress-reco/vuepress-theme-reco) starting a blog via `npx @vuepress-reco/theme-cli init my-blog` and choosing `afternoon-grocery` got a dependency of `"vuepress-theme-reco": "1.0.8-alpha.3"`. In fact, most of the dependencies look outdated.
> 
> ```
> root@home:~/blog# npm outdated
> Package                             Current         Wanted  Latest  Location
> @vuepress/plugin-medium-zoom  1.0.0-alpha.0  1.0.0-alpha.0   1.5.0  @wusisu/blog
> @vuepress/plugin-pwa          1.0.0-alpha.3  1.0.0-alpha.3   1.5.0  @wusisu/blog
> vuepress                              1.0.3          1.0.3   1.5.0  @wusisu/blog
> vuepress-theme-reco           1.0.8-alpha.3  1.0.8-alpha.3   1.4.5  @wusisu/blog
> ```
> 
> ## Fixing
> Change dependency as follow and `npm i` to upgrade node_modules works for me.
> 
> ```
> "dependencies": {
>     "vuepress": "^1.5.0",
>     "vuepress-theme-reco": "^1.4.5",
>     "@vuepress/plugin-medium-zoom": "^1.5.0",
>     "vuepress-plugin-flowchart": "^1.4.3",
>     "@vuepress/plugin-pwa": "^1.5.0"
>   }
> ```
> 
> It's time to upgrade `afternoon-grocery` including its [dependency](https://github.com/vuepress-reco/vuepress-theme-reco-demo/blob/demo/afternoon-grocery/package.json#L14-L20).

plugin-medium-zoom这个插件可以用吗？你们的图片可以放大吗？

**Comment by recoluan** [comment]
> Same problem.
> 
> It seems that following the instruction in [README](https://github.com/vuepress-reco/vuepress-theme-reco) starting a blog via `npx @vuepress-reco/theme-cli init my-blog` and choosing `afternoon-grocery` got a dependency of `"vuepress-theme-reco": "1.0.8-alpha.3"`. In fact, most of the dependencies look outdated.
> 
> ```
> root@home:~/blog# npm outdated
> Package                             Current         Wanted  Latest  Location
> @vuepress/plugin-medium-zoom  1.0.0-alpha.0  1.0.0-alpha.0   1.5.0  @wusisu/blog
> @vuepress/plugin-pwa          1.0.0-alpha.3  1.0.0-alpha.3   1.5.0  @wusisu/blog
> vuepress                              1.0.3          1.0.3   1.5.0  @wusisu/blog
> vuepress-theme-reco           1.0.8-alpha.3  1.0.8-alpha.3   1.4.5  @wusisu/blog
> ```
> 
> ## Fixing
> Change dependency as follow and `npm i` to upgrade node_modules works for me.
> 
> ```
> "dependencies": {
>     "vuepress": "^1.5.0",
>     "vuepress-theme-reco": "^1.4.5",
>     "@vuepress/plugin-medium-zoom": "^1.5.0",
>     "vuepress-plugin-flowchart": "^1.4.3",
>     "@vuepress/plugin-pwa": "^1.5.0"
>   }
> ```
> 
> It's time to upgrade `afternoon-grocery` including its [dependency](https://github.com/vuepress-reco/vuepress-theme-reco-demo/blob/demo/afternoon-grocery/package.json#L14-L20).

You are right.
