### ISSUE TITLE
@vuepress-reco/vuepress-plugin-extract-code 的console.log在发布时没有清掉

### ISSUE THREAD

**Issue by Ling310** [vuepress-reco/vuepress-theme-reco#165]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?
vuepress-plugin-extract-code的 RecoDemo.vue 在87行写了console.log(key.indexOf('code-'))，会在使用时输出，希望可以干掉。

- Your OS: 
- VuePress version: 1.3.1
- vuepress-plugin-extract-code version: 1.0.3
- Which package manager did you use for the install(npm/cnpm/yarn)? yarn

**Comment by Ling310** [comment]
> * [x]  I confirm that this is an issue rather than a question.
> 
> ## Bug report
> #### What is actually happening?
> vuepress-plugin-extract-code的 RecoDemo.vue 在82行和87行写了console.log，会在使用时输出，希望可以干掉。
> 
> * Your OS:
> * VuePress version: 1.3.1
> * vuepress-plugin-extract-code version: 1.0.3
> * Which package manager did you use for the install(npm/cnpm/yarn)? yarn

**Comment by recoluan** [comment]
已经删除测试代码，请使用 `1.0.4`。
