### ISSUE TITLE
左侧边栏如何自定义

### ISSUE THREAD

**Issue by zicheqingluo** [vuepress-reco/vuepress-theme-reco#166]
**Is your feature request related to a problem? Please describe.**

期望能够制定某个页面配置左侧边栏，看文档中提到了自定义，但没看到怎么配置

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zicheqingluo** [comment]
目前在config.js配置sidebar 就全局生效了

**Comment by recoluan** [comment]
Sidebar has been change to [series](http://v2.vuepress-reco.recoluan.com/docs/theme/series.html).
