### ISSUE TITLE
SidebarLinks.vue组件报错

### ISSUE THREAD

**Issue by Lichun0529** [vuepress-reco/vuepress-theme-reco#168]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
![image](https://user-images.githubusercontent.com/52193173/79078861-ec59b300-7d3d-11ea-947d-ce01efca8bba.png)

#### Other relevant information
![image](https://user-images.githubusercontent.com/52193173/79078910-2a56d700-7d3e-11ea-804a-cebda215d490.png)
把两个null改成undefined就不报错了，不知道原因

- Your OS: win10/64
- Node.js version: 12.14.1
- VuePress version: 1.4.0
- VuePress-theme-reco version:1.x
- Which package manager did you use for the install(npm/cnpm/yarn)?
npm

**Comment by recoluan** [comment]
将在下个版本中修复
