### ISSUE TITLE
中文名字分类的文章，开发环境每次更改文章内容都需要重启项目，否则直接报404找不到该文章

### ISSUE THREAD

**Issue by komorebi-crush** [vuepress-reco/vuepress-theme-reco#169]
## Bug report
中文名字分类的文章，开发环境每次更改文章内容都需要重启项目，否则直接报404找不到该文章

#### What is actually happening?
在中文分类下的博客文章，开发环境下文章内容发生变化，无法预览该博客文章，对应的博客文章路径下则显示404，当重启项目过后，又能正常预览；

文件夹目录结构
````
└─ blogs
      └─ 文件夹使用中文名字 // 

````
#### Other relevant information

- Your OS:  window11
- Node.js version: 18.4.0
- VuePress version: 2.0.0-beta.60
- VuePress-theme-reco version: 2.0.0-beta.53
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? npm

**Comment by shichaohui** [comment]
生产也有问题：
* 刷新页面会 404；
* 右键在新标签打开文章会 404；

**Comment by WXL570CN** [comment]
确实涉及到中文就会出问题！
