### ISSUE TITLE
npm run build后，生成的index.html 失去了样式

### ISSUE THREAD

**Issue by duktig666** [vuepress-reco/vuepress-theme-reco#170]
- [x] I confirm that this is an issue rather than a question.

## Bug report
执行 npm run dev 正常，但是执行npm run build后，生成的index.html 失去了样式

#### What is actually happening?
![image](https://user-images.githubusercontent.com/53132746/226831559-c22c7e61-59a8-407c-9a81-281beac2ecd6.png)

#### Other relevant information

- Your OS:  mac
- Node.js version: 16.17.1
- VuePress version:  1.9.2
- VuePress-theme-reco version: 1.16.17
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? npm and yarn

**Comment by recoluan** [comment]
项目不在根目录下，需要配置base，指定子目录

**Comment by duktig666** [comment]
"dest": "docs/.vuepress/dist",
docsDir: 'docs',

![image](https://user-images.githubusercontent.com/53132746/226837568-1a0ffa4d-f668-4ef7-b946-ad338670c08f.png)

这样配置应该没问题

**Comment by duktig666** [comment]
https://blog.csdn.net/weixin_57677300/article/details/128017651

找到了解决办法，这样可以解决。 但是访问链接也会加 #

从这个 https://duktig.cn/  
变成 http://duktig.cn/#/
