### ISSUE TITLE
The status of the blog module is not keep after return.

### ISSUE THREAD

**Issue by shichaohui** [vuepress-reco/vuepress-theme-reco#171]
#### What is actually happening?

The status of the blog module is not maintained after jumping to the page and returning to the home page.

From the home page, you jump to the second page (or other page) of the blog module, and then back to the home page, where the blog module changes back to the first page.

#### Other relevant information

- Your OS: Windows 10
- Node.js version: v18.15.0
- VuePress version: 2.0.0-beta.61
- VuePress-theme-reco version: 2.0.0-beta.55
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? yarn

**Comment by recoluan** [comment]
Because the paging of the blog data on the home page is parsed according to the total number of data, and the route does not change when switching the page, so the paging of the home page is actually fake.

**Comment by recoluan** [comment]
2.x has resolved this problem.
