### ISSUE TITLE
大佬请问preview如何生成的

### ISSUE THREAD

**Issue by kromalee** [vuepress-reco/vuepress-theme-reco#174]
大佬请问readme的preview如何生成的

**Comment by smallsunnyfox** [comment]
readme的preview是指啥

**Comment by smallsunnyfox** [comment]
> 大佬请问readme的preview如何生成的
readme的preview是指啥

**Comment by kromalee** [comment]
> > 大佬请问readme的preview如何生成的
> > readme的preview是指啥

https://camo.githubusercontent.com/6c5e2558c31084ceaabd8a441df19948431e3f45/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30312f31332f6b6531566972536851524c6e4564372e706e67

**Comment by recoluan** [comment]
可以去网上找一些 Photoshop 样机模板，自己修改里面的图片即可。
