### ISSUE TITLE
v1.4.3~v1.4.5版本的tag路由生成错误

### ISSUE THREAD

**Issue by Saszr** [vuepress-reco/vuepress-theme-reco#176]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?

详细的tag的路由跳转地址v1.4.2 之前是 /tags/xxxx/

v1.4.3~v1.4.5 
homeBlog右侧Tag区域，Tag页面上方Tag区域点击tag跳转 /tag/xxxx/，正常显示

文章tag点击跳转的路由地址 /tags/xxxx/，结果404

#### Other relevant information

- Your OS: 
- Node.js version: v10.16.0
- VuePress version: v1.4.1
- VuePress-theme-reco version: v1.4.3~v1.4.5
- Which package manager did you use for the install(npm/cnpm/yarn)? yarn

**Comment by fengchenzhihun1** [comment]
遇到了同样的问题

**Comment by smallsunnyfox** [comment]
https://github.com/vuepress-reco/vuepress-theme-reco/issues/180#issuecomment-629065010
