### ISSUE TITLE
文章摘要中的图片未添加max-width:100%适配

### ISSUE THREAD

**Issue by csdoker** [vuepress-reco/vuepress-theme-reco#177]
文章内容里的图片是有max-width:100%的样式的，但是文章列表摘要中的图片没加这个样式。。能加上吗。。

**Comment by 122177638** [comment]
> 文章内容里的图片是有max-width:100%的样式的，但是文章列表摘要中的图片没加这个样式。。能加上吗。。
你的图片可以放大吗，使用vuepress官方zoom插件的情况
