### ISSUE TITLE
安装vuepress-reco/vuepress-plugin-bulletin-popover后使用该插件后自己的博客却显示不出来，不知道为什么，代码格式和语法都没有错误，但就是一加入就显示不出来

### ISSUE THREAD

**Issue by ANGLEOZZZFFFYYY** [vuepress-reco/vuepress-theme-reco#177]
- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version: 
- VuePress-theme-reco version: 
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?

**Comment by recoluan** [comment]
把你的配置发一下，无法复现
