### ISSUE TITLE
how to include new font-family

### ISSUE THREAD

**Issue by fengfengyuyu** [vuepress-reco/vuepress-theme-reco#179]
## Feature request
I want to add new font-family. 

#### What problem does this feature solve?
But i have no idea to realise it like normal vue project.

#### How should this be implemented in your opinion?
1. download open font type files, such as 'oshidashi-m-gothic'
2. under .vuepress folder, create an assets folder , then push the new font file into assets folder.
3. under style folder, create a new index.styl, then add the content:
`h1,span.site-name{
     font-family:'oshidashi-m-gothic'!important;
     src:url('../assets/Oshidashi-M-Gothic.otf')
 }`

#### Are you willing to work on this yourself?
unfortunatelly, the above method doesn`t work on. Would you be kindly to point out what wrong i had made? Thanks a lot!

**Comment by smallsunnyfox** [comment]
My Steps
1. put font file in `.vuepress/public`
2. add following styles in `.vuepress/styles/palette.styl`
```
@font-face
{
  font-family: MEOW;
  src: url('/FZMiaoWuJW.ttf');
}

body, html {
  font-family: MEOW!important;
}
```
