### ISSUE TITLE
Tag标签生成的路径不对

### ISSUE THREAD

**Issue by YLDJack** [vuepress-reco/vuepress-theme-reco#180]
点击博客右上角Tag,会跳转到/Tag/目录下，而点击文章下方的标签，会跳转到/Tags/目录下。不知道这个是不是bug，如果不是，麻烦大佬提供一下解决方法。多谢！

**Comment by DaZiYuan** [comment]
同样的问题，
重现步骤：
- cli创建工程选择 afternoon-grocery 没有问题。
- 修改为最新版本，重现bug
```
    "vuepress": "1.4.1",
    "vuepress-theme-reco": "1.4.5",
```
当前url:
tags/随笔/
预期url:
tag/随笔/

**Comment by FinnXing** [comment]
bug原因是 components/PageInfo.vue中goTags方法内的链接path: /tags/${tag}/写错了，改为path: /tag/${tag}/即可

**Comment by fengfengyuyu** [comment]
> bug原因是 components/PageInfo.vue中goTags方法内的链接path: /tags/${tag}/写错了，改为path: /tag/${tag}/即可，
> 希望大佬尽快修复

遇到同样的问题。照这个改了，OK了。

**Comment by YLDJack** [comment]
> bug原因是 components/PageInfo.vue中goTags方法内的链接path: /tags/${tag}/写错了，改为path: /tag/${tag}/即可，
> 希望大佬尽快修复

根据这个issue修改，成功解决该bug。感谢大佬！

**Comment by chenweigao** [comment]
> goTags

请问这个需要怎么改呢？直接用的下载主题，源代码貌似看不见呢

**Comment by FinnXing** [comment]
> > goTags
> 
> 请问这个需要怎么改呢？直接用的下载主题，源代码貌似看不见呢
源码在node_modules/vuepress-theme-reco/里面

**Comment by chenweigao** [comment]
> > > goTags
> > 
> > 
> > 请问这个需要怎么改呢？直接用的下载主题，源代码貌似看不见呢
> 
> 源码在node_modules/vuepress-theme-reco/里面

刚刚看GitHub上的项目源代码，发现这个bug在源码中已经修复了，但是没法更新到自己的项目中，这样即使是在本地解决了这个问题，但是上传到服务器上，自动下载的vuepress-theme-reco中还是会存在该bug的，有没有可能从源码更新一个新的版本，比如说1.4.6？谢谢

**Comment by FinnXing** [comment]
> > > > goTags
> > > 
> > > 
> > > 请问这个需要怎么改呢？直接用的下载主题，源代码貌似看不见呢
> > 
> > 
> > 源码在node_modules/vuepress-theme-reco/里面
> 
> 刚刚看GitHub上的项目源代码，发现这个bug在源码中已经修复了，但是没法更新到自己的项目中，这样即使是在本地解决了这个问题，但是上传到服务器上，自动下载的vuepress-theme-reco中还是会存在该bug的，有没有可能从源码更新一个新的版本，比如说1.4.6？谢谢

可以修改你项目的package.json里vuepress-theme-reco的版本号，然后重新npm install一下即可，更新后的package.json代码提交服务器后可以自动下载指定版本vuepress-theme-reco

**Comment by chenweigao** [comment]
> > > > > goTags
> > > > 
> > > > 
> > > > 请问这个需要怎么改呢？直接用的下载主题，源代码貌似看不见呢
> > > 
> > > 
> > > 源码在node_modules/vuepress-theme-reco/里面
> > 
> > 
> > 刚刚看GitHub上的项目源代码，发现这个bug在源码中已经修复了，但是没法更新到自己的项目中，这样即使是在本地解决了这个问题，但是上传到服务器上，自动下载的vuepress-theme-reco中还是会存在该bug的，有没有可能从源码更新一个新的版本，比如说1.4.6？谢谢
> 
> 可以修改你项目的package.json里vuepress-theme-reco的版本号，然后重新npm install一下即可，更新后的package.json代码提交服务器后可以自动下载指定版本vuepress-theme-reco

目前最新版本为1.4.5，该版本中存在这个Tag的 bug，但是以前的版本可能会存在其他bug，而我看源码中已经修复了这个bug，但是没有发布新的vuepress-theme-reco版本，所以指定最新版本还是会出现问题。

**Comment by FinnXing** [comment]
> > > > > > goTags
> > > > > 
> > > > > 
> > > > > 请问这个需要怎么改呢？直接用的下载主题，源代码貌似看不见呢
> > > > 
> > > > 
> > > > 源码在node_modules/vuepress-theme-reco/里面
> > > 
> > > 
> > > 刚刚看GitHub上的项目源代码，发现这个bug在源码中已经修复了，但是没法更新到自己的项目中，这样即使是在本地解决了这个问题，但是上传到服务器上，自动下载的vuepress-theme-reco中还是会存在该bug的，有没有可能从源码更新一个新的版本，比如说1.4.6？谢谢
> > 
> > 
> > 可以修改你项目的package.json里vuepress-theme-reco的版本号，然后重新npm install一下即可，更新后的package.json代码提交服务器后可以自动下载指定版本vuepress-theme-reco
> 
> 目前最新版本为1.4.5，该版本中存在这个Tag的 bug，但是以前的版本可能会存在其他bug，而我看源码中已经修复了这个bug，但是没有发布新的vuepress-theme-reco版本，所以指定最新版本还是会出现问题。

目前最新版本是1.4.5，npm包也已经更新了，我更新了1.4.5版本后Tag的 bug已经修复

**Comment by csdoker** [comment]
> > > > > > > goTags
> > > > > > 
> > > > > > 
> > > > > > 请问这个需要怎么改呢？直接用的下载主题，源代码貌似看不见呢
> > > > > 
> > > > > 
> > > > > 源码在node_modules/vuepress-theme-reco/里面
> > > > 
> > > > 
> > > > 刚刚看GitHub上的项目源代码，发现这个bug在源码中已经修复了，但是没法更新到自己的项目中，这样即使是在本地解决了这个问题，但是上传到服务器上，自动下载的vuepress-theme-reco中还是会存在该bug的，有没有可能从源码更新一个新的版本，比如说1.4.6？谢谢
> > > 
> > > 
> > > 可以修改你项目的package.json里vuepress-theme-reco的版本号，然后重新npm install一下即可，更新后的package.json代码提交服务器后可以自动下载指定版本vuepress-theme-reco
> > 
> > 
> > 目前最新版本为1.4.5，该版本中存在这个Tag的 bug，但是以前的版本可能会存在其他bug，而我看源码中已经修复了这个bug，但是没有发布新的vuepress-theme-reco版本，所以指定最新版本还是会出现问题。
> 
> 目前最新版本是1.4.5，npm包也已经更新了，我更新了1.4.5版本后Tag的 bug已经修复

确定吗？为啥我的版本是1.4.5  还是有这个问题

**Comment by FinnXing** [comment]
> > > > > > > > goTags
> > > > > > > 
> > > > > > > 
> > > > > > > 请问这个需要怎么改呢？直接用的下载主题，源代码貌似看不见呢
> > > > > > 
> > > > > > 
> > > > > > 源码在node_modules/vuepress-theme-reco/里面
> > > > > 
> > > > > 
> > > > > 刚刚看GitHub上的项目源代码，发现这个bug在源码中已经修复了，但是没法更新到自己的项目中，这样即使是在本地解决了这个问题，但是上传到服务器上，自动下载的vuepress-theme-reco中还是会存在该bug的，有没有可能从源码更新一个新的版本，比如说1.4.6？谢谢
> > > > 
> > > > 
> > > > 可以修改你项目的package.json里vuepress-theme-reco的版本号，然后重新npm install一下即可，更新后的package.json代码提交服务器后可以自动下载指定版本vuepress-theme-reco
> > > 
> > > 
> > > 目前最新版本为1.4.5，该版本中存在这个Tag的 bug，但是以前的版本可能会存在其他bug，而我看源码中已经修复了这个bug，但是没有发布新的vuepress-theme-reco版本，所以指定最新版本还是会出现问题。
> > 
> > 
> > 目前最新版本是1.4.5，npm包也已经更新了，我更新了1.4.5版本后Tag的 bug已经修复
> 
> 确定吗？为啥我的版本是1.4.5 还是有这个问题

建议把node_modules删除以后重新npm install一下

**Comment by DaZiYuan** [comment]
还没有修复，1.4.5 26天前发布的，这个issue都还没提交

**Comment by FinnXing** [comment]
认真检查了一下代码，确实没修复，对不起大家。

**Comment by YLDJack** [comment]
我加了vuepress-theme-reco的讨论群，看到公告: @reco_luan

> 主题最近因为构建流程的大更新导致小bug不断，为了不影响大家使用，这几天一直在解决，最新版本为 1.4.5。
> 因为个人原因，我要消失一段时间，大概2至4个月，或许更长，期间主题不再更新，聊天也不会再回复。
> 希望大家能够积极帮助群内朋友解决问题，感谢大家支持🙏🙏🙏。
最近应该是没有修复的，大家需要耐心等待了。等@reco_luan回来，应该会看到我们的issue的。

**Comment by smallsunnyfox** [comment]
在这个[commit](https://github.com/vuepress-reco/vuepress-theme-reco/commit/97d8196225ba2b08ebdb2517479c749c13f3bf63)里有相关问题的修改，只是还没发布，可以先在node_modules改一下相关代码作为临时解决方案

**Comment by 122177638** [comment]
问题貌似还是存在,目前最新版本还是1.4.5
