### ISSUE TITLE
使用comments插件时，浏览数量的后台请求报跨域错误

### ISSUE THREAD

**Issue by fengchenzhihun1** [vuepress-reco/vuepress-theme-reco#181]
版本：vuepress-theme-reco: "1.4.5"
评论没有问题，浏览数量在请求时报跨域错误
![20200505114447](https://user-images.githubusercontent.com/10166554/81033448-4e818000-8ec6-11ea-8018-79028c96b9d3.png)

**Comment by csdoker** [comment]
在leancloud中，添加一个Counter的class就行了
