### ISSUE TITLE
文章翻页seo优化建议

### ISSUE THREAD

**Issue by DaZiYuan** [vuepress-reco/vuepress-theme-reco#182]
#### What problem does this feature solve?
当前翻页url地址不变化，感觉怪怪的也不利于seo

#### How should this be implemented in your opinion?
建议改成默认主题那种方式
https://example.vuepress-theme-blog.ulivz.com/
https://example.vuepress-theme-blog.ulivz.com/page/2/
https://example.vuepress-theme-blog.ulivz.com/page/3/
并且把翻页按钮改为链接，鼠标移上去能看见访问地址

#### Are you willing to work on this yourself?
看了下源码感觉自己改要花很多时间，我先提个建议

**Comment by ComicAuthor** [comment]
毕竟这里是个假分页，你说的这个其实可以自己搞一下。

**Comment by recoluan** [comment]
暂不支持。
