### ISSUE TITLE
vuepress-theme-reco 2.x左侧侧边栏不能折叠收缩

### ISSUE THREAD

**Issue by yaohui-li** [vuepress-reco/vuepress-theme-reco#186]
vuepress-theme-reco 2.x左侧侧边栏不能折叠收缩

#### Other relevant information

- Your OS:  window
- Node.js version:  v16.18.0
- VuePress version: 2.0.0-beta.61
- VuePress-theme-reco version: 2.0.0-beta.60
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? npm

**Comment by recoluan** [comment]
好的，安排

**Comment by yaohui-li** [comment]
大概什么版本支持此功能？

**Comment by recoluan** [comment]
最新版本已经支持

**Comment by yaohui-li** [comment]
跟vuepress原生配置一样吗？

**Comment by yaohui-li** [comment]
但是好像不能保持折叠的状态
