### ISSUE TITLE
Automatically set Categories and Tags When enabled, a new navigation bar menu will be automatically generated

### ISSUE THREAD

**Issue by familior** [vuepress-reco/vuepress-theme-reco#187]
## Bug report
After automatically generating Categories and Tags, the name is no longer the name set by the user
![截图_20230507155734](https://user-images.githubusercontent.com/84607943/236665244-ba4dd197-8e69-416a-a32b-5beda2a9bad1.png)

#### Other relevant information

- Your OS: 
- Node.js version: 18
- VuePress version: default
- VuePress-theme-reco version: 2.0
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? npm

**Comment by recoluan** [comment]
You can remove `autoAddCategoryToNavbar`.
