### ISSUE TITLE
日期显示错误

### ISSUE THREAD

**Issue by Louis-XIV** [vuepress-reco/vuepress-theme-reco#187]
- [x] I confirm that this is an issue rather than a question.

## Bug report
文章的date写的是2020-05-17但页面上显示2020-05-01
#### Other relevant information

- Your OS: win10
- Node.js version: 10
- VuePress version: 1.5.0
- VuePress-theme-reco version: 1.4.5
- Which package manager did you use for the install(npm/cnpm/yarn)?
npm

**Comment by recoluan** [comment]
我测试了一下没问题的啊，你是不是修改后没有重启啊？

**Comment by Louis-XIV** [comment]
> 我测试了一下没问题的啊，你是不是修改后没有重启啊？

有重启，vuepress1.5.0 reco 1.4.5版本 确认有bug。 目前发现只有date在2020年4月之后才有bug。 刚才测的date写2020-05-21 实际显示2020-05-02

**Comment by Louis-XIV** [comment]
补充一下这个日期显示错误只影响版本升级后新增的文章，对升级前已存在的文章没有影响。

**Comment by recoluan** [comment]
我这里实在是无法复现你这个问题，建议你将全局或项目中使用的依赖删除掉重新安装试一试。
<img width="1354" alt="WX20200524-181033@2x" src="https://user-images.githubusercontent.com/18067907/82751444-e1d51380-9de9-11ea-858e-c60559434985.png">

**Comment by 834930269** [comment]
2020/6月显示的是NaN-NaN-NaN

**Comment by recoluan** [comment]
The bug cannot be displayed repeatedly.
