### ISSUE TITLE
Question about preview images

### ISSUE THREAD

**Issue by jrappen** [vuepress-reco/vuepress-theme-reco#188]
How did you make the images in the [preview section](https://github.com/vuepress-reco/vuepress-theme-reco#preview) of the README?

**Comment by recoluan** [comment]
This is just a markdown syntax `![img name](img src) `.  I hope my answer can help you.

**Comment by jrappen** [comment]
I meant which software did you use to make those images.

**Comment by recoluan** [comment]
I used a photoshop template and inserted the image into the corresponding layer.

The PS template was given to me by a friend. If you like, I can send it to you and tell me your email.

**Comment by jrappen** [comment]
<mailto:jrappen@outlook.com>, thanks appreciate it.

**Comment by wangdabaoqq** [comment]
@recoluan wangdabao221@163.com
thanks
