### ISSUE TITLE
无法热更新(Hot update does not take effect)

### ISSUE THREAD

**Issue by ZooMze** [vuepress-reco/vuepress-theme-reco#189]
写了半天才意识到没有热更新, 我以为代码哪儿影响到了
重新用theme-cli初始化了一个, 依然没有热更新
强制刷新也不会更新, 只有重新跑dev命令才能看到更新
node和vuepress版本
cli.js/1.4.1 win32-x64 node-v10.16.0

**Comment by recoluan** [comment]
修改配置和增加 md 文件是需要重新启动项目的，书写 markdown 是会热更新的。

**Comment by ZooMze** [comment]
> 修改配置和增加 md 文件是需要重新启动项目的，书写 markdown 是会热更新的。

问题就是修改md没有热更新, 我是用的yarn安装的

**Comment by yech** [comment]
我遇到了同样的问题，修改md文件没有热更新。

**Comment by zhaodianlong** [comment]
同问

**Comment by wo2095296** [comment]
vuepress 1.5.0 修改markdown没有热更新

**Comment by 122177638** [comment]
> vuepress 1.5.0 修改markdown没有热更新

貌似 还是没有热更新

**Comment by sto666orz** [comment]
一样，没有热更新，修改啥都需要重启命令

**Comment by JarmanQian** [comment]
解决方案参考：https://github.com/vuejs/vuepress/issues/2392

> package.json中devDependencies，增加watchpack的版本

```
"devDependencies": {
    "watchpack": "1.6.1"
  }
```

> 然后再运行 npm install 就行了
