### ISSUE TITLE
左侧侧边栏目录排序有待完善

### ISSUE THREAD

**Issue by GaviXi** [vuepress-reco/vuepress-theme-reco#190]
<img width="176" alt="image" src="https://github.com/vuepress-reco/vuepress-theme-reco/assets/87537269/67fbe5f6-35fe-48f2-9ea3-575e5d8f18e0">
第十章和第十一章理应是在第九章后面的

**Comment by recoluan** [comment]
是自动生成侧边栏导致的吗

**Comment by GaviXi** [comment]
是的


toper
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vuepress-reco/vuepress-theme-reco"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月17日(星期三) 晚上6:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vuepress-reco/vuepress-theme-reco] 左侧侧边栏目录排序有待完善 (Issue #190)





 
是自动生成侧边栏导致的吗
