### ISSUE TITLE
首页标签tag跳转失败，如何修改？

### ISSUE THREAD

**Issue by q379257013** [vuepress-reco/vuepress-theme-reco#191]
- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version: 
- VuePress-theme-reco version: 
- Which package manager did you use for the install(npm/cnpm/yarn)?

**Comment by recoluan** [comment]
This has been fixed in `1.4.6`.
