### ISSUE TITLE
图片无法放大查看

### ISSUE THREAD

**Issue by 122177638** [vuepress-reco/vuepress-theme-reco#192]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
官方插件@vuepress/plugin-medium-zoom失效，是否在封装上发生了冲突，请留意，这是一个比较大的问题

#### Other relevant information

- Node.js version: v10.16.0
- VuePress version: 1.5
- VuePress-theme-reco version: 1.4.5
- Which package manager did you use for the install(npm/cnpm/yarn)?  
cnpm

**Comment by recoluan** [comment]
主题的官网用的是最新的主题，目前图片方法功能有效的。

**Comment by 122177638** [comment]
> 主题的官网用的是最新的主题，目前图片方法功能有效的。

经测试，如果在public新建一个img文件夹，此目录下文件是无法使用zoom功能，如直接放入public确实是没有问题
