### ISSUE TITLE
主题：黑夜模式下首页标题颜色比内容颜色还要深

### ISSUE THREAD

**Issue by nshusr** [vuepress-reco/vuepress-theme-reco#193]
如图：
![image](https://user-images.githubusercontent.com/45023042/83481453-66055600-a4d0-11ea-9406-d29f9ec87678.png)

应变暗内容文字颜色，让标题更亮些

**Comment by recoluan** [comment]
这个颜色是你自定义的主题色，可以通过修改 `$accentColor` 来调整。
