### ISSUE TITLE
默认配置，build报错

### ISSUE THREAD

**Issue by xionghaizhi** [vuepress-reco/vuepress-theme-reco#194]
默认配置，直接build  报错，run dev可以正常使用

![image](https://user-images.githubusercontent.com/30396478/83495809-c73a2300-a4ea-11ea-882e-7612060d356b.png)

- Your OS: windows
- Node.js version: 12.17
- VuePress version: 
- VuePress-theme-reco version: 1.0
- Which package manager did you use for the install(npm/cnpm/yarn)? npm 和cnpm 都试过

**Comment by 122177638** [comment]
> 默认配置，直接build 报错，run dev可以正常使用
> 
> ![image](https://user-images.githubusercontent.com/30396478/83495809-c73a2300-a4ea-11ea-882e-7612060d356b.png)
> 
> * Your OS: windows
> * Node.js version: 12.17
> * VuePress version:
> * VuePress-theme-reco version: 1.0
> * Which package manager did you use for the install(npm/cnpm/yarn)? npm 和cnpm 都试过

TypeError: Cannot read property 'pagation' of undefined
是这个错误吗，没加默认值的原因

**Comment by xionghaizhi** [comment]
> > 默认配置，直接build 报错，run dev可以正常使用
> > ![image](https://user-images.githubusercontent.com/30396478/83495809-c73a2300-a4ea-11ea-882e-7612060d356b.png)
> > 
> > * Your OS: windows
> > * Node.js version: 12.17
> > * VuePress version:
> > * VuePress-theme-reco version: 1.0
> > * Which package manager did you use for the install(npm/cnpm/yarn)? npm 和cnpm 都试过
> 
> TypeError: Cannot read property 'pagation' of undefined
> 是这个错误吗，没加默认值的原因

好的 谢谢，我更新了下所有版本后也可以使用了

**Comment by XuMinhui** [comment]
如何解决的，能分享一下吗？

**Comment by 122177638** [comment]
> 如何解决的，能分享一下吗？

升级Vuepress-theme-reco最新版本，1.4.6. 
已经修复了tags路径错误，以及这个打包错误

**Comment by xionghaizhi** [comment]
yarn upgrade-interactive --latest


> 如何解决的，能分享一下吗？

yarn upgrade-interactive --latest

**Comment by xionghaizhi** [comment]
最终升级了下版本解决了此问题
yarn upgrade-interactive --latest

**Comment by yuqing521** [comment]
升级Vuepress-theme-reco最新版本，1.4.6.
在package.json中修改devDependencies
改为"vuepress-theme-reco": "1.4.6"
yarn install 即可
