### ISSUE TITLE
左侧边栏折叠后，点击一个展开了所有的

### ISSUE THREAD

**Issue by yhx1001** [vuepress-reco/vuepress-theme-reco#194]
左侧边栏折叠后，点击一个展开了所有的

**Comment by recoluan** [comment]
好的，周末看一下

**Comment by recoluan** [comment]
你好，我这没有复现这个 bug 呢，有什么办法稳定复现吗？

**Comment by codedog01** [comment]
官网就有这个问题呢，[](https://vuepress-theme-reco.recoluan.com/docs/theme/markdown-task.html)

左侧边栏 【主题配置】系列默认展开，点击折叠后，再点击其他系列的任意子项时，【主题配置】就会恢复为默认展开状态。

**Comment by codedog01** [comment]
[复现地址](https://vuepress-theme-reco.recoluan.com/docs/theme/markdown-task.html)

**Comment by iHTCboy** [comment]
想要的效果是，默认折叠，然后点击一个目录就展开，点击另一个目录时，原来已经展开的目录不折叠，目前的代码好像不能实现~ 0.0
