### ISSUE TITLE
无法分页

### ISSUE THREAD

**Issue by zeroover** [vuepress-reco/vuepress-theme-reco#195]
Error in render: "TypeError: Cannot read property 'pagation' of undefined"

**Comment by zerocola777** [comment]
安装最新版本之后无法分页

**Comment by XuMinhui** [comment]
更改一行代码即可
node_modules\@vuepress-reco\vuepress-plugin-pagation\bin\locales.js
中第37行修改为
const { $lang, $recoLocales: { pagation } = {} } = ctx

**Comment by zeroover** [comment]
改源码不好，可以降低vuepress-plugin-pagation这个包的版本

**Comment by recoluan** [comment]
问题将在 `1.4.7` 版本修复。

**Comment by zeroover** [comment]
> 问题将在 `1.4.7` 版本修复。

事情忙完了？要回归了？

**Comment by recoluan** [comment]
> > 问题将在 `1.4.7` 版本修复。
> 
> 事情忙完了？要回归了？

哈哈，要回归了，但是时间没原来充裕了，只能挤出时间来做。
