### ISSUE TITLE
build后文件404，路径是默认路径

### ISSUE THREAD

**Issue by oranges-have-to-be-sweet** [vuepress-reco/vuepress-theme-reco#198]
build后文件404，路径是默认路径
![image](https://user-images.githubusercontent.com/44565996/84036112-5bb2f280-a9cf-11ea-9576-779c10dd51bf.png)

**Comment by recoluan** [comment]
你的项目不在域名的根目录，`base` 应该没有设置或设置不正确，具体看一下 GitHub 的 pages 文档吧。
