### ISSUE TITLE
Giscus Comment Component theme bug with personal solution

### ISSUE THREAD

**Issue by yxzlwz** [vuepress-reco/vuepress-theme-reco#198]
version: [2.0.0-beta.63](https://www.npmjs.com/package/vuepress-theme-reco/v/2.0.0-beta.63)

I'm using Giscus as my comment component. It works well with dev server, but when I build it, the theme of the component fallback to _High Contrast_ one, as _Tritanopia_ was expected.

I checked the css file output into `dist/assets`, only to find `.bulletin-wrapper{border-w` in both `.vuepress\dist\assets\giscus-theme.css` and `.vuepress\dist\assets\giscus-theme-dark.css`.

![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/75941562/41b85160-159c-4c7b-a8cc-4ec7f536f3f4)

I thought there should be some css content, so I copied content from `node_modules\@vuepress-reco\vuepress-plugin-comments\lib\client\styles\giscus-theme.css` to those files and restarted the browser, finding the problem was solved. Then I checked the source code, in my opnion, the below program didn't write correct content into those files.

https://github.com/vuepress-reco/vuepress-theme-reco/blob/main/packages/%40vuepress-reco/plugin-comments/src/node/commentsPlugin.ts#L11

As I'm not a skilled frontend developer, I opened this issue. Hope you can fix it ASAP!

---

Picture: a same page shows in different way in dev and prod version.

![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/75941562/636db8ce-762c-42bd-b53f-6b1926045667)

![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/75941562/329d13f0-e51a-4390-915e-58b572a229cc)

**Comment by recoluan** [comment]
It was resolved in this [commit](https://github.com/vuepress-reco/vuepress-theme-reco/commit/24b84a6085aac663d262bfbfa480071cc586423f).

**Comment by yxzlwz** [comment]
Could you please tell me when a new version will be published on npm?

**Comment by recoluan** [comment]
> Could you please tell me when a new version will be published on npm?

I will release it on Sunday.

**Comment by yxzlwz** [comment]
I tried to build it locally and the problem fixed. Thank you for answering! I'm looking forward to try the new version tomorrow!

**Comment by yxzlwz** [comment]
By the way there's another issue: Though my site theme is dark, Giscus always show light theme at the first time I open a certain page. If I refresh the page, Giscus theme will show rightly(match the site theme). But after I open another page and then go back here, Giscus shows light theme again. If I stand in page and change the site theme, Giscus theme can change well.

I tried the latest commit, the problem still occurs.

**Comment by yxzlwz** [comment]
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/75941562/ad334403-cee2-4f05-92f3-9defce874699)

These code can fix it, which is really not elegant...

**Comment by yxzlwz** [comment]
I found that the problem was occured because class `nprogress-busy` will be added to html class when changing page, so that compare string can't work correctly. I opened a PR to fix this problem.

Please merge it before your publishing tomorrow, as I'm really looking forward to deploy my blog! Thx.

**Comment by yxzlwz** [comment]
Will I be able to see new published version tonight?

**Comment by yxzlwz** [comment]
Still no new version now...

**Comment by yxzlwz** [comment]
Fine, I'm going to build it myself
