### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by 790480681** [vuepress-reco/vuepress-theme-reco#199]
在config.ts中，我配置了base为'vuepress-blog/',现在点击分页，页面显示404，地址有点奇怪，地址为：http://localhost:8082/vuepress-blog/vuepress-blog%2F?page=2

**Comment by 790480681** [comment]
以下是版本号
    "vuepress": "2.0.0-beta.61",
    "vuepress-theme-reco": "2.0.0-beta.62"

**Comment by yxzlwz** [comment]
试试把 `home: '/vuepress-blog/'` 换成 `home: '/vuepress-blog'`？

（没用过base，只是猜测）
