### ISSUE TITLE
[Bug] Can't resolve 'vue-class-component' when building

### ISSUE THREAD

**Issue by VerifiedGruber** [vuepress-reco/vuepress-theme-reco#201]
#### What is actually happening?

Although `yarn run dev` works just fine, `yarn run build` results in:

```sh
 (undefined) ./node_modules/vue-property-decorator/lib/vue-property-decorator.js
 Module not found: Error: Can't resolve 'vue-class-component' in '/builds/navarra-dev/shoggoth/node_modules/vue-property-decorator/lib'
 resolve 'vue-class-component' in '/builds/navarra-dev/shoggoth/node_modules/vue-property-decorator/lib'
   Parsed request is a module
   using description file: /builds/navarra-dev/shoggoth/node_modules/vue-property-decorator/package.json (relative path: ./lib)
     Field 'browser' doesn't contain a valid alias configuration
     resolve as module
       looking for modules in /builds/navarra-dev/shoggoth/node_modules/@vuepress/core/lib/node/webpack/node_modules
         using description file: /builds/navarra-dev/shoggoth/node_modules/@vuepress/core/package.json (relative path: ./lib/node/webpack/node_modules)
           Field 'browser' doesn't contain a valid alias configuration
```

#### Other relevant information/How to fix the issue

Temporary solution and explanation for the bug proposed [here](https://github.com/kaorun343/vue-property-decorator/issues/324):

- Run or equivalent npm command `yarn add vue-class-component -D` in the repository default `package.json` and it'll be fixed, both for your local theme and the repository of the theme itself.

-----------------

#### Debugging information: 

- Your OS: [Docker Image 12.8.0 Kernel arm64/v8](https://hub.docker.com/layers/node/library/node/12.18.0/images/sha256-7ad08ad4aef88011145a250e60e798822fdfdd786903dccf4521c077ed2dd5c0?context=explore)
- Node.js version:  12.8.0
- VuePress version: 1.4.1
- VuePress-theme-reco version: 1.4.5 
- Which package manager did you use for the install(npm/cnpm/yarn): Yarn

**Comment by recoluan** [comment]
Thank you for your advice. But do you know the specific reason for this problem?

**Comment by franklinqin0** [comment]
> Thank you for your advice. But do you know the specific reason for this problem?

In @VerifiedGruber's [shared link](https://github.com/kaorun343/vue-property-decorator/issues/324), this problem happens because 'vue-class-component' is not explicitly imported in 'vue-property-decorator'. Thus, we have to add `"vue-class-component": "^7.2.3",` in `package.json` or `yarn add vue-class-component` to import it at top level.

**Comment by VerifiedGruber** [comment]
> Thank you for your advice. But do you know the specific reason for this problem?

Thank you @franklinqin0 for explaining the solution thoroughly. I'd also like to point out this happened because it seems there was a v8.5.0 release of `vue-property-decorator` that is not listed on its Github page where [it seems the only change made was moving 'vue-class-component' to `peerDependencies`](https://github.com/kaorun343/vue-property-decorator/blob/master/CHANGELOG.md). What can be done by theme-creators that use this dependency is adding it manually as a dependency to their respective `package.json`, although I'm not quite sure if that's the correct permanent fix for this situation.

**Comment by VerifiedGruber** [comment]
[The bug has been addressed by the developer on the component newer versions, v8.5.1 and v9.0.0.](https://github.com/kaorun343/vue-property-decorator/issues/324#issuecomment-646295325) so I think it is safe to assume that this should not happen to anyone else as long they keep their packages up-to-date.
