### ISSUE TITLE
To decide whether prefetch js files manually

### ISSUE THREAD

**Issue by yxzlwz** [vuepress-reco/vuepress-theme-reco#205]
It is too heavy to prefetch all js files when open the website, which causes meaningless network and storage waste, and makes it more difficult to update content.

So I suggest add a setting to decide whether add prefetch to the html file when build. It seem easy to realise - just delete `<!--vuepress-ssr-resources-->` from index.build.html

**Comment by wstee** [comment]
You can set ``shouldPrefetch: false`` in config file.

**Comment by yxzlwz** [comment]
Thx
