### ISSUE TITLE
能否设置 heroImage 为可选项（即不要默认的，也不想自定义）

### ISSUE THREAD

**Issue by sammyne** [vuepress-reco/vuepress-theme-reco#206]
#### What problem does this feature solve?
当前实现下 heroImage 要么用默认的，要么显式设置，但是两种方式的结果都会引入 heroImage。个人觉得如果能够让 heroImage 可关掉就更好了，即不要默认的，也不想自定义。

#### How should this be implemented in your opinion?
通过添加一个开关，类似 `home: true` 标识当前是否是主页，把整个 [heroImage 相关的 div](https://github.com/vuepress-reco/vuepress-theme-reco/blob/develop/packages/vuepress-theme-reco/components/HomeBlog.vue#L3-L26) 屏蔽掉

#### Are you willing to work on this yourself?
很久没用 vue.js 了，不是很熟悉，所以暂时没有提 PR 的计划= = 要是哪位大佬能够帮忙实现一下就更好了~ 

这个主题很好看~

**Comment by recoluan** [comment]
在首页的 `front-matter` 中不添加 `heroImage` 这个配置，就不会出现 heroImage 了，你先这样试一下呢。

**Comment by sammyne** [comment]
> 在首页的 `front-matter` 中不添加 `heroImage` 这个配置，就不会出现 heroImage 了，你先这样试一下呢。

试了~ 发现还是出现了默认的，所以就找大佬求救= = @recoluan

**Comment by recoluan** [comment]
> > 在首页的 `front-matter` 中不添加 `heroImage` 这个配置，就不会出现 heroImage 了，你先这样试一下呢。
> 
> 试了~ 发现还是出现了默认的，所以就找大佬求救= = @recoluan
好的，我抽时间检查一下代码，请耐心等待一下。

**Comment by recoluan** [comment]
我看了一下最新版本的代码中，如果不配置 heroImage 是不会显示的，所以你使用的应该是不是最新版本吧。

我看到你的 [博客](https://sammyne.github.io/) 中已经没有这个问题了对吧，那我就关闭这个 issue 了。

**Comment by sammyne** [comment]
我用的主题版本时 v1.4.7，这个具体是在哪个版本修复了的 @recoluan

**Comment by sammyne** [comment]
我升级到 v1.5.3，发现依然还是无法去掉 heroImage

**Comment by recoluan** [comment]
这不正常吗，哪有 heroImage 啊？
![image](https://user-images.githubusercontent.com/18067907/87038865-e9793c00-c220-11ea-80dd-1b91d69df85f.png)

**Comment by sammyne** [comment]
> 这不正常吗，哪有 heroImage 啊？
> ![image](https://user-images.githubusercontent.com/18067907/87038865-e9793c00-c220-11ea-80dd-1b91d69df85f.png)

我理解以下截图部分就是 heroImage ~
![image](https://user-images.githubusercontent.com/16666661/87105206-e1ef7c80-c28c-11ea-8f64-f4d4453c1665.png)

**Comment by recoluan** [comment]
@sammyne 后面那张图是 banner 图，banner 图暂时不支持去掉。
