### ISSUE TITLE
首页的底部评论统计如何展示啊

### ISSUE THREAD

**Issue by kingcwt** [vuepress-reco/vuepress-theme-reco#207]
使用 waline 各个页面都显示了 但是首页的这么配置 如何在首页底部展示浏览统计次数。麻烦告诉一下。

**Comment by kingcwt** [comment]
<img width="628" alt="image" src="https://github.com/vuepress-reco/vuepress-theme-reco/assets/29888469/4978f545-aa5c-4fb6-8b2f-890d10cc5c97">
<img width="733" alt="image" src="https://github.com/vuepress-reco/vuepress-theme-reco/assets/29888469/d34a4083-0b00-4368-b601-01f0e95883e5">


不支持waline ？

**Comment by recoluan** [comment]
@wstee

**Comment by kingcwt** [comment]
已经通过 CustomFooter 改了 不等了
