### ISSUE TITLE
无法覆写分页参数 perPage

### ISSUE THREAD

**Issue by sammyne** [vuepress-reco/vuepress-theme-reco#207]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?
参照官方文档的 [对象式覆写插件](https://vuepress-theme-reco.recoluan.com/views/plugins/#%E6%8F%92%E4%BB%B6%E6%80%8E%E4%B9%88%E7%94%A8) 教程无法改变默认的分页参数 `perPage`。

样例参见 [这里](https://github.com/sammyne/sammyne.github.io/blob/12ec8c33310eed86790f12e93a6ac5abee1de061/.vuepress/config.js#L13)，设置了 `perPage` 为 8，但是前端页面依然按默认的 10 来分页，相应的 UI 参见 https://sammyne.github.io/

#### Other relevant information

- Your OS: macOS
- Node.js version: v12.18.1
- VuePress version: v1.5.2
- VuePress-theme-reco version: v1.4.7
- Which package manager did you use for the install(npm/cnpm/yarn)? yarn

**Comment by recoluan** [comment]
已经收到你的问题，结果会在这里向你反馈。
