### ISSUE TITLE
Front Matter 配置是否发布 publish 不符合预期要求。

### ISSUE THREAD

**Issue by demigodliu** [vuepress-reco/vuepress-theme-reco#213]
Front Matter 配置 publish: false，文章列表不会显示出未发布的文章，但是左侧 aside 栏会显示。

文章配置图：https://i.loli.net/2020/07/08/ZdELxj2Fk8bfw6V.png

文章列表图：https://i.loli.net/2020/07/08/n3R7mU2DbC8JAgl.png 符合预期要求。

文章详情图：https://i.loli.net/2020/07/08/3xEzgnOaTNsUmjW.png 不符合预期要求。

**Comment by recoluan** [comment]
目前 publish 只过滤博客，没有过滤文档，其实 reco 主题建议将文档和博客分开来看待：

博文更具有独立性，一般通过分类、标签来将其组合成一组数据；而文档，我们一般使用自定义侧边栏来将其组合到一起，所以这些文章一般会一起出现或一起不出现，没必要过滤侧边栏里的某篇文章。

reco 主题处理博客数据会过滤没有分类的文章，所以如果不想出现在网站中，不要添加分类，也不要放在侧边栏中即可。

后期会将以上约定加入到文档中，以方便大家更好地书写。

希望以上回复可以帮助到你。
