### ISSUE TITLE
安装速度太慢了，卡住动不了

### ISSUE THREAD

**Issue by xushuhui** [vuepress-reco/vuepress-theme-reco#214]
我在安装选择午后南杂就一直现在加载，选择blog可以正常安装，虽然也很慢。但是午后南杂就让我一直等，半个小时了。
![image](https://user-images.githubusercontent.com/13704743/87220088-a5f30f00-c393-11ea-8a5e-3639148b2241.png)

npm 6.14.5 使用了淘宝镜像
node 14.4

感谢开发出这个产品，很清新

**Comment by recoluan** [comment]
`午后南杂` 的文件太多，github 本身下载就很慢，如果不是一定要看午后南杂的博客配置，没有必要下载 `午后南杂`的。
