### ISSUE TITLE
时间轴和文章统计

### ISSUE THREAD

**Issue by Licodeao** [vuepress-reco/vuepress-theme-reco#214]
佬 时间轴和文章总数统计啥时候安排呢

**Comment by recoluan** [comment]
时间轴，在最新版本里已经有了，/timeline，文章总数的话，感觉并不是一个很有必要的数据

**Comment by Licodeao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Licodeao** [comment]
> 时间轴，在最新版本里已经有了，/timeline，文章总数的话，感觉并不是一个很有必要的数据

v1版本都有，v2咋就要弃掉了呢，可以搞个配置项交给使用者来决定嘛
