### ISSUE TITLE
Giscus getting discussions mistakely

### ISSUE THREAD

**Issue by yxzlwz** [vuepress-reco/vuepress-theme-reco#216]
First, I opened the index page, and get these requests (Giscus request a discussion for index)

![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/75941562/d2408626-52f7-4902-b0d8-e5bce0e833df)

After that I click and view an article, it still requested discussion with keyword index:

![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/75941562/a3988aa1-a84f-4075-8ba3-882b5a176f7c)

Then I go back to index page by click the upper left corner, Giscus requested discussion for the article page:

![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/75941562/ea65745f-f76f-4194-b0a5-8812d4867785)

Please help to fix it! It really matters as now it is showing wrong discussion for articles - in fact, all articles are showing the same!

**Comment by recoluan** [comment]
@wstee
