### ISSUE TITLE
能不能实现一个自动生成series啊

### ISSUE THREAD

**Issue by moozae** [vuepress-reco/vuepress-theme-reco#22]
**Is your feature request related to a problem? Please describe.**
qwq

**Describe the solution you'd like**
能否根据文件树自动生成左侧边栏啊，这样对于页面很多的文档站会很有用

**Describe alternatives you've considered**
因为vuepress不再允许插件修改配置，目前我的想法是在文档生成之前先进行series生成然后写入config.ts，然后再进行构建，很明显这样的方法不够优雅

**Additional context**
嘤嘤嘤

**Comment by recoluan** [comment]
有这样的打算：https://github.com/vuepress-reco/vuepress-theme-reco/issues/17#issue-1133986549
