### ISSUE TITLE
Vssue评论插件加载报错

### ISSUE THREAD

**Issue by zengdw** [vuepress-reco/vuepress-theme-reco#220]
- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Your OS: 
- yarn.js version:  1.22.4
- VuePress version:  1.3.0
- VuePress-theme-reco version:  1.5.4
- Which package manager did you use for the install(npm/cnpm/yarn)? yarn
![sssssss](https://user-images.githubusercontent.com/37267612/87922151-26112700-caae-11ea-9382-01b798193600.png)

**Comment by zengdw** [comment]
![sssssss](https://user-images.githubusercontent.com/37267612/87922273-55279880-caae-11ea-8bcb-16015fab96d8.png)

**Comment by recoluan** [comment]
把你的配置贴一下吧
