### ISSUE TITLE
发现一个关于Sidebar的控制台错误，但并不影响使用

### ISSUE THREAD

**Issue by yokefellow** [vuepress-reco/vuepress-theme-reco#221]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?

当博客的类型为`blog`且手动设置siderbar（`.vuepress/config/sidebar/index.js`）的时候，控制台出现了如下错误，
![image](https://user-images.githubusercontent.com/43605758/87938854-bf9a0200-cac9-11ea-9d95-f66baca330df.png)

#### 错误触发条件，以[橘子大佬的博客](https://blog.smallsunnyfox.com/)为例

1.第一次进入页面不会报错
![image](https://user-images.githubusercontent.com/43605758/87939479-bcebdc80-caca-11ea-9f75-5116b8f44838.png)

2.当用户点击首页文章且这篇文章手动设置了siderbar
![image](https://user-images.githubusercontent.com/43605758/87939513-cd03bc00-caca-11ea-9df2-b1bbb2d7e13b.png)

3.用户回到主页，再点击这篇文章，控制台出现错误
![image](https://user-images.githubusercontent.com/43605758/87939717-0c320d00-cacb-11ea-94a9-0dbdf045fd67.png)

#### Other relevant information

- Your OS: Windows
- Node.js version: v10.15.3
- VuePress version: 1.4.0
- VuePress-theme-reco version: 1.5.3
- Which package manager did you use for the install(npm/cnpm/yarn)?yarn

**Comment by yokefellow** [comment]
应该是vuepress本身的问题

**Comment by recoluan** [comment]
> 应该是vuepress本身的问题

已经验证了吗？

**Comment by yokefellow** [comment]
> > 应该是vuepress本身的问题
> 
> 已经验证了吗？
vue-router在3.1之后把$router.push()方法改为了Promise。如果没有回调函数，错误信息就会交给全局的路由错误处理，就会报上述的错误。[#2881](https://github.com/vuejs/vue-router/issues/2881#issuecomment-520554378)
我在enhanceApp.js添加了如下代码隐藏了vue-router的报错
```js
export default ({Vue,options,router,siteData,isServer}) => {
  const originalPush = router.push
  router.push = function push(location, onResolve, onReject) {
    if (onResolve || onReject) return originalPush.call(this, location, onResolve, onReject)
    return originalPush.call(this, location).catch(err => {err})
  }
}
```
