### ISSUE TITLE
How to add favicon

### ISSUE THREAD

**Issue by shangliuyan** [vuepress-reco/vuepress-theme-reco#222]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
my version is "2.0.0-beta.63" .
I put **/favicon.ico**  in **.vuepress/public** directory but it not work

**Comment by wstee** [comment]
You should set ``head`` in config file.[https://v2.vuepress.vuejs.org/zh/reference/config.html#head](https://v2.vuepress.vuejs.org/zh/reference/config.html#head)

**Comment by shangliuyan** [comment]
> You should set `head` in config file.https://v2.vuepress.vuejs.org/zh/reference/config.html#head

thanks! it works!
