### ISSUE TITLE
最新版打包部署白屏报错

### ISSUE THREAD

**Issue by Rooon-K** [vuepress-reco/vuepress-theme-reco#224]
- [ ] I confirm that this is an issue rather than a question.

## Bug report
升级到最新版build部署后白屏，F12控制台报错
Cannot destructure property 'currentRoute' of 'tl(...)' as it is undefined.

#### Other relevant information

- Your OS: 
- Node.js version: 16.20.1
- VuePress version: 2.0.0-beta66
- VuePress-theme-reco version: 2.0.0-beta.67
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?yarn

**Comment by recoluan** [comment]
vuepress 升级到 rc.9，主题升级到 rc.8 再试试
