### ISSUE TITLE
关于官网提到的约定

### ISSUE THREAD

**Issue by amadeus711** [vuepress-reco/vuepress-theme-reco#226]
你好，官网提到了1.5.3会将样式分为博客和文档，对此进行了项目结构的变化，我也想体验新变化，但是当结构变化后，跑起来home等页面找不到了，方便提供一个样例吗？我想参考一下路径的配置，万分感谢！

**Comment by amadeus711** [comment]
已解决，当版本升到1.5.3以上，不用改项目目录，右面的侧边栏也能出来

**Comment by recoluan** [comment]
升级之后就可以体验。

关于官网提到的约定，目的有两点：

1. 解释一下 reco 主题是怎么处理数据的，以便于使用者更好地去处理博客和文档的差别，因为很多朋友主观上是不区分博客和文档的，往往将两者混在一起使用，而主题本身也并没有严格限制用户去区分文档和博客的 md 怎么去写，就会出现一些显示方面的小问题，所以更希望通过约定来处理这个问题；

2. 如果项目中即存在文档，又存在博客，主题希望用户能按照推荐的方式去处理文件目录，这样更加清晰（当然不参考也是完全没问题的）。
