### ISSUE TITLE
最新版build打包错误

### ISSUE THREAD

**Issue by kuikui2** [vuepress-reco/vuepress-theme-reco#227]
D:\目录仓库\api-docs>npm run build

> vuepress-theme-reco-demo@2.0.0 build
> vuepress build .
× Compiling with vite - failed in 1.28s
Error: [vite]: Rollup failed to resolve import "D:/mulucangku/api-docs/.vuepress/.temp/pages/index.html.vue" from "D:/目录仓库/api-docs/.vuepress/.temp/internal/pagesComponents.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

**Comment by panmili** [comment]
大哥，搞定没

**Comment by panzhangbao** [comment]
楼主有解决吗，我也遇到了同样的问题
![打包报错](https://github.com/vuepress-reco/vuepress-theme-reco/assets/18541722/3fa6ac99-d4c6-4852-84b2-0097303599cb)

**Comment by recoluan** [comment]
应该是路径中有中文的问题
