### ISSUE TITLE
希望增加分类下标签筛选功能

### ISSUE THREAD

**Issue by ty-peng** [vuepress-reco/vuepress-theme-reco#228]
#### What problem does this feature solve?
1. 希望增加分类下标签筛选功能
1. 希望文章能增加不显示在首页的属性（但是分页等其他页面可以展示）

#### How should this be implemented in your opinion?
1. 分类下增加标签筛选
如果要只筛选出在该分类下的标签太麻烦的话，也可以直接把所有标签作为筛选条件，如果选择该分类下有这个标签则展示，没有也无妨，为空即可。

1. 文章增加不显示在首页的属性
Front-matter 中增加对应属性即可，默认展示在首页，如果填写，则在编译时不进入首页列表，或者在首页列表增加过滤方法。

#### Are you willing to work on this yourself?
目前对于主题源码不太熟悉，如果可以明确的知道修改哪部分代码的话，我可以修改提交 PR。
前端只是基于兴趣爱好的学习，可能对于渲染性能方面不是太了解。

**Comment by recoluan** [comment]
功能1：分类和标签是筛选文章的两个不同的维度，一是没有必要混合这两个筛选条件，二是静态博客没有必要搞得太复杂，所以主题不考虑加入此功能；
功能2：同意。
