### ISSUE TITLE
翻页后，页面没有自动滚动到列表页面 ｜The page does not automatically scroll to the list page after the page is turned

### ISSUE THREAD

**Issue by wsrfde** [vuepress-reco/vuepress-theme-reco#229]
flie：Blog.vue

为什么要把 blogContentTop.value前面加个-号，是不需要让博客翻页后滚动吗？
window.scrollTo({ left: 0, top: -blogContentTop.value - 250, behavior: 'smooth' })

**Comment by recoluan** [comment]
应该是写错了，抽时间改一下
