### ISSUE TITLE
点击二级锚点目录还是跳不到目标位置

### ISSUE THREAD

**Issue by woytu** [vuepress-reco/vuepress-theme-reco#230]
请进链接 https://www.bajins.com/Other/Windows%E8%BD%AF%E4%BB%B6.html 然后随便点击一个二级目录锚点，如`AutoIt`

**Comment by recoluan** [comment]
测试了一下没问题啊

![image](https://user-images.githubusercontent.com/18067907/89408648-3f270280-d753-11ea-9f82-baa4a9ea125a.png)

**Comment by woytu** [comment]
> 测试了一下没问题啊
> 
> ![image](https://user-images.githubusercontent.com/18067907/89408648-3f270280-d753-11ea-9f82-baa4a9ea125a.png)

不好意思，我没表达清楚，我是说的顶部的那个toc，不是侧边栏

**Comment by recoluan** [comment]
已在 64dbd6323 修复，下个版本更新。
