### ISSUE TITLE
项目初始化报错

### ISSUE THREAD

**Issue by anye88** [vuepress-reco/vuepress-theme-reco#232]
# 报错信息
```
✖ [1/3] Load file from git
ErrorClass [RequestError]: connect ETIMEDOUT 192.30.253.113:443
    at ClientRequest.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/got/index.js:73:21)
    at Object.onceWrapper (events.js:313:26)
    at ClientRequest.emit (events.js:223:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ETIMEDOUT',
  message: 'connect ETIMEDOUT 192.30.253.113:443',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/recoluan/vuepress-theme-reco-demo/archive/demo/1.x.zip',
  bufferedData:
```

- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version: 
- VuePress-theme-reco version: 
- Which package manager did you use for the install(npm/cnpm/yarn)?

**Comment by wencwcoder** [comment]
me too

**Comment by recoluan** [comment]
网络问题吧，因为是从 github 拉取代码

**Comment by wencwcoder** [comment]
> 网络问题吧，因为是从 github 拉取代码

在公司里面，github 总是各种问题

**Comment by zw3428** [comment]
> > 网络问题吧，因为是从 github 拉取代码
> 
> 在公司里面，github 总是各种问题

我能 clone github 别的项目，push 也没问题，这个就初始化不了，请问下后来你初始化成功了吗......

**Comment by wencwcoder** [comment]
> > > 网络问题吧，因为是从 github 拉取代码
> > 
> > 
> > 在公司里面，github 总是各种问题
> 
> 我能 clone github 别的项目，push 也没问题，这个就初始化不了，请问下后来你初始化成功了吗......

后来我去找了个使用这个主题的项目，在vuepress 的基础上去改的，你可以看看我改的 [https://wencwcoder.github.io/](url)

**Comment by zw3428** [comment]
> > > > 网络问题吧，因为是从 github 拉取代码
> > > 
> > > 
> > > 在公司里面，github 总是各种问题
> > 
> > 
> > 我能 clone github 别的项目，push 也没问题，这个就初始化不了，请问下后来你初始化成功了吗......
> 
> 后来我去找了个使用这个主题的项目，在vuepress 的基础上去改的，你可以看看我改的 [https://wencwcoder.github.io/](url)

谢谢~~
