### ISSUE TITLE
v2.0.0-beta.67版本打包报错

### ISSUE THREAD

**Issue by silin001** [vuepress-reco/vuepress-theme-reco#233]
## Bug report
安装最新版本（v2.0.0-beta.67）本地启动没问题，打包时报错，github actions 打包时也报错

#### What is actually happening?
TypeError: Cannot read properties of undefined (reading 'replace')

#### Other relevant information
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/45745674/3fcd3916-5970-4f1c-aaec-e5cbc60a9a01)

- Your OS:  win10
- Node.js version: 16.x
- VuePress version:  2.0.0-beta.66
- VuePress-theme-reco version: v2.0.0-beta.67
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?  yarn

**Comment by chen2021z** [comment]
我也遇到了，检查你所有博客是否有date,全部加上就好了

**Comment by recoluan** [comment]
@silin001 @chen2021z 

date 不添加是没有问题，是不是 date 的格式不正确啊，你 date  是什么格式啊

**Comment by recoluan** [comment]
是的，解决了

**Comment by silin001** [comment]
ok 升级68已解决
