### ISSUE TITLE
h1标题出现了两次

### ISSUE THREAD

**Issue by shadowfish07** [vuepress-reco/vuepress-theme-reco#234]
![image](https://user-images.githubusercontent.com/38303418/89630245-ab2f7500-d8d1-11ea-91ca-ac8d46741224.png)
![image](https://user-images.githubusercontent.com/38303418/89630568-22fd9f80-d8d2-11ea-83db-77f449578fbb.png)

**Comment by woytu** [comment]
可以这样做

[https://github.com/woytu/notes-vuepress/blob/e1c0c790b52605c91c81bcf3a6895375671da3e6/.vuepress/styles/index.styl#L19-L22](https://github.com/woytu/notes-vuepress/blob/e1c0c790b52605c91c81bcf3a6895375671da3e6/.vuepress/styles/index.styl#L19-L22)

**Comment by recoluan** [comment]
主题会借鉴这种方式，方便实用 h1 来写标题。
