### ISSUE TITLE
.vue文件中导出  import { ref } from "vue";后启动项目时报错

### ISSUE THREAD

**Issue by meishaonian123** [vuepress-reco/vuepress-theme-reco#235]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/42731172/eea4f9a7-3b1d-45b6-a513-7ed462a00b63)

#### Other relevant information

- Your OS: mac
- Node.js version: 16.19.0
- VuePress version: 2.0.0-beta.66
- VuePress-theme-reco version: 2.0.0-beta.67
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?

**Comment by meishaonian123** [comment]
在ts或js中import { reactive, computed } from "vue";，然后在vue文件中引入，启动不会报错。只是在vue文件中直接引入后启动报错

**Comment by recoluan** [comment]
临时解决方案，可以使用相对路径，去 node_modules 里去引用
