### ISSUE TITLE
启用Home-Blog后首页进不去

### ISSUE THREAD

**Issue by shadowfish07** [vuepress-reco/vuepress-theme-reco#236]
我使用了这个配置后，进入网站首页一直卡在加载，控制台报错如下：
```
themeConfig: {
    type: 'blog'
  }
```
![image](https://user-images.githubusercontent.com/38303418/89715561-f4b6b780-d9d8-11ea-9553-09d7afe25fbe.png)
但如果不使用这个配置是可以正常访问的。
我自行排错步骤：
一开始博文数量较少时可以正常访问，后面一次性添加了很多文章，怀疑是里面文章格式错误，一步步删除测试后发现删到一个节点时又可以正常访问，但如果再加入任意的文件，即使新增文件内容和可以正常访问时的一篇文件内容相同，都又会报同样的错。  
然后尝试在报错的情况下直接访问非首页页面，可以正常访问，而且通过点击左上角跳转到首页，首页可以正常显示，但是如果在首页刷新依然报错进不去。
如果需要，我可以提供完整站点文件

**Comment by shadowfish07** [comment]
进一步调试后发现，我docs文件夹下原来是4个文件夹，分别代表一个分组存放md文件。只要把文件夹数量控制到两个以下就可以正常运行

**Comment by luoxuancong** [comment]
> 我使用了这个配置后，进入网站首页一直卡在加载，控制台报错如下：
> 
> ```
> themeConfig: {
>     type: 'blog'
>   }
> ```
> 
> ![image](https://user-images.githubusercontent.com/38303418/89715561-f4b6b780-d9d8-11ea-9553-09d7afe25fbe.png)
> 但如果不使用这个配置是可以正常访问的。
> 我自行排错步骤：
> 一开始博文数量较少时可以正常访问，后面一次性添加了很多文章，怀疑是里面文章格式错误，一步步删除测试后发现删到一个节点时又可以正常访问，但如果再加入任意的文件，即使新增文件内容和可以正常访问时的一篇文件内容相同，都又会报同样的错。
> 然后尝试在报错的情况下直接访问非首页页面，可以正常访问，而且通过点击左上角跳转到首页，首页可以正常显示，但是如果在首页刷新依然报错进不去。
> 如果需要，我可以提供完整站点文件

更新之后  我也遇到这个问题了

**Comment by recoluan** [comment]
能体提供一下你们的博客项目吗？我这边无法复现这个问题，可以发送至我的邮箱 recoluan@outlook.com。
