### ISSUE TITLE
build 的时候 @vuepress-reco/extract-code 插件报错且无法显示

### ISSUE THREAD

**Issue by ty-peng** [vuepress-reco/vuepress-theme-reco#237]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?
在运行 yarn build 时，出现以下报错，且插件无法正常在页面上显示，之前主题版本一直是 OK 的，该插件好像一直没有更新改动，不知道是不是主题更新后导致的问题  

![image](https://user-images.githubusercontent.com/20200179/91005379-55fd9e00-e609-11ea-955b-31904553b72b.png)

#### Other relevant information

- Your OS: Windows & Linux
- Node.js version: v10.16.3 v12.x
- VuePress version: 1.5.3
- VuePress-theme-reco version: 1.5.5
- Which package manager did you use for the install(npm/cnpm/yarn)? yarn

**Comment by recoluan** [comment]
你删除 node_modules 重新安装试一下呢

**Comment by ty-peng** [comment]
> 你删除 node_modules 重新安装试一下呢

还是会有报错

**Comment by recoluan** [comment]
暂未复现问题。
