### ISSUE TITLE
部署了v2，两个建议

### ISSUE THREAD

**Issue by eryajf** [vuepress-reco/vuepress-theme-reco#238]
1.新增了自动设置系列的配置项，autoSetSeries，这个非常nice，但是尴尬的是，貌似没能很好的支持排序，希望给一个明确的排序方式，比如1,2,3这样。
2. 如何设置自定义的base呢，目前貌似没有看到这样的配置项。 https://v2.vuepress.vuejs.org/zh/reference/config.html#base

**Comment by recoluan** [comment]
1. 目前已经做了排序了 [Code](https://github.com/vuepress-reco/vuepress-theme-reco/blob/main/packages/vuepress-theme-reco/src/client/composables/useSortSeries.ts)
2. 就按照官方网文档的这个方式设置 base 就可以了
