### ISSUE TITLE
Algolia not able to jump between titles in page

### ISSUE THREAD

**Issue by yxzlwz** [vuepress-reco/vuepress-theme-reco#239]
I opened a blog page, and then search something in the same page but different title area in Algolia, when I clicked the result, the target title starts with `#` appeared in the browser address bar, but then disappeared instantly. 

The animation of the sidebar (on the right part of the page) flashed and then reset. The page didn't scroll at all.

Test page: https://www.yixiangzhilv.com/blogs/20230729155357.html

Test Keywork: MicroG

**Comment by recoluan** [comment]
I found that this problem is caused by encryption, and I will find a solution later.
