### ISSUE TITLE
希望文档页面对标题h3和h4有更明显的样式支持，类似h2

### ISSUE THREAD

**Issue by fudalijunyi** [vuepress-reco/vuepress-theme-reco#240]
样式如下参考
![image](https://user-images.githubusercontent.com/37106981/91411252-a596d080-e87a-11ea-9843-47143b2787e8.png)

**Comment by recoluan** [comment]
可以给到一些参考

**Comment by yung-Twist** [comment]
请问2级标题要怎么去掉前面这个绿色的
