### ISSUE TITLE
时间轴时区和首页排序有误

### ISSUE THREAD

**Issue by ty-peng** [vuepress-reco/vuepress-theme-reco#243]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?
时间轴生成的日期有时候会比实际日期多一天，推测应该是时区问题，一般都是晚上发布的文章日期会多一天，应该是 +8 了

#### Other relevant information

还有个问题是有些文章首页上看不到，有些奇怪，还没找到原因

- Your OS: Windows & Linux
- Node.js version: 10.16.3
- VuePress version: 1.5.4
- VuePress-theme-reco version: 1.5.5
- Which package manager did you use for the install(npm/cnpm/yarn)?yarn

**Comment by ty-peng** [comment]
首页文章不显示原来是排序乱了

**Comment by ty-peng** [comment]
首页排序错误貌似是因为某个文件夹下有一个页面是没有日期的，加上日期就 Ok 了，但是之前也添加过很多没有日期的页面，按理说只是不展示在首页而已，背后的原因没有找到，有点奇怪

**Comment by recoluan** [comment]
针对博客日期的显示和排序做了优化，将在 `1.6.2` 中提现。

但是如果博客没有日期，仍然会被排到有时间的博客后面，这一特点不做改变。
