### ISSUE TITLE
type: blog会导致在生产环境Safari下打不开

### ISSUE THREAD

**Issue by mypridelife** [vuepress-reco/vuepress-theme-reco#247]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?

1、设置` type: "blog"`

2、npm run build 而不是 npm run dev

3、非edge/chrome，只有Safari有问题。

4、错误信息：`HierarchyRequestError: The operation would yield an incorrect node tree.` 此错误会导致一直停留在这个地方。

![image](https://user-images.githubusercontent.com/35483539/92868617-7bc1da00-f434-11ea-8cec-4d87a17c4315.png)

#### Other relevant information
测试了半天才发现是设置了type:blog导致的，郁闷

- Your OS:  macos 10.15.6
- Node.js version:  v12.16.1
- VuePress version: vuepress/1.0.2
- VuePress-theme-reco version: "vuepress-theme-reco": "^1.5.5"
- Which package manager did you use for the install(npm/cnpm/yarn)? npm

**Comment by mypridelife** [comment]
是否和 #136 有关

**Comment by mypridelife** [comment]
已排查，和 #136 无关

**Comment by recoluan** [comment]
暂未复现问题。

**Comment by tian0o0** [comment]
同样遇到这个问题，请问你解决了吗？

**Comment by tian0o0** [comment]
> 同样遇到这个问题，请问你解决了吗？

已解决，用npm会有问题，yarn则不会
