### ISSUE TITLE
使用nginx部署成功后，从主页进入详情页面，没有显示侧边栏目录，但是从顶部导航栏进入显示正常

### ISSUE THREAD

**Issue by tahitimoon** [vuepress-reco/vuepress-theme-reco#248]
问题描述：
使用nginx部署成功后，从主页进入详情页面，没有显示侧边栏目录，但是从顶部导航栏进入显示正常，如下图所示，本地调试也正常
<img width="1581" alt="image" src="https://github.com/vuepress-reco/vuepress-theme-reco/assets/37645552/6628f585-c1ad-4ed8-b777-858f3eb191e2">
<img width="1496" alt="image" src="https://github.com/vuepress-reco/vuepress-theme-reco/assets/37645552/15be8494-b688-4464-a8dc-0e1a87941b79">

- Your OS: macOS 12.6.6
- Node.js version: 16.20.0
- VuePress version: 2.0.0-beta.66
- VuePress-theme-reco version: 2.0.0-beta.67
- Which package manager did you use for the install：yarn

**Comment by recoluan** [comment]
能给我发一下网址吗，我观察一下

**Comment by tahitimoon** [comment]
部署在内网，问题解决啦。只要设置的时候加html后缀才行，不加不行。
![4613dc9eec3744e32ad0003b988d7d64](https://github.com/vuepress-reco/vuepress-theme-reco/assets/37645552/84ea64a1-a65b-4504-8049-cf9241ee60ec)
