### ISSUE TITLE
二级标题上的链接无法点击

### ISSUE THREAD

**Issue by ty-peng** [vuepress-reco/vuepress-theme-reco#248]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?
下方紧邻二级标题的超链接无法点击，必须要在下方添加其他内容当前链接才可点击

浏览器: Chrome 80.0.3987.163

#### Other relevant information

- Your OS: Windows
- Node.js version: 10.16.3
- VuePress version: 1.5.4
- VuePress-theme-reco version: 1.5.5
- Which package manager did you use for the install(npm/cnpm/yarn)?yarn

**Comment by recoluan** [comment]
与 #246 重复。
