### ISSUE TITLE
配置-首页的bannner->heroImageStyle配置样式不生效

### ISSUE THREAD

**Issue by zhangjinyuan190729** [vuepress-reco/vuepress-theme-reco#249]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?
配置-首页的bannner->heroImageStyle配置样式不生效
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/53432711/785e724f-69ad-44d0-9e05-8c1e8e45516b)
应该使用展开运算符
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/53432711/f5ca4288-bccd-4a5d-988d-e6e5e011d341)

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version:  2.0.0-beta.67
- VuePress-theme-reco version: 2.0.0-beta.68
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?npm

**Comment by recoluan** [comment]
收到，你方便提交一个pr吗

**Comment by zhangjinyuan190729** [comment]
已提交pr
