### ISSUE TITLE
Add infoCard

### ISSUE THREAD

**Issue by LocTran016** [vuepress-reco/vuepress-theme-reco#252]
## Feature request
Can you please add a infoCard like this:
![image](https://user-images.githubusercontent.com/64778285/93085871-72e53880-f6c0-11ea-8646-a508b7b5a29d.png)
This picture is from [here](https://vuepress-theme-meteorlxy.meteorlxy.cn/posts/2019/02/27/theme-guide-en.html), it's a feature of [vuepress-theme-meteorlxy](https://github.com/meteorlxy/vuepress-theme-meteorlxy)
It would be great if you add some small icon for social media account
#### What problem does this feature solve?
Absolute it would be better than adding the contact information in the nav bar
#### How should this be implemented in your opinion?
In the newest version, your Card seem look great and if you can change the headerBackground of the infoCard as well as add the contact information in the card would be great
#### Are you willing to work on this yourself?
Sorry, I don't have any knowledge about coding and programming so I don't have the ability to do this, really sorry

**Comment by recoluan** [comment]
I didn't focus on this place in my previous work. I will optimize it according to your Suggestions later. 

The process will not be as fast as it is due to the lack of personal free time, but please rest assured that your Suggestions will be reflected in later versions. 

Thanks again for your suggestions.

**Comment by recoluan** [comment]
This is the example:

<img 
  width="300px"
  src="https://user-images.githubusercontent.com/18067907/100771463-6b206f00-3439-11eb-8ce4-6c8521020fcf.png" 
/>
