### ISSUE TITLE
Add more icon

### ISSUE THREAD

**Issue by LocTran016** [vuepress-reco/vuepress-theme-reco#253]
## Feature request
Can you please add reddit as well as instagram icon because these social media sites are widely-used
#### What problem does this feature solve?
Missing some social media icon
#### How should this be implemented in your opinion?
Well, because Reddit and Instagram have a lot of user so adding the icon would be good
#### Are you willing to work on this yourself?
Sorry, I don't have the ability to do this

**Comment by recoluan** [comment]
Thank you for your suggestion. Are there any other icons that need to be added?

**Comment by LocTran016** [comment]
I think that is enough but some science symbol (for example a microscope/molecule icon is good as well) is better for those having science blog

**Comment by LocTran016** [comment]
> Thank you for your suggestion. Are there any other icons that need to be added?

May be you could add a way to use fontawesome 5's icon (for example: `icon: "github fab"` stand for github icon where `fab` is the prefix): I have found [a hexo theme](https://molunerfinn.com/hexo-theme-melody-doc/theme-config.html#social-icons) which have this feature

**Comment by LocTran016** [comment]
I have try to use FontAwesome but there is a small problem here. Vuepress-theme-reco add the iconfont before `fab fa-bitbucket fa-xs` which lead to this issue, I don't know if you can fix this
![image](https://user-images.githubusercontent.com/64778285/94986842-3f455200-058c-11eb-81cf-19feb681dac3.png)

**Comment by rexwangcc** [comment]
@LocTran016 Not sure this helps since you seems to look for extra icons in the sidebar/navbar, but if you want to insert icons to the blog posts, my current work around is to use a plugin `@nine-theme/vuepress-plugin-fontawesome`: https://rexwang.cc/blogs/2020/000-writing-guide/writing-guide.html#_13-insert-icons

**Comment by recoluan** [comment]
The theme already supports Font Awesome ([commit detail](https://github.com/vuepress-reco/vuepress-theme-reco/commit/984ed3fc041498611b139ecd273f28af0b2ad00c)).
