### ISSUE TITLE
怎么自定义主题颜色呢

### ISSUE THREAD

**Issue by bean4896** [vuepress-reco/vuepress-theme-reco#253]
:root {
    --link-color-light: #8B0000;  
    --link-color-dark: #FFA07A;   
 }
 
 @media (prefers-color-scheme: light) {
     :root {
         --linkColor: var(--link-color-light);
     }
 }
 
 @media (prefers-color-scheme: dark) {
     :root {
         --linkColor: var(--link-color-dark);
     }
 }
 
 a {
    color: var(--linkColor);
 }
 
 我在styles>index.css 加这些做一个尝试 没有用

**Comment by wstee** [comment]
[https://vuepress-theme-reco.recoluan.com/docs/theme/custom-primary-color.html](https://vuepress-theme-reco.recoluan.com/docs/theme/custom-primary-color.html)
