### ISSUE TITLE
run dev后，修改代码后，每次刷新都要加载很多js，很慢，是正常的吗？

### ISSUE THREAD

**Issue by yijiepifu** [vuepress-reco/vuepress-theme-reco#254]
run dev后，修改代码后，每次刷新都要加载很多js，很慢，是正常的吗？

**Comment by yijiepifu** [comment]
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/8278902/44854f8d-6204-447c-af7c-89e9c34d350a)

**Comment by NetFreeOps** [comment]
加载速度特别慢，不知道为啥

**Comment by recoluan** [comment]
vuepress 升级到 rc.9，主题升级到 rc.8 再试试
