### ISSUE TITLE
Add date setting

### ISSUE THREAD

**Issue by LocTran016** [vuepress-reco/vuepress-theme-reco#255]
## Feature request
Add a setting for changing date format
#### What problem does this feature solve?

Different culture use different date format (for ex: some countries use `ddd DD MMM YYYY` but some others use `ddd MMM DD YYYY` so having a setting for this would great

#### How should this be implemented in your opinion?

This will extremely important because people using a different date format

#### Are you willing to work on this yourself?
Sorry, I can't do this because I'm not a coder. Truly sorry

**Comment by recoluan** [comment]
This is a very good suggestion and I appreciate your feedback.
