### ISSUE TITLE
使用 theme-cli生成的2.x无法立即使用

### ISSUE THREAD

**Issue by threeTrave** [vuepress-reco/vuepress-theme-reco#257]
- [x] I confirm that this is an issue rather than a question.

## Bug report
2。使用主题cli生成的2.x无法立即使用，并且无法显示初始页面。控制台报告错误：
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/122736310/4ff865a5-4eaf-43ed-90d5-d54d77ff5dc0)
错误指向此文件
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/122736310/8794fa4f-0efd-4544-a2f2-9ee57d28824e)
第三十行代码 ：const localePaths = Object.keys(locales).sort((a, b) => ...
我怀疑locales配置项未被确定为未定义。在检查原始config.ts文件时，确实没有定义与本地相关的设置。
解决方法一：
在config中设置locales配置项后之后，bug就会消失。（示例下面的评论已经给出）
解决方法二：
在报错的文件中对local是否为undefine进行判空，bug就会消失。如下所示：
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/122736310/a3c55c7f-c2d5-43ce-b8b4-e0a70246d8e4)

#### Other relevant information

- Your OS: 
- Node.js version: 20.10.0
- VuePress version: 2.0.0-rc.0
- VuePress-theme-reco version: 2.0.0-rc.1
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?npm&yarn

**Comment by HSqure** [comment]
It worked! Thanks!

**Comment by minibear2333** [comment]
<img width="555" alt="image" src="https://github.com/vuepress-reco/vuepress-theme-reco/assets/42294819/39d1242d-ca50-4326-97be-b1196b7a1851">

在主题配置里添加以下内容即可

```js
locales: {
      // 键名是该语言所属的子路径
      // 作为特例，默认语言可以使用 '/' 作为其路径。
      '/': {
        lang: 'zh-CN',
        title: 'VuePress',
        description: 'Vue 驱动的静态网站生成器',
      },
    },
```

**Comment by zhooke** [comment]
感谢，有用，不知道为啥不改呢

**Comment by Guocccw** [comment]
It worked! 不过这个bug很难搞吗?怎么离谱的问题都不改
