### ISSUE TITLE
The type option in commentConfig in config.ts of the 2.0 project generated by theme cli was misspelled

### ISSUE THREAD

**Issue by threeTrave** [vuepress-reco/vuepress-theme-reco#258]
- [x] I confirm that this is an issue rather than a question.

## Bug report
This is the commentConfig in the default config.ts file generated by theme cli, and the type attribute is' valie ', which is obviously incorrect
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/122736310/1410e52f-2cbf-4495-9002-f3496c2b8c72)
Judgment in the source code
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/122736310/1aa897ac-2a81-4729-bbdc-b3ed077f1cdd)
In fact, this bug is very small, and upon closer inspection, you will find it, but it can bring about a bad experience, and it feels like it's not something to use right out of the box
#### Other relevant information

- Your OS: 
- Node.js version: 20.10.0
- VuePress version: 2.0.0-rc.0
- VuePress-theme-reco version: 2.0.0-rc.1
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?npm & yarn

**Comment by recoluan** [comment]
Thank you for your advice. I've fixed it in  ([commit](https://github.com/vuepress-reco/vuepress-theme-reco-demo/commit/0dd474bcb38e4ac0cad873f9282dfbfaad6c6983)).
