### ISSUE TITLE
下载源码运行或者使用yarn安装脚手架创建初始化项目，会因为yarn 源的问题报错，运行不起来

### ISSUE THREAD

**Issue by mrjerryli** [vuepress-reco/vuepress-theme-reco#259]
- [ ] I confirm that this is an issue rather than a question.

## Bug report

源码运行或脚手架创建项目初始化报错，影响项目正常运行。

- 源码运行

   ```
   git clone git@github.com:vuepress-reco/vuepress-theme-reco.git
   cd vuepress-theme-reco
   yarn install
   ```
- 脚手架创建项目初始化

   ```
   yarn global add @vuepress-reco/theme-cli
   theme-cli init
   cd 项目名
   yarn install
   ```

#### What is actually happening?

错误信息如下：
error An unexpected error occurred: "http://r.npm.sankuai.com/@vuepress/core/download/@vuepress/core-1.5.0.tgz: getaddrinfo ENOTFOUND r.npm.sankuai.com".

#### Other relevant information

- Your OS:  MacOS Big Sur
- Node.js version:  14.11.0.
- VuePress version: 1.5.0
- VuePress-theme-reco version: 1.5.5
- Which package manager did you use for the install(npm/cnpm/yarn)?
   yarn

**Comment by recoluan** [comment]
与 #256 问题为同一问题。
