### ISSUE TITLE
markdown-it-plantuml 插件未生效

### ISSUE THREAD

**Issue by Q-Action** [vuepress-reco/vuepress-theme-reco#260]
添加插件后，也在配置文件中增加配置，没有生效
![image](https://user-images.githubusercontent.com/17774429/93953982-231d0600-fd7f-11ea-8532-992c7abc0198.png)
![image](https://user-images.githubusercontent.com/17774429/93953999-2e703180-fd7f-11ea-98a9-b53461d07335.png)
![image](https://user-images.githubusercontent.com/17774429/93954018-392ac680-fd7f-11ea-8209-e8bca96c27ad.png)
![image](https://user-images.githubusercontent.com/17774429/93954069-5790c200-fd7f-11ea-9e36-82f570ccab10.png)

能帮忙看看问题吗

**Comment by Q-Action** [comment]
依赖情况：
```
"devDependencies": {
    "vuepress": "^1.5.4",
    "markdown-it-plantuml": "^1.4.1",
    "vuepress-plugin-mathjax": "^1.2.8",
    "vuepress-theme-reco": "^1.5.5"
  },
  "dependencies": {
    "@vuepress-reco/vuepress-plugin-comments": "^1.5.7",
    "@vuepress-reco/vuepress-plugin-kan-ban-niang": "^1.0.5",
    "markdown-it": "^11.0.1",
    "vuepress-plugin-cat": "^1.0.3",
    "vuepress-plugin-comment": "^0.7.3",
    "vuepress-plugin-latex": "^0.1.3",
    "vuepress-plugin-mermaidjs": "^1.8.0",
    "vuepress-plugin-reading-progress": "^1.0.10"
```
配置情况：
```
markdown: {
    extendMarkdown: (md) => {
      md.use(require('markdown-it-plantuml'))
    },
  },
  theme: require.resolve('./theme'),
```

**Comment by recoluan** [comment]
请到 vuepress 提 issue。
