### ISSUE TITLE
有计划升级vuepress2的版本么

### ISSUE THREAD

**Issue by linpeilie** [vuepress-reco/vuepress-theme-reco#263]
目前引用的vuepress2的版本为2.0.0-rc.0，vuepress2从2.0.0-rc.2才有提供sitemap和seo插件，或者有其他的方式可以添加sitemap和seo？

**Comment by recoluan** [comment]
正在尝试升级到 rc8，升级后遇到一些问题已经给 vuepress 提了 issue，还没得到回复。

**Comment by recoluan** [comment]
vuepress 的版本已经升级到 rc.9，主题最新版本 rc.8。
