### ISSUE TITLE
黑暗模式 主页标题颜色问题

### ISSUE THREAD

**Issue by sonderlau** [vuepress-reco/vuepress-theme-reco#264]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?
![image](https://user-images.githubusercontent.com/12829325/95408219-86c23a00-090e-11eb-8047-169a81143e2a.png)

黑暗模式 主页的标题颜色 太深了

**Comment by recoluan** [comment]
下个版本将优化此问题。
