### ISSUE TITLE
Why is the default theme black?

### ISSUE THREAD

**Issue by yaozongbin** [vuepress-reco/vuepress-theme-reco#265]
Why is the default theme black?

- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Your OS: 
- Node.js version: 17
- VuePress version: 2
- VuePress-theme-reco version: 2.x
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?

**Comment by InsHomePgup** [comment]
https://vuepress-theme-reco.recoluan.com/docs/theme/appearance.html
