### ISSUE TITLE
为什么点击标签按钮不会跳转？

### ISSUE THREAD

**Issue by wankaiyi** [vuepress-reco/vuepress-theme-reco#267]
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/129262385/46e40ba4-b5da-4e48-b5aa-048bd9bc63e2)
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/129262385/21caec6d-c814-4417-97bd-e56aa0180e9a)
为什么点了那个标签的按钮，地址栏变了，但是没有跳转到对应的页面，要手动刷新才会跳转

- Your OS: Window11
- Node.js version: 18.20.0
- VuePress version: 2
- VuePress-theme-reco version: 2.x
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? npm

**Comment by recoluan** [comment]
具体版本是多少啊

**Comment by wankaiyi** [comment]
npm是10.5.0
"vuepress": "2.0.0-rc.0",
"vuepress-theme-reco": "2.0.0-rc.5"

**Comment by recoluan** [comment]
vuepress 升级到 rc.8，主题升级到 rc.7 试试呢，但是有点其他 bug，你先试试能不能正常

**Comment by wankaiyi** [comment]
还有新的问题就是升级了版本后：
1. markdown的渲染出现了问题
2. 之前的标签页404了

**Comment by wankaiyi** [comment]
感谢大佬，刚刚试了一下路由没问题了，其他就是markdown渲染有点奇怪

**Comment by recoluan** [comment]
> 感谢大佬，刚刚试了一下路由没问题了，其他就是markdown渲染有点奇怪

vuepress 升级到 rc.9，主题升级到 rc.8 再试试

**Comment by wankaiyi** [comment]
> > 感谢大佬，刚刚试了一下路由没问题了，其他就是markdown渲染有点奇怪
> 
> vuepress 升级到 rc.9，主题升级到 rc.8 再试试

可以了，已经完美解决了

**Comment by wankaiyi** [comment]
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/129262385/df9d299e-9ca3-4305-b5d8-510a885ddece)
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/129262385/2680abd8-3c24-425c-8dfd-489b9a7d05dd)
还有个问题就是主页的标签的链接还没有变

**Comment by recoluan** [comment]
> ![image](https://private-user-images.githubusercontent.com/129262385/323441148-df9d299e-9ca3-4305-b5d8-510a885ddece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDgwNTMsIm5iZiI6MTcxMzQwNzc1MywicGF0aCI6Ii8xMjkyNjIzODUvMzIzNDQxMTQ4LWRmOWQyOTllLTljYTMtNDMwNS1iNWQ4LTUxMGE4ODVkZGVjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwMjM1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDU1YmU4ZDcyZTk0YWNhOWRmY2UwMTBjMWEyOTQ3OGZmN2JmMDdmMzMyODhmZGIzOWJhNzMzYTc1MGEyOTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C4iNAJS4xWybH5SAB80Hffin6n-ky4dRVG3BnJbGXJA)
> 
> ![image](https://private-user-images.githubusercontent.com/129262385/323441330-2680abd8-3c24-425c-8dfd-489b9a7d05dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDgwNTMsIm5iZiI6MTcxMzQwNzc1MywicGF0aCI6Ii8xMjkyNjIzODUvMzIzNDQxMzMwLTI2ODBhYmQ4LTNjMjQtNDI1Yy04ZGZkLTQ4OWI5YTdkMDVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwMjM1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTQ1MjQwMzRjNmE1N2MzOTZlNGNiODVkN2EyM2ZlODM1MjlhMGY2ODMwOThjZjRkZDc1NTE3NTE2MWY2ZmJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c5V7BAvDGULRMrBxMxteHo0DW8UMPiq5d-XOg_QDA8M) 还有个问题就是主页的标签的链接还没有变

收到，这里落下了，尽快修复

**Comment by wankaiyi** [comment]
> 收到，这里落下了，尽快修复

好的，谢谢！期待更新
