### ISSUE TITLE
绝对加密 absoluteSecrecy: true 存疑

### ISSUE THREAD

**Issue by Mu-Yan** [vuepress-reco/vuepress-theme-reco#268]
vuepress-theme-reco@1.5.7 版本 ，设置absoluteSecrecy: true时无效，经查源码内未使用absoluteSecrecy

**Comment by recoluan** [comment]
请使用 `absoluteEncryption: true`，我修改一下文档。

**Comment by Mu-Yan** [comment]
> 请使用 `absoluteEncryption: true`，我修改一下文档。

使用后存在样式兼容问题

![image](https://user-images.githubusercontent.com/38280175/100210810-5ed27880-2f46-11eb-878c-8ca0a8006a12.png)

输入框直接置顶，并且遮挡侧边栏，标题等

**Comment by Mu-Yan** [comment]
我通过修改Layout.vue 源码解决了这个问题。

在 vuepress-theme-reco 留言板留言过

留言内容：

由于无法设定absoluteSecrecy，我这边在themeConfig添加了pAbsoluteSecrecy（布尔类型）参数，并修改了Layout.vue页面的相关代码(注：vuepress-theme-reco@1.5.7)，以实现文章页面的绝对加密
``` vue
<Page v-else-if="!$themeConfig.pAbsoluteSecrecy || isHasPage" :sidebar-items="sidebarItems"/>
```
``` js
methods: {
    hasPageKey () {
      let pageKeys = this.$frontmatter.keys
      if (!pageKeys || pageKeys.length === 0) {
        this.isHasPage = true
        return
      }
      
      pageKeys = pageKeys.map(item => item.toLowerCase())
      this.isHasPage = pageKeys.indexOf(sessionStorage.getItem(`pageKey${window.location.pathname}`)) > -1
    },
  },
  watch: {
    $frontmatter (newVal, oldVal) {
      this.hasPageKey()
    }
  }
```
