### ISSUE TITLE
请问我设置了 algolia 但是搜索不到内容, 请问如何解决

### ISSUE THREAD

**Issue by Pupper0601** [vuepress-reco/vuepress-theme-reco#268]
配置文件
<img width="500" alt="image" src="https://github.com/vuepress-reco/vuepress-theme-reco/assets/58965954/39c55ad6-554b-4b52-9843-2dd08bf0bbd5">
algolia 爬取脚本
<img width="500" alt="image" src="https://github.com/vuepress-reco/vuepress-theme-reco/assets/58965954/425783b5-a86e-4597-92dc-4ed2172dd403">
<img width="500" alt="image" src="https://github.com/vuepress-reco/vuepress-theme-reco/assets/58965954/ac4efd19-a319-4743-9a7d-0d3f2d878eda">
没看到配置有问题, 请问要如何解决

**Comment by recoluan** [comment]
这个我也不太清楚，很久没陪配置过 algolia 了，并且这个功能是用的 vuepress 的官方插件，你去那边问一下呢。
