### ISSUE TITLE
标题显示错误

### ISSUE THREAD

**Issue by vlssu** [vuepress-reco/vuepress-theme-reco#269]
- [x] I confirm that this is an issue rather than a question.

## Bug report
null

#### What is actually happening?
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/43847794/5a929162-b163-48cc-9771-a42add2f8f6c)
![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/43847794/eed0df66-5e27-4a64-b42a-151004eb9bb0)
很明显，二级标题他默认不显示，需要把鼠标指针往上移才会显示，且样式有点问题，就跟没换行一样

#### Other relevant information

- Your OS: ubuntu-latest
- Node.js version: 20
- VuePress version: 2.0.0-rc.8
- VuePress-theme-reco version: 2.0.0-rc.7
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? yarn@4.1.1

**Comment by recoluan** [comment]
升级一下，vuepress@2.0.0-rc.9 vuepress-theme-reco@2.0.0-rc.8

**Comment by recoluan** [comment]
删除 cache 文件重新启动试试呢

**Comment by vlssu** [comment]
虽然f12控制台还是报错，但是页面已经能够正常访问了
