### ISSUE TITLE
评论插件不支持vpress 2.0.0-rc.9？

### ISSUE THREAD

**Issue by wankaiyi** [vuepress-reco/vuepress-theme-reco#270]
运行npm i -D vuepress-plugin-comment2时报错：
npm i -D vuepress-plugin-comment2
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vuepress-theme-reco-demo@2.0.0
npm ERR! Found: vuepress@2.0.0-rc.9
npm ERR! node_modules/vuepress
npm ERR!   vuepress@"2.0.0-rc.9" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vuepress@"2.0.0-rc.8" from vuepress-plugin-comment2@2.0.0-rc.30
npm ERR! node_modules/vuepress-plugin-comment2
npm ERR!   dev vuepress-plugin-comment2@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

报错说明vpress 2.0.0-rc.9不支持vuepress-plugin-comment2插件

**Comment by recoluan** [comment]
找一下插件方吧，看是不是需要适配，跟主题应该关系应该不大

**Comment by wankaiyi** [comment]
> 找一下插件方吧，看是不是需要适配，跟主题应该关系应该不大

好的，谢谢
