### ISSUE TITLE
新创建的项目需要很久才能加载出来内容（The newly created project takes a long time to load its content）

### ISSUE THREAD

**Issue by xifan052** [vuepress-reco/vuepress-theme-reco#272]
#### What is actually happening?

如标题描述，在运行之后需要加载的内容太多了，导致http请求阻塞，需要很久才能加载完毕，这里是否有优化的方法来减少加载的依赖，

![1714148050977](https://github.com/vuepress-reco/vuepress-theme-reco/assets/34504196/0f1bace5-d1bc-45ed-bbb0-98afa0b53062)

是新建的项目，并没有什么内容，

![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/34504196/4783d5d8-9a71-453e-9549-4650860cd41a)

是不是不能使用viteBundler

![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/34504196/0019776d-b6c1-446f-a327-aed1b2635f03)

#### Other relevant information

- Your OS: Windows 10 专业版
- Node.js version: v20.10.0
- VuePress version: 2.0.0-rc.9
- VuePress-theme-reco version: 2.0.0-rc.8
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? yarn

**Comment by recoluan** [comment]
用 webpackBundler 会好一些
