### ISSUE TITLE
希望保留单篇文章的原生 sidebar 样式

### ISSUE THREAD

**Issue by CyC2018** [vuepress-reco/vuepress-theme-reco#273]
#### What problem does this feature solve?

原生 sidebar 在移动端能展示，而 subsidebar 不行。希望能提供一个配置项，保留原生 sidebar。

**Comment by recoluan** [comment]
可以增加子侧边栏在移动端的适配，但是不会再让两者兼容了。

**Comment by Candane** [comment]
> 可以增加子侧边栏在移动端的适配，但是不会再让两者兼容了。

点击subsidebar标题滚动的时候能不能使内容偏移上面一段距离，现在太靠近nav了，感觉好别扭
