### ISSUE TITLE
Navbar 點擊 nav item 沒載入該頁面

### ISSUE THREAD

**Issue by whyayen** [vuepress-reco/vuepress-theme-reco#278]
## Bug report
不確定是否 config.js 設定有問題，但我 build 出來的網頁，第一次進入頁面的時候，點擊 nav bar 的連結 (category、tag、timeline) 後，網址會變，但頁面不會跳轉，console 也沒 error，重新整理後再點擊便可以跳轉到該頁面。

連結：https://blog.jayuen.dev/
config 設定：https://github.com/whyayen/blog/blob/master/.vuepress/config.js

#### What is actually happening?
點擊 nav bar 的連結，頁面應跳轉

#### Other relevant information
只有 build 出來的才有這問題，在 dev server 內沒發生

- Your OS: MacOS
- Node.js version: 
- VuePress version: 1.5.4
- VuePress-theme-reco version: 1.5.7
- Which package manager did you use for the install(npm/cnpm/yarn)? yarn

**Comment by recoluan** [comment]
你好朋友，我 clone 了你的项目在本地尝试了一下，发现没有问题，也许你应该删除 node_modules 并重新安装 npm 依赖，重新尝试一下，如果还有问题随时沟通。

**Comment by whyayen** [comment]
@recoluan 謝謝，抱歉我再試試，可能是透過 GitHub Actions 部屬或一些 GitHub Pages 設定不當導致，這裡先關閉 issue，待研究出原因再補充，感謝 👍🏾
