### ISSUE TITLE
autoSetSeries: true，自动设置系列失效  ，左侧没有自动根据文件夹目录生成侧边栏

### ISSUE THREAD

**Issue by zhaochengyang123** [vuepress-reco/vuepress-theme-reco#278]
package.json：{
  "name": "vuepress-theme-reco-demo",
  "version": "2.0.0",
  "description": "Demo for vuepress-theme-reco@2.x.",
  "repository": "git@github.com:recoluan/vuepress-theme-reco-demo.git",
  "author": "reco_luan <recoluan@outlook.com>",
  "license": "MIT",
  "scripts": {
    "dev": "vuepress dev .",
    "start": "vuepress dev .",
    "build": "vuepress build ."
  },
  "dependencies": {
    "vue": "^3.4.19",
    "vuepress": "2.0.0-rc.9",
    "vuepress-theme-reco": "2.0.0-rc.9",
    "@vuepress/bundler-vite": "2.0.0-rc.9",
    "@vuepress/bundler-webpack": "2.0.0-rc.9"
  }
}
实测  "vuepress-theme-reco": "2.0.0-rc.8"时也不行，node版本v20.12.2 ，操作系统win11 ，目录和文件名无中文字符

**Comment by recoluan** [comment]
已经找到原因，尽快修复。
