### ISSUE TITLE
请问分类设置成汉字后，导致刷新页面404，这个怎么解决

### ISSUE THREAD

**Issue by it01-co** [vuepress-reco/vuepress-theme-reco#281]
- [x] I confirm that this is an issue rather than a question.

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version: 
- VuePress-theme-reco version: 
- Which package manager did you use for the install(npm/cnpm/yarn)?

**Comment by pythonsir** [comment]
同问

**Comment by dycong** [comment]
同问
macOS
node 10.14.0
vuepress 1.8
vuepress-theme-reco 1.6.1

**Comment by JOJO567** [comment]
你可以将 Vue-router 回退到 3.4.5

**Comment by ATQQ** [comment]
可查看这个[issue:276](https://github.com/vuepress-reco/vuepress-theme-reco/issues/276)　

有一些解法
