### ISSUE TITLE
侧边栏组别名能加黑不

### ISSUE THREAD

**Issue by cikichen** [vuepress-reco/vuepress-theme-reco#282]
侧边栏的组别名在文章标题长的时候感觉不明显，能不能加黑加粗

**Comment by recoluan** [comment]
麻烦贴一下现在样式的截图

**Comment by cikichen** [comment]
![image](https://user-images.githubusercontent.com/1478821/103116438-7b76e300-46a1-11eb-8245-1ae3e66ddad6.png)
@recoluan

**Comment by cikichen** [comment]
还一个问题是侧边栏文章多的时候，通过顶部菜单栏点击不能定位到选中的那片文章
![image](https://user-images.githubusercontent.com/1478821/103116741-6fd7ec00-46a2-11eb-8d38-b50e42631221.png)

**Comment by recoluan** [comment]
最近在用 vca 重构，为了 vuepress@2.x 做准备，抽空会根据你的建议做一下优化的。
