### ISSUE TITLE
Fix english translation for tags and categories labels

### ISSUE THREAD

**Issue by Zenahr** [vuepress-reco/vuepress-theme-reco#283]
对不起，我不会说中文。因此，我使用图像进行通信。

![image](https://user-images.githubusercontent.com/47085752/103164364-bf392c00-480a-11eb-9455-f6527add0938.png)

![image](https://user-images.githubusercontent.com/47085752/103164387-ff001380-480a-11eb-8f1c-d3574753f17b.png)

**Comment by recoluan** [comment]
Thank you very much for your contribution and your interest in this theme.
