### ISSUE TITLE
地址栏携带文档标题时，刷新页面 404

### ISSUE THREAD

**Issue by LiJunYi2** [vuepress-reco/vuepress-theme-reco#283]
版本如下：
```xml
"vue": "^3.4.19",
"vuepress": "2.0.0-rc.11",
"vuepress-theme-reco": "2.0.0-rc.12"
```

地址栏一旦出现标题，刷新后就会报 404 错误：
<img width="796" alt="image" src="https://github.com/vuepress-reco/vuepress-theme-reco/assets/40384503/c3738765-c4ac-48d6-b855-e82cfcbc0538">

**Comment by recoluan** [comment]
This is a problem with vuepress, as detailed in [issue#1561](https://github.com/vuepress/core/issues/1561), which has been fixed in [pr#1562](https://github.com/vuepress/core/pull/1562).
