### ISSUE TITLE
电脑版微信内置浏览器打开错误

### ISSUE THREAD

**Issue by OrenZhang** [vuepress-reco/vuepress-theme-reco#286]
使用电脑版微信打开时会一直处在加载界面无法正常进入。

https://www.recoluan.com/

[![r70i0f.png](https://s3.ax1x.com/2020/12/28/r70i0f.png)](https://imgchr.com/i/r70i0f)

**Comment by ZHXDiDa** [comment]
经过测试

有问题：https://www.recoluan.com/
（包含我自己的博客和文档）

没问题：https://vuepress-theme-reco.recoluan.com/
