### ISSUE TITLE
Build does not work. Broken CSS

### ISSUE THREAD

**Issue by Zenahr** [vuepress-reco/vuepress-theme-reco#287]
- [x] I confirm that this is an issue rather than a question.

## Bug report
The website is shown correctly when I use `yarn dev`.
![image](https://user-images.githubusercontent.com/47085752/103303064-5bc71e00-4a05-11eb-95cc-8a78a39cd401.png)

Using `yarn build` and opening `index.html` inside the `public` folder however does not show the website correctly.
![image](https://user-images.githubusercontent.com/47085752/103303142-84e7ae80-4a05-11eb-8a8a-d52c83c44bd6.png)
(Github Pages)

![image](https://user-images.githubusercontent.com/47085752/103303228-bb252e00-4a05-11eb-8c88-0a83f6e54e62.png)
(Console Log)

#### Other relevant information

- Your OS: Windows 10
- Node.js version: v14.15.3
- VuePress version: 1.7.1
- VuePress-theme-reco version: 1.6.0
- Which package manager did you use for the install? npm

**Comment by rexwangcc** [comment]
With a quick look at your screenshots it seems your base paths are different between your local dev server and the deployed (I assumed Github Pages), maybe it's helpful to set the `base`? (see Vuepress's config doc [here](https://vuepress.vuejs.org/config/#base)).

Also, I couldn't reproduce the issue with `npm` or `yarn`, either of which runs `vuepress build .` under the hood. The [Chrome dev server app](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb/related?hl=en) might be helpful to debug this specific issue locally without uploading the built files to the server, but it's still hard for me to believe there's an actual Content Security Policy issue with the theme as your console log shows.

**Comment by Zenahr** [comment]
@rexwangcc thanks for the quick reply! I seem to have forgotten to set the base-url. I'll test and and check back for other who might run into this issue themselves.

**Comment by Zenahr** [comment]
@rexwangcc That solved the problem. Thanks!
