### ISSUE TITLE
2.x打包样式丢失

### ISSUE THREAD

**Issue by HXF-A** [vuepress-reco/vuepress-theme-reco#288]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
打包之后访问文件路径有问题
<img width="1157" alt="image" src="https://github.com/vuepress-reco/vuepress-theme-reco/assets/51697295/a6f38ad4-22de-49f4-826b-3fc9cd773da7">
现象：
<img width="1507" alt="image" src="https://github.com/vuepress-reco/vuepress-theme-reco/assets/51697295/d8c39ee8-f684-4ef4-a0b6-c961f52c3b2b">

<img width="416" alt="image" src="https://github.com/vuepress-reco/vuepress-theme-reco/assets/51697295/bf73a1a1-ea46-4a52-8714-bb11ed6bb5e1">

#### Other relevant information

- Your OS: macbook pro M1
- Node.js version: v18.18.2
- VuePress version: 2.0.0-rc.12
- VuePress-theme-reco version: 2.0.0-rc.13
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?
- npm

**Comment by HXF-A** [comment]
<img width="556" alt="image" src="https://github.com/vuepress-reco/vuepress-theme-reco/assets/51697295/a4ed7db5-c5b8-4581-8fc9-bd2907db8866">
使用npx下载

**Comment by recoluan** [comment]
是不是直接打开的index.html，静态资源的路径引用方式，需要你将编译后的资源放到 server 下才可以
