### ISSUE TITLE
请求支持vuepress 2.0

### ISSUE THREAD

**Issue by Urie96** [vuepress-reco/vuepress-theme-reco#289]
## Feature request

npm上已经发布了vuepress 2.0的alpha版本，请问最近有开发适配vuepress 2.0版本的计划吗？

**Comment by recoluan** [comment]
主题目前在使用 vca 重写代码，为升级做准备。但是同 vuepress 负责人沟通的结果是，`vuepress@2.x` 可能会重构主题系统，那样的话升级成本会很高，所以具体结果会在 `vuepress@2.x` 确定重构方案后再说，我会尽最大努力升级的。
