### ISSUE TITLE
大佬， 在下提一建议

### ISSUE THREAD

**Issue by xiangergou** [vuepress-reco/vuepress-theme-reco#29]
项目初始化时如果不指定目录名称会报错
TypeError: Path must be a string. Received true
个人觉着此处可以考虑做兼容， 不指定项目名称即默认初始化至当前目录下， 大佬以为如何。  这其实很常见 我记着之前大点的CLI大多是这样

**Comment by recoluan** [comment]
好的，接受你的建议，后面尝试改进。

留下 <notifications@github.com> 于2019年7月11日周四 上午10:04写道：

**Comment by recoluan** [comment]
`@vuepress-reco/theme-cli@1.0.6` 支持是否新建文件夹。
