### ISSUE TITLE
@vuepress-reco/core/lib/components cannot be loaded

### ISSUE THREAD

**Issue by dennislblog** [vuepress-reco/vuepress-theme-reco#290]
- [ x ] I confirm that this is an issue rather than a question.

#### What is actually happening?
So long as `ts/tsx` files are trying to be loaded, an error is thrown out 
```
Module not found: Error: Can't resolve '@vuepress-reco/core/lib/components' in 'xxxx\node_modules\vuepress-theme-reco\components'
```

#### Other relevant information
I have tried to install typescript locally but this problem persists. I have tried version 1.6 and the latest version both of which throw the same "module not found" errors. 

- Your OS:   **Microsoft Windows [Version 10.0.19042.685]**
- Node.js version:   **v10.16.0**
- VuePress version:  **1.7.1**
- VuePress-theme-reco version:  **1.6**
- Which package manager did you use for the install(npm/cnpm/yarn)?  **yarn**

**Comment by recoluan** [comment]
Can you send me your code address, or send your code to my email `recoluan@outlook.com`. Let me check.

**Comment by dennislblog** [comment]
> Can you send me your code address, or send your code to my email `recoluan@outlook.com`. Let me check.

Hi, just to make sure my emails are sent. I am using vuepress-theme-reco^1.4.7 and websites are rendered completely fine. I am just a little curious of what might be wrong because I am new to vue and typescript language.

**Comment by recoluan** [comment]
`@vuepress-reco/core` is a new package added in version 1.7.1, but there is no problem when I test locally, maybe you can try to delete node_modules and re-execute `npm install` to solve your problem, because sometimes there are dependencies The phenomenon of incompleteness.

I hope you still use the new version so that you can enjoy the latest features and optimizations.

**Comment by dennislblog** [comment]
I have tried that and it produced the same error. Perhaps the issue is specific to my system setup. Thank you for your time to investigate this problem.
