### ISSUE TITLE
是否支持默认主题的 "上 / 下一篇链接"

### ISSUE THREAD

**Issue by sammyne** [vuepress-reco/vuepress-theme-reco#291]
## Feature request

请问该很好看的主题支持和默认主题类似的 [上 / 下一篇链接] 功能么~

我设置了 .vuepress/config.js 中的 `module.exports.themeConfig.nextLinks` 为 `true` 没有生效~ 求解

#### What problem does this feature solve?
支持和默认主题类似的 [上 / 下一篇链接]。

#### Are you willing to work on this yourself?

[上 / 下一篇链接]: https://www.vuepress.cn/theme/default-theme-config.html#%E4%B8%8A-%E4%B8%8B%E4%B8%80%E7%AF%87%E9%93%BE%E6%8E%A5

**Comment by recoluan** [comment]
自定义侧边栏是支持上下篇的，博客不支持。

**Comment by sammyne** [comment]
好的，感激~
