### ISSUE TITLE
可以加入时间线功能

### ISSUE THREAD

**Issue by jack200111** [vuepress-reco/vuepress-theme-reco#292]
希望可以加入时间线功能

**Comment by recoluan** [comment]
> 希望可以加入时间线功能

已经有了，可以去官网的内置页面里找一下

**Comment by recoluan** [comment]
> 希望可以加入时间线功能

已经有了，可以去官网的内置页面里找一下

**Comment by jack200111** [comment]
已解决：https://theme-reco.vuejs.press/docs/theme/builtin-page.html

**Comment by JJJJerry** [comment]
时间线顺序能否更改，能否改成从最近到以前这种顺序？

**Comment by recoluan** [comment]
最近没有时间处理，你有时间的话可以提一下 pr
