### ISSUE TITLE
Translate to spanish

### ISSUE THREAD

**Issue by joseluisgs** [vuepress-reco/vuepress-theme-reco#293]
## Feature request
Translate to spanish

#### What problem does this feature solve?
Spanish language

#### How should this be implemented in your opinion?
Yes, I can help in it

#### Are you willing to work on this yourself?
yes. Please, let me how I can help you!

**Comment by recoluan** [comment]
Thank you very much for your support and contribution. You can add the corresponding translation file to the following address, and then export it to index.js.

https://github.com/vuepress-reco/vuepress-theme-reco/tree/master/packages/vuepress-theme-reco/locales

**Comment by joseluisgs** [comment]
export default {
  homeBlog: {
    article: 'Artículos',
    tag: 'Etiquetas',
    category: 'Categorías',
    friendLink: 'Páginas amigas'
  },
  tag: {
    all: 'Todas'
  }
}

I didn't made a pull request, because I add the file, but dosn't works, folliwing https://vuepress-theme-reco.recoluan.com/en/views/1.x/local.html. 
But if I change en.js file works fine.

Thank you again

**Comment by joseluisgs** [comment]
Ok, I need to change mixins locale too. I will test, but That is the traslation. Do you need more?
Do you need a pull request and the index file to and mixins?

**Comment by joseluisgs** [comment]
Also It is important to change Timeline message
And navbar categories and tags text.

**Comment by recoluan** [comment]
Sorry to reply to you so late, I have been focusing on the upcoming baby recently, and I have no energy to invest in development for the time being.

In fact, I very much agree with your suggestions and hope you can contribute code.

You can pull request and the index file to and mixins. And if you can, you can try to change Timeline message and navbar categories and tags text.

If you have limited time, you can only contribute to the changes you can. I will follow your suggestions to improve the localization function later. Thank you very much.

**Comment by joseluisgs** [comment]
Thank you very much and congratulations :)

I will try to help you as much as possible.

Again I wish you much happiness with your family.
