### ISSUE TITLE
2.0 版本 使用 viteBundler 后   评论功能无法初始化， Valine 报错

### ISSUE THREAD

**Issue by xStrayx** [vuepress-reco/vuepress-theme-reco#295]
## 问题
使用 viteBundler 本地运行的时候，开启 valine 功能后，控制台报错，无评论功能， 配置不变换为 webpackBundler 后，可正常显示评论模块
![](https://gcore.jsdelivr.net/gh/xStrayx/oss_img/img/20240730%2F8ce3bcb1987ce196e1148730fac90c98.png)

 
## 安装版本
```
  "dependencies": {
    "@vuepress/bundler-vite": "2.0.0-rc.13",
    "@vuepress/bundler-webpack": "2.0.0-rc.13",
    "vue": "^3.4.27",
    "vuepress": "2.0.0-rc.13",
    "vuepress-theme-reco": "2.0.0-rc.16"
  },
```

## 配置
```
export default defineUserConfig({
  title: "Demo",
  description: "",
  // bundler: webpackBundler(),
  bundler: viteBundler(),
 theme: recoTheme({
    style: "@vuepress-reco/style-default",
    logo: "/logo.png",
    author: "test",
    authorAvatar: "/head.png",
    docsRepo: "https://github.com/vuepress-reco/vuepress-theme-reco-next",
    docsBranch: "main",
    lastUpdatedText: "",
    navbar: [
      { text: "首页", link: "/" },
    ],
    commentConfig: {
      type: 'valine',
      options: {
        appId: '****',
        appKey: '*****',
        // placeholder: '填写邮箱可以收到回复提醒哦！',
        // verify: true, // 验证码服务
        // notify: true,
        // recordIP: true,
        // hideComments: true // 隐藏评论
      },
    },
  }),
});
```

**Comment by Luqir** [comment]
我也遇到了这个问题，编辑器直接就报错了：对象字面量只能指定已知属性，并且“commentConfig”不在类型“RecoThemeData”中。ts(2353)

**Comment by recoluan** [comment]
> 我也遇到了这个问题，编辑器直接就报错了：对象字面量只能指定已知属性，并且“commentConfig”不在类型“RecoThemeData”中。ts(2353)

ts 我完善一下

**Comment by recoluan** [comment]
> ## 问题
> 使用 viteBundler 本地运行的时候，开启 valine 功能后，控制台报错，无评论功能， 配置不变换为 webpackBundler 后，可正常显示评论模块 ![](https://camo.githubusercontent.com/0387154d0a91bdb89db8e6817436630c010d93cd583552d47b13172a3db0d92e/68747470733a2f2f67636f72652e6a7364656c6976722e6e65742f67682f785374726179782f6f73735f696d672f696d672f323032343037333025324638636533626362313938376365313936653131343837333066616339306339382e706e67)
> 
> ## 安装版本
> ```
>   "dependencies": {
>     "@vuepress/bundler-vite": "2.0.0-rc.13",
>     "@vuepress/bundler-webpack": "2.0.0-rc.13",
>     "vue": "^3.4.27",
>     "vuepress": "2.0.0-rc.13",
>     "vuepress-theme-reco": "2.0.0-rc.16"
>   },
> ```
> 
> ## 配置
> ```
> export default defineUserConfig({
>   title: "Demo",
>   description: "",
>   // bundler: webpackBundler(),
>   bundler: viteBundler(),
>  theme: recoTheme({
>     style: "@vuepress-reco/style-default",
>     logo: "/logo.png",
>     author: "test",
>     authorAvatar: "/head.png",
>     docsRepo: "https://github.com/vuepress-reco/vuepress-theme-reco-next",
>     docsBranch: "main",
>     lastUpdatedText: "",
>     navbar: [
>       { text: "首页", link: "/" },
>     ],
>     commentConfig: {
>       type: 'valine',
>       options: {
>         appId: '****',
>         appKey: '*****',
>         // placeholder: '填写邮箱可以收到回复提醒哦！',
>         // verify: true, // 验证码服务
>         // notify: true,
>         // recordIP: true,
>         // hideComments: true // 隐藏评论
>       },
>     },
>   }),
> });
> ```

报错点进去看一下，贴图具体是哪行代码报错呢？

我本地始终没有复现呢，代码可以发我邮箱看一下吗？recoluan@qq.com

**Comment by recoluan** [comment]
问题复现了，尽快解决

**Comment by recoluan** [comment]
问题复现了，尽快解决

**Comment by recoluan** [comment]
@xStrayx @Luqir 升级 2.0.0-rc.18 试一下

**Comment by suiyang1714** [comment]
`{
  "name": "vuepress-theme-reco-demo",
  "version": "2.0.0",
  "description": "Demo for vuepress-theme-reco@2.x.",
  "repository": "git@github.com:recoluan/vuepress-theme-reco-demo.git",
  "author": "reco_luan <recoluan@outlook.com>",
  "license": "MIT",
  "scripts": {
    "dev": "vuepress dev .",
    "start": "vuepress dev .",
    "build": "vuepress build ."
  },
  "dependencies": {
    "vue": "^3.5.0",
    "vuepress": "2.0.0-rc.18",
    "vuepress-theme-reco": "2.0.0-rc.25",
    "@vuepress/bundler-vite": "2.0.0-rc.18",
    "@vuepress/bundler-webpack": "2.0.0-rc.18"
  }
}
`

目前还是报错
