### ISSUE TITLE
Last Updated: Invalid Date

### ISSUE THREAD

**Issue by vervin** [vuepress-reco/vuepress-theme-reco#295]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?

how to fixed it, my page end with "Last Updated: Invalid Date"!

#### Other relevant information

- Your OS:  win 10
- Node.js version: 12.16.3
- VuePress version: 1.8.0
- VuePress-theme-reco version: 1.6.1
- Which package manager did you use for the install(npm/cnpm/yarn)? yarn

**Comment by joseluisgs** [comment]
Hi, ¿language? For me it works:
In Page.vue, try:
lastUpdated () {
      return this.$page.lastUpdated
      // return new Date(this.$page.lastUpdated).toLocaleString()
    },

**Comment by recoluan** [comment]
@vervin @joseluisgs 

What is your lang configuration?

**Comment by pythonsir** [comment]
lastUpdated: 'Last Updated',  同样的问题，不显示时间

**Comment by somenzz** [comment]
设置这个 `lang: 'zh-CN'` 就会出现 Last Updated: Invalid Date。望作者早日修复。

**Comment by recoluan** [comment]
将在 `1.6.2` 修复。
