### ISSUE TITLE
服务器部署不显示文件夹目录

### ISSUE THREAD

**Issue by mytcs** [vuepress-reco/vuepress-theme-reco#296]
你好！
我想请问一下在本地运行可以正常显示文件夹目录，但是部署到了服务器之后无法正常显示目录，这个是什么原因呢？
![服务器运行](https://github.com/user-attachments/assets/4e9a37e5-48c5-44ad-8ecb-dae685784c1a)

![本地运行](https://github.com/user-attachments/assets/f288b7a8-74cd-4987-879f-8c6795dad2ea)

- Your OS: 
- Node.js version: 
- VuePress version: 
- VuePress-theme-reco version: 
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?

**Comment by recoluan** [comment]
你的文件名是不是中文啊
