### ISSUE TITLE
Markdown Whether to add dimension and alignment configuration to the image

### ISSUE THREAD

**Issue by zxwin0125** [vuepress-reco/vuepress-theme-reco#298]
Markdown 图片中可以加个尺寸大小和对齐方式的配置，类似 CSDN 中的那样

1. 在图片链接地址后添加形如=600x600的数字，即可调整图片大小
2. 在图片链接地址后面添加指令#pic_center，即可居中对齐

目前可以直接在外层包img标签自定义实现，但是如果能支持类似这样的简单配置的话，就更好啦

**Comment by recoluan** [comment]
这个插件可以满足你的要求：https://ecosystem.vuejs.press/zh/plugins/markdown/markdown-image.html
