### ISSUE TITLE
正文中会显示一级标题

### ISSUE THREAD

**Issue by fullstack-zhangpeng** [vuepress-reco/vuepress-theme-reco#298]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?
正文中包含一级标题

#### Other relevant information
![image](https://user-images.githubusercontent.com/39549827/105043618-b4d42000-5aa0-11eb-84d4-6a91891a1380.png)

- Your OS: macOS
- Node.js version: v15.4.0
- VuePress version: ^1.7.0
- VuePress-theme-reco version: ^1.5.7
- Which package manager did you use for the install(npm/cnpm/yarn)? yarn

**Comment by recoluan** [comment]
你的使用场景是什么样的，导致出现这个问题。

**Comment by fullstack-zhangpeng** [comment]
> 你的使用场景是什么样的，导致出现这个问题。

就是一个普通的markdown

**Comment by BoBoooooo** [comment]
一样遇到了这个问题
先全部隐藏了..

.page-title{
  display:none !important;
}

**Comment by recoluan** [comment]
暂时参考 @BoBoooooo 的解决方案吧，`vuepress` 处理 title 的方式改变了。
