### ISSUE TITLE
俩边侧边栏位置建议

### ISSUE THREAD

**Issue by LiJunYi2** [vuepress-reco/vuepress-theme-reco#300]
如图所示，左右侧边栏感觉还可以往边缘挪一点，这样中间文章部分的位置会相对多一点，看上去会好一点。

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/b7f93b9e-a827-4eae-9fda-60cf44457ae0">
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/378c5c2f-9c2d-46af-9870-c4188ffe8921">

**Comment by recoluan** [comment]
已调整
