### ISSUE TITLE
Wrong creation date

### ISSUE THREAD

**Issue by OSDVF** [vuepress-reco/vuepress-theme-reco#302]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?
In the component PageInfo.vue the method formatDateValue(value) returns only the number of current day in the month. This happens when the user is in locale where they use the DD. MM. YYYY date format.

#### Other relevant information

- Your OS: Windows 10
- Node.js version: v10.16.0
- VuePress version: 
- VuePress-theme-reco version: 1.6.1
- Which package manager did you use for the install(npm/cnpm/yarn)? npm

**Comment by recoluan** [comment]
You can try the string format, just like:
```yaml
title: 'test'
date: '2021-01-25 03:00:00'
```
