### ISSUE TITLE
当使用plugins配置valine时，阅读量无法正常显示

### ISSUE THREAD

**Issue by irvingzhang0512** [vuepress-reco/vuepress-theme-reco#303]
如题，当使用plugins配置valine时，评论可以正常显示，但阅读量无法正常显示。

如果使用themeConfig配置valine则无该问题。

**Comment by recoluan** [comment]
是不是你配置 valine 的方式不正确，因为主题已经内置，是无需配置 plugin 的，你是具体怎么配置的呢？请详细描述一下。

**Comment by irvingzhang0512** [comment]
plugin形式的配置如下
```js

['@vuepress-reco/comments',
{
  solution: 'valine',
  options: {
    appId: 'xxx',
    appKey: 'xxx',
  }
}]
```

另外，这个问题不只是我碰到。在2群问了这个问题（valine配置好后评论可用、阅读量不可用）后，有大佬回复说让我用themeConfig配置而不是plugins配置，他也碰到过一样的问题。

**Comment by recoluan** [comment]
那位同学说的没问题，在 `themeConfig` 里配置，见 [文档](https://vuepress-theme-reco.recoluan.com/views/1.x/valine.html)。
