### ISSUE TITLE
代码高亮没生效

### ISSUE THREAD

**Issue by WChangfei** [vuepress-reco/vuepress-theme-reco#303]
大佬，代码高亮功能好像支持出问题啦，之前用的2.0.bata版本，现在升级到rc了。

  "dependencies": {
    "@vuepress/bundler-vite": "^2.0.0-rc.14",
    "@vuepress/plugin-git": "^2.0.0-rc.37",
    "@vuepress/plugin-search": "^2.0.0-rc.37",
    "@vuepress/utils": "^2.0.0-rc.14",
    "element-plus": "^2.3.14",
    "vuepress": "^2.0.0-rc.14",
    "vuepress-plugin-md-enhance": "^2.0.0-rc.52",
    "vuepress-theme-reco": "^2.0.0-rc.19"
  }

**Comment by recoluan** [comment]
我这边没有复现，可以提供代码吗
