### ISSUE TITLE
一级标题会默认隐藏 The first level title will be hidden

### ISSUE THREAD

**Issue by iyuzhang** [vuepress-reco/vuepress-theme-reco#307]
I'm not sure if something is wrong, the default primary title of markdown is always hidden by a style

我不清楚是否是哪里不对，markdown的默认一级标题总是会被一个.theme-container .theme-reco-md-content h1 的样式给隐藏掉。

---

![屏幕截图 2024-10-08 211335](https://github.com/user-attachments/assets/dc8d6bc2-e2ef-4a73-a366-4497f66b9bf9)
![屏幕截图 2024-10-08 214723](https://github.com/user-attachments/assets/cd690ed2-d489-4ec5-9856-5a39a0789fdb)

**Comment by recoluan** [comment]
主题是这样设计的，文档的标题就是一级标题，文档的正文应该从二级标题开始。
