### ISSUE TITLE
侧边栏折叠有问题

### ISSUE THREAD

**Issue by xuoutput** [vuepress-reco/vuepress-theme-reco#309]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
都添加
collapsable: true
但第一个都会展开

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version: 
- VuePress-theme-reco version: 
- Which package manager did you use for the install(npm/cnpm/yarn)?

**Comment by recoluan** [comment]
这样是正确的，因为需要有默认值啊
