### ISSUE TITLE
How to register custom components 

### ISSUE THREAD

**Issue by gongxuanzhang** [vuepress-reco/vuepress-theme-reco#310]
I am using 2.0.0-rc.22(the latest version).
I want to register a custom components like the [document](https://theme-reco.vuejs.press/docs/theme/frontmatter-home.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A6%96%E9%A1%B5%E6%A8%A1%E5%9D%97).
However, the link to the register component provided in the documentation does not exist.

I'm not a front-end engineer, so please forgive me if I mention something offensive 💗

**Comment by recoluan** [comment]
Sorry, the location of the document has changed.

You need to place the components you want to register in `.vuepress/components`.

- Document: https://theme-reco.vuejs.press/docs/guide/register-components.html
- Example: https://github.com/vuepress-reco/vuepress-theme-reco/blob/main/docs/.vuepress/components/CustomBanner.vue

**Comment by gongxuanzhang** [comment]
Thanks a lot
