### ISSUE TITLE
无法关闭 lastUpdated

### ISSUE THREAD

**Issue by xuoutput** [vuepress-reco/vuepress-theme-reco#311]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?

无法设置也无法关闭 lastUpdated

```
  themeConfig: {
    lastUpdated: false,
```
![image](https://user-images.githubusercontent.com/16385443/106377400-ae667200-63d7-11eb-965b-aab863962571.png)

使用 vuepress 的方式也不行

https://vuepress.vuejs.org/zh/plugin/official/plugin-last-updated.html#%E9%80%89%E9%A1%B9

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version: 
- VuePress-theme-reco version: 
- Which package manager did you use for the install(npm/cnpm/yarn)?

**Comment by lgdl** [comment]
在node_modules\vuepress-theme-reco\components目录下Page.vue
