### ISSUE TITLE
1.6.5版本打包出现错误提示 语法错误

### ISSUE THREAD

**Issue by nshusr** [vuepress-reco/vuepress-theme-reco#315]
- [ x ] I confirm that this is an issue rather than a question.

#### What is actually happening?
```
TypeError: Cannot read property 'noFoundPageByTencent' of undefined
    at Vue.<anonymous> (node_modules/vuepress-theme-reco/layouts/404.vue:25:35)
```
and
```
[Vue warn]: Error in render: "TypeError: Cannot read property 'themeConfig' of undefined"

found in

---> <Common>
       <Anonymous>
         <GlobalLayout>
           <Root>
```
#### Other relevant information

- Your OS: 
- Node.js version: 15.8.0
- VuePress version: 1.8.1
- VuePress-theme-reco version: 1.6.5
- Which package manager did you use for the install(npm/cnpm/yarn)? npm/pnpm

**Comment by gerryge** [comment]
类似的错误：
![image](https://user-images.githubusercontent.com/6952917/108346817-c1bc6e80-721a-11eb-859b-2dcca33b41cc.png)
![Uploading image.png…]()

**Comment by zjgyb** [comment]
我也碰到了相同的问题。

我看了代码发现在`v1.6.2`的时候获取实例的方法从`ctx.root`改为`getCurrentInstance()`，比如在文件[common.vue](https://github.com/vuepress-reco/vuepress-theme-reco/blob/master/packages/vuepress-theme-reco/components/Common.vue#L77)中，使用该方法得到的实例不能获取到`$themeConfig`、`$site`等参数，因此控制台报`themeConfig undefined`问题。

**Comment by opamine** [comment]
> 
> 
> 我也碰到了相同的问题。
> 
> 我看了代码发现在`v1.6.2`的时候获取实例的方法从`ctx.root`改为`getCurrentInstance()`，比如在文件[common.vue](https://github.com/vuepress-reco/vuepress-theme-reco/blob/master/packages/vuepress-theme-reco/components/Common.vue#L77)中，使用该方法得到的实例不能获取到`$themeConfig`、`$site`等参数，因此控制台报`themeConfig undefined`问题。

@recoluan

**Comment by recoluan** [comment]
应该是 `@vue/composition-api` 导致的问题，但是目前还没有找到一个好的解决方案，大家如果有好的方法，及时在这里同步一下。

**Comment by nshusr** [comment]
还好我没上vue-demi，用过@composition-api遇到个时间就即时退了，或许能不能直接上vue3？vuepress-next，别用vue-demi

**Comment by LiDengHui** [comment]
https://github.com/vuejs/composition-api/blob/master/CHANGELOG.md

# 1.0.0-beta.22 (2020-12-19)
## Features
getCurrentInstance: Aligning with vue3 (#520) (1495a46)
## BREAKING CHANGES
getCurrentInstance: The internal vm can be accessed with getCurrentInstance().proxy
```js
const vm = getCurrentInstance()

// becomes

const vm = getCurrentInstance().proxy
```

**Comment by recoluan** [comment]
> 还好我没上vue-demi，用过@composition-api遇到个问题就即时退了，或许能不能直接上vue3？vuepress-next，别用vue-demi

使用 @vue/composition-api 就是为了到时候快速适配 vuepress-next，但是后来跟 vuepress 目前的负责人了解到，next 可能会更改主题系统，改回 0.x 的样子，主题适配难度增大，所以暂时观望，并且 vuepress 已经被 Vue 团队放弃，主题转 vitepress 的可能性比较大。

**Comment by recoluan** [comment]
> https://github.com/vuejs/composition-api/blob/master/CHANGELOG.md
> 
> 
> 
> # 1.0.0-beta.22 (2020-12-19)
> 
> ## Features
> 
> getCurrentInstance: Aligning with vue3 (#520) (1495a46)
> 
> ## BREAKING CHANGES
> 
> getCurrentInstance: The internal vm can be accessed with getCurrentInstance().proxy
> 
> ```js
> 
> const vm = getCurrentInstance()
> 
> 
> 
> // becomes
> 
> 
> 
> const vm = getCurrentInstance().proxy
> 
> ```

我这两天也在本地通过 .proxy 进行优化，但是发现仍有两个问题：

1. 某些实例属性仍然没有，比如 $router；
2. instance 在 setup 函数中仍有 undefined 的情况，导致深层属性找不到而报错。
