### ISSUE TITLE
Why isn't the auto-registration component working? None of the icons are showing up.

### ISSUE THREAD

**Issue by junjiantech** [vuepress-reco/vuepress-theme-reco#316]
## Bug report
![image](https://github.com/user-attachments/assets/1f08f378-60b6-44b3-a9a9-7329d3032bc6)

#### What is actually happening?
None of the icons are showing up.

#### Other relevant information

- Your OS: Windows
- Node.js version: v18.20.4
- VuePress version: 2.0.0-rc.18
- VuePress-theme-reco version: 2.0.0-rc.23
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? npm

**Comment by recoluan** [comment]
Icon components should be registered in `vuepress/components`.
