### ISSUE TITLE
reco主题首页关闭navbar后，博客栏box-shadow消失

### ISSUE THREAD

**Issue by MrHanson** [vuepress-reco/vuepress-theme-reco#317]
- [x] I confirm that this is an issue rather than a question.

#### Other relevant information，

- Your OS: window10
- Node.js version: 12.16.1
- VuePress version: 1.7.1
- VuePress-theme-reco version: 1.6.1
- Which package manager did you use for the install(npm/cnpm/yarn)? npm

**Comment by recoluan** [comment]
- [x] 已确认：首页设置 `front-matter` 的 navbar 为 false， `home-blog` 下的元素 box-shadow 消失；
- [ ] 待确认：`bgImageStyle` 高度设置为 `100vh` 时，`home-blog` 下的元素 box-shadow 消失，同时顶部仍留有 navbar 的 margin，导致 `bgImage` 服务无法覆盖全屏。（**请升级至最新版本测试后补充说明，谢谢。**）

**Comment by MrHanson** [comment]
> * [x]  已确认：首页设置 `front-matter` 的 navbar 为 false， `home-blog` 下的元素 box-shadow 消失；
> * [ ]  待确认：`bgImageStyle` 高度设置为 `100vh` 时，`home-blog` 下的元素 box-shadow 消失，同时顶部仍留有 navbar 的 margin，导致 `bgImage` 服务无法覆盖全屏。（**请升级至最新版本测试后补充说明，谢谢。**）

升级后1.6.5 后遇到 https://github.com/vuepress-reco/vuepress-theme-reco/issues/315#issuecomment-781260114 同样的问题了。。

**Comment by recoluan** [comment]
可以关注一下主题 2.0，1.0 后期将不再维护。

http://v2.vuepress-reco.recoluan.com/
