### ISSUE TITLE
2.0中不能用vuepress自带的Badge组件了

### ISSUE THREAD

**Issue by Louis-XIV** [vuepress-reco/vuepress-theme-reco#317]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?
在1.x中可以使用类似`<Badge type="tip" text="SpringBoot2" />`的组件
在2.0中build会报错
[vite] Internal server error: Illegal '/' in tags.

#### Other relevant information

- Your OS: Win10
- Node.js version: 
- VuePress version: 2.0.0-rc.18
- VuePress-theme-reco version: 2.0.0-rc.25
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?  npm

**Comment by recoluan** [comment]
我测试没问题啊

**Comment by Louis-XIV** [comment]
> 我测试没问题啊

再测了一下，是用在提示的标题上会报错，例如
```
:::tip <Badge type="tip" text="SpringBoot2" />
一段提示
:::
```
这种语法在1.x是支持的

**Comment by recoluan** [comment]
应该是vuepress的问题了，可以去2.0下面提issue
