### ISSUE TITLE
prism-tomorrow.css 的请求时间过长导致加载速度变慢

### ISSUE THREAD

**Issue by Restent** [vuepress-reco/vuepress-theme-reco#318]
- [x] I confirm that this is an issue rather than a question.

## Bug report

站点加载时间需要 41s

查询 F12 Network 发现一个名为 prism-tomorrow.css 的文件 (https://prismjs.com/themes/prism-tomorrow.css) 请求错误。

这一个请求先是 Pending 然后直接 FAILED，原因是 Timed Out，直接访问也是“响应时间过长”。

(F12 Console 也仅仅提示该 CSS 文件请求时间过长)

#### What is actually happening?

与上面一致

#### Other relevant information

似乎您个人的博客也出现了这个报错。

- Your OS: Windows 10 Enterprise LTSC
- Node.js version: 14.15.5
- VuePress version: 1.8.0
- VuePress-theme-reco version: 1.6.1
- Which package manager did you use for the install(npm/cnpm/yarn)? npm

**Comment by recoluan** [comment]
这个与个人网络以及该 cdn 的稳定性有关，但是也确实是一个问题，我先记录一下。

**Comment by recoluan** [comment]
已经移除了该cdn。可以关注一下主题 2.0，1.0 后期将不再维护。

http://v2.vuepress-reco.recoluan.com/
