### ISSUE TITLE
支持vuepress-next

### ISSUE THREAD

**Issue by ZHXDiDa** [vuepress-reco/vuepress-theme-reco#321]

**Comment by rexwangcc** [comment]
or maybe `vitepress` as it's also getting actively developed.

**Comment by recoluan** [comment]
主题代码最近在使用 composition API 重构就是为了适配 `vuepress-next`，并且 `vitepress` 未来应该也会适配，毕竟 Vue 团队已经放弃 vuepress 了。

但是因为个人时间问题，进展都比较缓慢，但是请放心，一定都会支持的。

**Comment by waycowei** [comment]
> VitePress is not compatible with the current VuePress ecosystem (mostly themes and plugins). The overall idea is that VitePress will have a drastically more minimal theming API (preferring JavaScript APIs instead of file layout conventions) and likely no plugins (all customization is done in themes).

VitePress 大概率不会有插件系统，现在越来越多人转 Vue 3.x，`vuepress-next` 适配要抓紧啦
