### ISSUE TITLE
VueRuter 读取自定义标签后，因为是中文所以有错误信息

### ISSUE THREAD

**Issue by nshusr** [vuepress-reco/vuepress-theme-reco#322]
- [ x] I confirm that this is an issue rather than a question.
![image](https://user-images.githubusercontent.com/45023042/109299000-5f451d00-786f-11eb-9138-1c17a71d74f1.png)

- Your OS: 
- Node.js version: 14.15.1
- VuePress version: 1.8.2
- VuePress-theme-reco version: 1.6.6-alpha.0
- Which package manager did you use for the install(npm/cnpm/yarn)? pnpm

**Comment by recoluan** [comment]
无法编码会导致页面 404，但是已经解决这个 bug 了，所以暂时不用理会这些 warning 提示了
