### ISSUE TITLE
date显示错误

### ISSUE THREAD

**Issue by laobg** [vuepress-reco/vuepress-theme-reco#326]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
 front matter 中日期如果这样写
``date: '2021-03-02'``
日期会显示为
``2021/3/1``
会少一天

#### Other relevant information

- Your OS: 
- Node.js version: 14.16.0
- VuePress version: 1.8.0
- VuePress-theme-reco version: 1.6.6-alpha.0
- Which package manager did you use for the install(npm/cnpm/yarn)?npm

**Comment by recoluan** [comment]
可以关注一下主题 2.0，1.0 后期将不再维护。

http://v2.vuepress-reco.recoluan.com/
