### ISSUE TITLE
本地正常，服务器出现错误，卡在加载页

### ISSUE THREAD

**Issue by JayeZhu** [vuepress-reco/vuepress-theme-reco#328]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
报错：
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method
重新build，还是一样
#### Other relevant information

- Your OS: WIN10
- Node.js version: 12.16.1
- VuePress version: 1.5.4
- VuePress-theme-reco version: 1.5.7
- Which package manager did you use for the install(npm/cnpm/yarn)? yarn

**Comment by WangScaler** [comment]
我之前也出现过，重新build之后没出现。之前看vuepress也有问这个问题的。

**Comment by JayeZhu** [comment]
> 我之前也出现过，重新build之后没出现。之前看vuepress也有问这个问题的。
嗯嗯，在 vuepress 中看过，之前博客发布到 github.io，昨天转移到自己域名下就没问题了

**Comment by recoluan** [comment]
这个问题经常出现，我也出现过，暂时还不清楚解决方案，更换一下 vuepress 版本试一下。

**Comment by JayeZhu** [comment]
> 这个问题经常出现，我也出现过，暂时还不清楚解决方案，更换一下 vuepress 版本试一下。

好的，谢谢作者

**Comment by w2252218951** [comment]
主页设置为空貌似就好了

**Comment by weihang-wills** [comment]
同出现这个问题。
然后重新装了一下vuepress，把文章不要分文件夹，全部放一起。然后重新build，成功了。不知道是哪个步骤导致成功的。
所以，期望vuepress大神能够修复这个问题

**Comment by recoluan** [comment]
可以关注一下主题 2.0，1.0 后期将不再维护。

http://v2.vuepress-reco.recoluan.com/
