### ISSUE TITLE
首页文章标签点击跳转404

### ISSUE THREAD

**Issue by llorz-o** [vuepress-reco/vuepress-theme-reco#33]
标签点击后使用search进行跳转导致github上为 404
https://mrzhoulichao.github.io/tag/?tag=%E5%90%8E%E7%AB%AF

**Comment by recoluan** [comment]
“使用search进行跳转”是什么意思啊？

我看到你的项目本身就是404啊

**Comment by llorz-o** [comment]
我换了，如果git pages 是个人主页的page将不会产生这个问题，但是如果是 项目仓库 的 page 路径将是 github.io/repository_name/ 这样的路径，而标签在跳转时却指向了 github.io/?tag=tagname 这样的路径导致了我的 404 错误，也就是说如果不是直接部署在根域名上 tag 产生了 404 。

配置文件中的 `base`也设置过了，但是没有作用。

我现在的域名为 [https://llorz-o.github.io/](https://llorz-o.github.io/) 这个问题也就不存在了

**Comment by recoluan** [comment]
我看了一下，你目前用的是旧版本，如果项目不在根目录下，确实存在跳转的bug，目前最新的版本中已经修复这个bug了，你可以升级到 `1.0.4`。

**Comment by llorz-o** [comment]
tks

**Comment by llorz-o** [comment]
tks
已经部署到github主页仓库了，但是这个问题却可以帮助到别人。

reco_luan <notifications@github.com> 于2019年8月15日周四 下午1:05写道：

**Comment by recoluan** [comment]
是的，没错^_^
