### ISSUE TITLE
一个路由 bug

### ISSUE THREAD

**Issue by Hezon** [vuepress-reco/vuepress-theme-reco#331]
问题描述：
点击含有中文的 Category 或 Tag，再点击某篇文章，进去文章详情页后，点浏览器返回按钮，页面出现 404

**Comment by recoluan** [comment]
你的主题版本是多少呢？

**Comment by ATQQ** [comment]
一个简单的解决方案：https://github.com/vuepress-reco/vuepress-theme-reco/issues/395#issuecomment-1019087787

**Comment by recoluan** [comment]
可以关注一下主题 2.0，1.0 后期将不再维护。

http://v2.vuepress-reco.recoluan.com/
