### ISSUE TITLE
你的案例页面是配置还是自定义开发的

### ISSUE THREAD

**Issue by yexiaodong** [vuepress-reco/vuepress-theme-reco#332]
https://vuepress-theme-reco.recoluan.com/views/other/theme-example.html

**Comment by recoluan** [comment]
是自己开发的 vue 组件，然后在markdown 文件里直接使用。

**Comment by yexiaodong** [comment]
使用了自己的vue组件后，头部消失了。希望vue组件只替换中间内容区，头部和脚部保留应该怎样配置

**Comment by recoluan** [comment]
可以关注一下主题 2.0，1.0 后期将不再维护。

http://v2.vuepress-reco.recoluan.com/
