### ISSUE TITLE
没有日期的页面也显示在了首页

### ISSUE THREAD

**Issue by ty-peng** [vuepress-reco/vuepress-theme-reco#333]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?
以前没有日期的页面不会显示在首页，现在好像也没有选项设置是否显示在首页

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version: 
- VuePress-theme-reco version: 1.6.6
- Which package manager did you use for the install(npm/cnpm/yarn)?yarn

**Comment by recoluan** [comment]
在 frontmatter 设置一下 `publish: false` 。

**Comment by recoluan** [comment]
可以关注一下主题 2.0，1.0 后期将不再维护。

http://v2.vuepress-reco.recoluan.com/
