### ISSUE TITLE
出现这种错误 Duplicate keys detected

### ISSUE THREAD

**Issue by 183908201026** [vuepress-reco/vuepress-theme-reco#334]
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620 [Vue warn]: Duplicate keys detected: 'https://www.iconfont.cn'. This may cause an update error.

 <DropdownLink> at node_modules/vuepress-theme-reco/components/DropdownLink.vue
       <NavLinks> at node_modules/vuepress-theme-reco/components/NavLinks.vue
         <Navbar> at node_modules/vuepress-theme-reco/components/Navbar.vue
           <Common> at node_modules/vuepress-theme-reco/components/Common.vue
             <Layout> at node_modules/vuepress-theme-reco/layouts/Layout.vue
               <GlobalLayout> at node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue
                 <Root>
应该怎么解决？

**Comment by wencwcoder** [comment]
@183908201026 这就是提示有部分的 key 是相同的，你检查一下哪里有用到，key 应该是唯一标识符。

**Comment by snowinszu** [comment]
我也出现这样的问题

**Comment by PabloRN** [comment]
Same here

**Comment by recoluan** [comment]
可以关注一下主题 2.0，1.0 后期将不再维护。

http://v2.vuepress-reco.recoluan.com/
