### ISSUE TITLE
请问文章怎么根据标题生成目录？

### ISSUE THREAD

**Issue by zhoufanglu** [vuepress-reco/vuepress-theme-reco#337]
请问文章怎么根据标题生成目录？ 有这个功能吗？

**Comment by zhoufanglu** [comment]
![1BZZN) CN Y79M83XNOJP](https://user-images.githubusercontent.com/24451091/112929236-964a6f00-914a-11eb-9c54-410df4663049.png)

类似这种文章的二级标题，能生成固定在左侧的目录吗？

**Comment by recoluan** [comment]
已经将文章标题生成的目录放在右边了，通过 subSidebar 开启，具体可以看文档。
