### ISSUE TITLE
vuepress-theme-reco升级到1.6.6使用md5给项目加密失败，还是识别为keys里面的字符串

### ISSUE THREAD

**Issue by HelenTim** [vuepress-reco/vuepress-theme-reco#338]
themeConfig: {
    // 密钥
    keyPage: {
      keys: ['32位的 md5 加密密文'], // 1.3.0 版本后需要设置为密文
      color: '#42b983', // 登录页动画球的颜色
      lineColor: '#42b983' // 登录页动画线的颜色
    }
  }
配置md5无效

**Comment by recoluan** [comment]
可以关注一下主题 2.0，1.0 后期将不再维护。

http://v2.vuepress-reco.recoluan.com/
