### ISSUE TITLE
ToC 更改设置不生效

### ISSUE THREAD

**Issue by chendifan** [vuepress-reco/vuepress-theme-reco#34]
原生 markdown.toc 的配置在我的项目中不生效

配置如下：
``` json
markdown: {
  lineNumbers: true,
  toc: {
    includeLevel: [1, 2, 3, 4, 5]
  }
},
```

期望：
五级 <h> 均生成 ToC

结果：
仅生成 2、3 两级

**Comment by recoluan** [comment]
你好，我试了一下，我这是可以的，你看看你的 `vuepress` 是什么版本。下面是我的尝试结果，我使用的是 `1.0.1` 版本：
![a](https://user-images.githubusercontent.com/18067907/63209719-32ab3380-c117-11e9-93ae-9dea0e56a121.png)

还有我个人的建议是，默认的 [2, 3] 是比较不错的，如果文档层级太深，会影响读者阅读的，当然这只是我的个人观点。

**Comment by chendifan** [comment]
额，我说的是侧边栏：
![image](https://user-images.githubusercontent.com/22953986/63209837-b7e31800-c118-11e9-82a9-607d1ecb4ae6.png)

**Comment by recoluan** [comment]
侧边栏只展示[2, 3]，是因为分得太多会显示得特别乱。
但是这个建议我先记录下来，后期是否会加上，取决于功能调研的反馈，感谢你的建议。
