### ISSUE TITLE
中文名字的 markdown 文件路由跳转会引起错误

### ISSUE THREAD

**Issue by Limsanity** [vuepress-reco/vuepress-theme-reco#340]
- [x] I confirm that this is an issue rather than a question.

## Bug report
中文名字的 markdown 文件路由跳转会引起 Maximum call stack size exceeded 错误。

#### What is actually happening?
markdown 文件包含中文名字，项目目录如下：
![image](https://user-images.githubusercontent.com/31369862/113562670-184e0280-9639-11eb-94ba-b3c24883b4ac.png)

点击页面 link 会出现 Maximum call stack size exceeded 报错：
![image](https://user-images.githubusercontent.com/31369862/113562824-5ea36180-9639-11eb-9015-c2fe17839637.png)

初步判断为 [fixRouterError404](https://github.com/vuepress-reco/vuepress-theme-reco/blob/master/packages/vuepress-theme-reco/helpers/other.js#L38) 导致，注释掉该函数则表现正常。

页面中 $router 的属性存在如下 redirect 信息，`fixRouterError404` 不停触发该 redirect，导致 `Maximum call stack size exceeded`

![image](https://user-images.githubusercontent.com/31369862/113563132-bfcb3500-9639-11eb-903a-ba52b5bd68c4.png)

[生成 vuepress routes 代码](https://github.com/vuejs/vuepress/blob/64e92ca6a1/packages/%40vuepress/core/lib/node/internal-plugins/routes.js#L31) 中似乎有对 encodeURIComponent 的处理

#### Other relevant information

- Your OS:  mac os v10.15.7
- Node.js version: v12.16.1
- VuePress version: v1.7.1
- VuePress-theme-reco version: v1.6.6
- Which package manager did you use for the install(npm/cnpm/yarn)? yarn

**Comment by wencwcoder** [comment]
@Limsanity 路由跳转是基于 vue-router 的嘛，可能是它对中文的支持有问题，还是用英文命名，减少 bug 触发。

**Comment by fenyuluoshang** [comment]
> @Limsanity 路由跳转是基于 vue-router 的嘛，可能是它对中文的支持有问题，还是用英文命名，减少 bug 触发。

但是已有升级代价就有点大了鸭

**Comment by wencwcoder** [comment]
@fenyuluoshang 这个文件名其实去看大部分博主都是用到日期命名的，因为最终在 vuepress 中显示的名字是根据 markdown 里面的 Front Matter  的 title 作为来源，和这个 xxx.md 的 xxx 没关系。

**Comment by qianzai** [comment]
主要是找md文件的时候，不用中文，就很难受

**Comment by qianzai** [comment]
哭了😭

**Comment by shirayner** [comment]
使用插件 `vuepress-plugin-permalink-pinyin` 可解决此问题，具体请参考 [基于VuePress和GitHub搭建个人博客站点](https://github.com/shirayner/snote/blob/master/docs/cs/backend/dev-tools/08_%E5%9F%BA%E4%BA%8EVuePress%E5%92%8CGitHub%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%E7%AB%99%E7%82%B9.md)

当文件名含有中文时，对应页面无法跳转，可通过如下插件解决这个问题，这个插件会将中文路径转换为拼音路径

本地安装：
```bash
npm install -D  vuepress-plugin-permalink-pinyin
```
然后配置插件：
```js
module.exports = {
  plugins: [
      // 支持中文文件名
      [
        "permalink-pinyin",
        {
          lowercase: true, // Converted into lowercase, default: true
          separator: "-", // Separator of the slug, default: '-'
        },
      ],
  ]
}
```

效果：
有如下中文文件

![image](https://user-images.githubusercontent.com/11574340/121691686-dd18f580-caf9-11eb-8a7d-f271bddad1c0.png)

会被插件转成拼音路径，访问如下地址
> [https://shirayner.github.io/snote/cs/backend/java/jvm/01_jvmhe-xin-zhi-shi-dian-tu-jie.html](https://shirayner.github.io/snote/cs/backend/java/jvm/01_jvmhe-xin-zhi-shi-dian-tu-jie.html)

会发现中文路径已经被转成拼音了

![image](https://user-images.githubusercontent.com/11574340/121691911-17829280-cafa-11eb-9e08-dd1e646a8338.png)

**Comment by AlanLee97** [comment]
牛逼，有用！！

**Comment by lyandut** [comment]
@shirayner 楼上太强了，mua~

**Comment by ATQQ** [comment]
一个相对简单解决方案：https://github.com/vuepress-reco/vuepress-theme-reco/issues/395#issuecomment-1019087787

**Comment by recoluan** [comment]
咱们可以关注一下主题 2.0，后期 1.0 将不再维护了。

http://v2.vuepress-reco.recoluan.com/
