### ISSUE TITLE
自定义博客列表的点击事件

### ISSUE THREAD

**Issue by yexiaodong** [vuepress-reco/vuepress-theme-reco#341]
点击博客列表时，部分文章直接跳转外链。能否通过配置实现，如果不能如何添加点击事件覆盖原来的点击事件

**Comment by recoluan** [comment]
主题是没有提供这个功能的，其他覆盖 click 时间的方法也没有。

建议：如果非常需要这个功能，建议将主题代码粘贴到本地改源码。

**Comment by recoluan** [comment]
可以关注一下主题 2.0，1.0 后期将不再维护。

http://v2.vuepress-reco.recoluan.com/
