### ISSUE TITLE
进入首页总是自动跳转到侧边栏的第一篇文章

### ISSUE THREAD

**Issue by Yanstory** [vuepress-reco/vuepress-theme-reco#343]
还原为默认主题后不存在这个问题，应该是主题的问题。

**Comment by recoluan** [comment]
我想你一定是在自定义侧边栏时，把首页路径放在了首位置。

**Comment by wencwcoder** [comment]
@Yanstory sidebar 的配置可能路径不太对。

**Comment by guohui666** [comment]
@recoluan 
```javascript
sidebar: [
            {
                title: 'ui相关',
                path: '/ui/',
                collapsable: false,
                children: [
                    '/ui/item-title-bar',
                ]
            },
            {
                title: 'utils',
                path: '/utils/',
                collapsable: false,
                sidebarDepth: 2,
                children: [
                    '/utils/dictConfig',
                ]
            },
        ]
```

大佬看下，我也是进首页直接跳到第一篇文章

**Comment by NatureK88** [comment]
@guohui666 config写错了

> ```js
> sidebar: [
>             {
>                 title: 'ui相关',
>                 path: '/ui/',
>                 collapsable: false,
>                 children: [
>                     '/ui/item-title-bar',
>                 ]
>             },
>             ...
> ```

应该写为：
```
sidebar: {
    '/ui/':[         
            'item-title-bar',
        ]   
},
...
```

**Comment by recoluan** [comment]
可以关注一下主题 2.0，1.0 后期将不再维护。

http://v2.vuepress-reco.recoluan.com/
