### ISSUE TITLE
侧边导航在页面未加载完成时显示有问题

### ISSUE THREAD

**Issue by yexiaodong** [vuepress-reco/vuepress-theme-reco#344]
加载中
![image](https://user-images.githubusercontent.com/13914749/114302416-7c6e3c00-9afb-11eb-8c57-8a13a90d7606.png)
加载完成
![image](https://user-images.githubusercontent.com/13914749/114302500-eb4b9500-9afb-11eb-82ae-a9d358bdd812.png)

重现地址：http://yexiaodong.gitee.io/blog/docs/favorite/

**Comment by wencwcoder** [comment]
@yexiaodong 检查一下 sidebar 的配置。

**Comment by yexiaodong** [comment]
"sidebar": {
      "/docs/favorite/": [
        "",
        "tools",
      ],
      "/docs/project/": [
        "",
        "PC",
        "ionic",
        "react",
      ],
    },
这配置没有什么问题啊

**Comment by vdbvxcbcb** [comment]
还没解决吗？我也遇到了同样的问题，有点郁闷，vuepress-theme-reco 版本为 1.6.1

**Comment by vdbvxcbcb** [comment]
还没解决吗？在首次加载时我也会遇到同样的问题，点击刷新后加载效果是正常的，vuepress-theme-reco 版本为 1.6.1

**Comment by recoluan** [comment]
这个问题暂时没有找到解决方案，咱们可以关注一下主题 2.0，后期 1.0 将不再维护了。

http://v2.vuepress-reco.recoluan.com/

**Comment by vdbvxcbcb** [comment]
把 vuepress-theme-reco 版本降到 1.57 就好了
