### ISSUE TITLE
开启绝对加密后密码输入页面 Layout 错误

### ISSUE THREAD

**Issue by OrvilleQ** [vuepress-reco/vuepress-theme-reco#347]
![image](https://user-images.githubusercontent.com/21377465/114460777-44a6e780-9c14-11eb-8fc6-3f2f273ebc39.png)

如图，会遮挡住加载界面的标题等。

**Comment by WangScaler** [comment]
![image](https://user-images.githubusercontent.com/68225189/120991313-14af3700-c7b4-11eb-8d23-82cbe189002e.png)
我现在时扩大了它的高度

**Comment by recoluan** [comment]
现在已经没有再限制这个高度了
