### ISSUE TITLE
如何让一篇文章排在前面？

### ISSUE THREAD

**Issue by maYunLaoXi** [vuepress-reco/vuepress-theme-reco#348]
文章好像是按照时间排序，但是有某一篇/几篇文章是希望进入首页后排在前面，如何配置呢？

**Comment by wencwcoder** [comment]
可以在 Front Matter 中添加 sticky 来选择文章的排列优先级，type: number
参考：[sticky](https://vuepress-theme-reco.recoluan.com/views/1.x/frontMatter.html#sticky)

**Comment by wencwcoder** [comment]
@maYunLaoXi

**Comment by maYunLaoXi** [comment]
> 可以在 Front Matter 中添加 sticky 来选择文章的排列优先级，type: number
> 参考：[sticky](https://vuepress-theme-reco.recoluan.com/views/1.x/frontMatter.html#sticky)

收到，感谢
