### ISSUE TITLE
通过点击导航或者标题进入md，页面会正常显示顶部，能看到标题和作者信息，在页面内刷新就只会从中间部分显示

### ISSUE THREAD

**Issue by ouchengle** [vuepress-reco/vuepress-theme-reco#349]
- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Your OS: 
- Node.js version: v12.18.0
- VuePress version: vuepress@1.8.2
- VuePress-theme-reco version: 1.6.6
- Which package manager did you use for the install(npm/cnpm/yarn)?
npm

**Comment by recoluan** [comment]
这个问题暂时没有找到解决方案，咱们可以关注一下主题 2.0，后期 1.0 将不再维护了。

http://v2.vuepress-reco.recoluan.com/
