### ISSUE TITLE
文章加密功能失效

### ISSUE THREAD

**Issue by Xuminhua** [vuepress-reco/vuepress-theme-reco#35]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?
设置文章加密后（页面加上keys），从主页或者TimeLine进入对应文章是仍然可以顺利访问，强制刷新一次后出现加密的状态。
从category或者tag的入口进去，就能显示加密的状态

#### Other relevant information

- Your OS: MacOS Mojave 10.14.6
- Node.js version: 8.9.0
- VuePress version: 1.0.1
- VuePress-theme-reco version: 1.0.4
- Which package manager did you use for the install(npm/cnpm/yarn)?

**Comment by recoluan** [comment]
> * [x]  I confirm that this is an issue rather than a question.
> 
> ## Bug report
> #### What is actually happening?
> 设置文章加密后（页面加上keys），从主页或者TimeLine进入对应文章是仍然可以顺利访问，强制刷新一次后出现加密的状态。
> 从category或者tag的入口进去，就能显示加密的状态
> 
> #### Other relevant information
> * Your OS: MacOS Mojave 10.14.6
> * Node.js version: 8.9.0
> * VuePress version: 1.0.1
> * VuePress-theme-reco version: 1.0.4
> * Which package manager did you use for the install(npm/cnpm/yarn)?

非常感谢你的反馈，我已将这个bug加入to-do list，如果修复，我会在这里通知你的。

**Comment by recoluan** [comment]
请升级至 `1.1.0`

**Comment by hellorayza** [comment]
在加密的md文档中也不要使用
```
<!-- more -->
```
作为摘要，否则亦会导致文章加密失效。
具体表现为在主页或者tag页面，虽然可以看到标题有加标识(锁)但可以看到`more`之前的内容。

环境：
```json
{
  "devDependencies": {
	"vuepress": "^1.7.1",
	"vuepress-theme-reco": "^1.6.1"
  }
}
```
