### ISSUE TITLE
可以考虑子侧边栏显示一级标题吗，或者提供显示哪些等级标题的配置，在front-matter或者theme-config

### ISSUE THREAD

**Issue by ouchengle** [vuepress-reco/vuepress-theme-reco#350]

**Comment by ouchengle** [comment]
module.exports = {
  markdown: {
    extractHeaders: ["h1", "h2", "h3", "h4", "h5", "h6"]
  }
}

看到之前有同学提过关于标题等级的issue，发现他说的这个配置能启用子侧边栏的其他标题显示

**Comment by ouchengle** [comment]
不过刷新之后会自动定位到第一个二级标题的位置

**Comment by recoluan** [comment]
可以关注一下主题 2.0，后面 1.0 就不再维护了。
