### ISSUE TITLE
category

### ISSUE THREAD

**Issue by wencwcoder** [vuepress-reco/vuepress-theme-reco#351]
![Snipaste_2021-04-17_16-56-26](https://user-images.githubusercontent.com/52773820/115107510-dceaf680-9f9d-11eb-9176-53a1c4d94366.png)
该 category 现在1.x 版本给个配置就会自动生成，有没有办法控制其顺序，现在发现有时 cate1 和 cate2 的顺序是随机的。

**Comment by recoluan** [comment]
删除配置，手写 navbar 即可

**Comment by wencwcoder** [comment]
@recoluan 🤦‍♂️
