### ISSUE TITLE
文章目录高度太小了，可以自定义 subSidebar 的高度吗？

### ISSUE THREAD

**Issue by shirayner** [vuepress-reco/vuepress-theme-reco#354]
## Feature request
如下图，只能显示部分目录，而我想目录的高度变大一点
![image](https://user-images.githubusercontent.com/11574340/116856961-94366d00-ac2e-11eb-955a-3bb4f0faf450.png)
最好类似Typora这种，可以一下子显示整篇文章的目录
![image](https://user-images.githubusercontent.com/11574340/116857264-17f05980-ac2f-11eb-9bd4-7a99c7957966.png)

如果能让用户自定义 subSidebar  高度，就会很棒，请问有什么方式可以实现这个需求吗？

**Comment by NatureK88** [comment]
有两个方法：
一是在你生成的网页上f12，找到相关元素的css，在此是sidebar-links之类，然后按照官网教程自定义css样式。
二是找到SidebarLinks.vue文件，直接在这个文件中找到相关设置修改，在这个文件同级目录下还有诸多其他设置的.vue文档。

**Comment by recoluan** [comment]
> ## Feature request
> 如下图，只能显示部分目录，而我想目录的高度变大一点 ![image](https://user-images.githubusercontent.com/11574340/116856961-94366d00-ac2e-11eb-955a-3bb4f0faf450.png) 最好类似Typora这种，可以一下子显示整篇文章的目录 ![image](https://user-images.githubusercontent.com/11574340/116857264-17f05980-ac2f-11eb-9bd4-7a99c7957966.png)
> 
> 如果能让用户自定义 subSidebar 高度，就会很棒，请问有什么方式可以实现这个需求吗？

可以通过自定义样式去实现：https://vuepress.vuejs.org/zh/config/#index-styl
