### ISSUE TITLE
让文章能够有多级标题

### ISSUE THREAD

**Issue by rsong404** [vuepress-reco/vuepress-theme-reco#358]
我是1.6.1的主题版本，这版本中只支持文章的二级和三级标题，实在有点少，很多使用想用一级或四级标题都不能显示，希望题主主在新版本中能支持更多的标题级别。

**Comment by recoluan** [comment]
一级标题是文章的大标题，正文不应该出现一级标题；至于四级标题，右侧侧边栏只是方便文章大概位置的跳动，不需要展示完整，使用场景不多，如果一定要展示全，建议在页面最上方使用 [[TOC]]
