### ISSUE TITLE
首页tag跳转路径错误

### ISSUE THREAD

**Issue by yanyongyu** [vuepress-reco/vuepress-theme-reco#36]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?

点击首页标签之后跳转地址为：xxxxx/tag/#?tag=xxx

多了一个#导致实际显示的不是那一栏

#### Other relevant information

- Your OS: Windows
- Node.js version: 
- VuePress version: 1.0.2
- VuePress-theme-reco version: 1.0.4
- Which package manager did you use for the install(npm/cnpm/yarn)? npm

**Comment by recoluan** [comment]
我记得当初是为了解决另一个问题来着，采取的一个朋友的建议，没想到又出现了其他的问题，我会修复这个bug的，感谢你的反馈🙏。
