### ISSUE TITLE
文章超过64页时，首页显示不正确！

### ISSUE THREAD

**Issue by shinuyeim** [vuepress-reco/vuepress-theme-reco#362]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
当我新增博客的页面总共到64个页面的时候，主页页面会显示混乱，就是最新提交的5篇就消失了的。就是在主页显示不出来最新的5篇文章（更新到第64篇，多余64篇也是同样的问题，只能显示前59篇），但是在分类、标签、时间线和搜索框下都能找到最新更新的文章，就只是首页显示时混乱的。而且，当我文章总数到64篇的时候，页面显示不正确，但是删除其中的任意一篇，主页页面都可以正常显示，就是文章总数只要不大于64，那么无论怎们换文章都可以正常显示。我也经过多次测试，但是都不能解决这个问题，看其使用这个主题的的人，大多数都还没有写道第64篇，所以不知道其他人有没有这个问题。

#### Other relevant information

- Your OS: Windows10 专业版
- Node.js version: 14.17.0
- VuePress version: 1.8.2
- VuePress-theme-reco version: 1.6.6
- Which package manager did you use for the install(npm/cnpm/yarn)?yarn

**Comment by jokervTv** [comment]
同样如此，不过我这里不是 64，但是问题是差不多的

**Comment by ATQQ** [comment]
所以我至今 还是用的 1.5.7 真好用 https://github.com/ATQQ/sugar-blog

**Comment by recoluan** [comment]
我这边没复现问题呢，咱们可以都关注一下主题 2.0，后面 1.0 就不再维护了。
