### ISSUE TITLE
为什么日期显示规则是这样的？9/21/2019

### ISSUE THREAD

**Issue by alvin0216** [vuepress-reco/vuepress-theme-reco#363]
![image](https://user-images.githubusercontent.com/34113677/123402778-af907980-d5da-11eb-9bb7-a8935dcdcc45.png)

**Comment by duolanda** [comment]
我解决这个问题了，需要将默认的 lang 改为 zh-CN，进入 config.js，添加如下内容：

```
module.exports = {
  locales: {
    '/': {
      lang: 'zh-CN', 
    }
  },
} 
```

**Comment by alvin0216** [comment]
好像不行的哦 ～

**Comment by duolanda** [comment]
> 好像不行的哦 ～

不应该呀，我这里改完之后就可以了，你按 F12 看一下 html 的 lang 是不是变成"zh-CN"了，如果没有的话说明配置还有问题。

**Comment by alvin0216** [comment]
> > 好像不行的哦 ～
> 
> 不应该呀，我这里改完之后就可以了，你按 F12 看一下 html 的 lang 是不是变成"zh-CN"了，如果没有的话说明配置还有问题。

我写到 themeConfig 里面了原来，多谢，已解决
