### ISSUE TITLE
md 文件使用中文命名编译失败，不使用主题则正常编译显示正常。

### ISSUE THREAD

**Issue by TuiMao233** [vuepress-reco/vuepress-theme-reco#364]
![image](https://user-images.githubusercontent.com/49724027/123442383-673b8080-d607-11eb-9508-921da87c8dbb.png)

**Comment by KimYangOfCat** [comment]
可以考虑使用一个插件  `permalink-pinyin` ，将中文文件名自动转化为拼音：

https://github.com/viko16/vuepress-plugin-permalink-pinyin
