### ISSUE TITLE
暗黑主题logo设置

### ISSUE THREAD

**Issue by lunxian8** [vuepress-reco/vuepress-theme-reco#365]
## Feature request

config.js
feat：
darkIcon: /dark.ico

home.vue

feat:
darkHeroImage: /dark.png

**Comment by recoluan** [comment]
根据咱的建议，该功能将在主题 2.0 里实现，1.0 后期将不再维护。

https://github.com/vuepress-reco/vuepress-theme-reco-next/issues/18#issue-1133994228
