### ISSUE TITLE
404 doesnot work

### ISSUE THREAD

**Issue by fastzhong** [vuepress-reco/vuepress-theme-reco#367]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?

default theme can return 404 page. 

i copy reco to my docs/.vuepress/theme

a (blank) page returned below instead of the proper 404 page (below): 

```html
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title></title>
  <link rel="apple-touch-icon" href="apple-touch-icon.png"><link rel="icon" href="favicon.ico"><link rel="manifest" href="site.webmanifest"><meta name="application-name" content="fastzhong-bits"><meta name="description" content="fastzhong's study notes"><meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no"><meta charset="utf-8"></head>
  <body>
    <div id="app"></div>
  <script type="text/javascript" src="/assets/js/app.js"></script></body>
</html>
```

#### Other relevant information

- Your OS: MacOS 11.4
- Node.js version: 16.3
- VuePress version: 1.8.2
- VuePress-theme-reco version: 1.6.6
- Which package manager did you use for the install(npm/cnpm/yarn)? yarn

**Comment by recoluan** [comment]
可以关注一下主题 2.0，1.0 后期将不再维护。

http://v2.vuepress-reco.recoluan.com/
