### ISSUE TITLE
代码块不能高亮

### ISSUE THREAD

**Issue by ZW-L** [vuepress-reco/vuepress-theme-reco#369]
- [ ] I confirm that this is an issue rather than a question.

#### 代码块无法高亮

代码块有时能高亮有时不能高亮，在 VuePress 中无这个问题，请问是何原因？

- Your OS: Mac
- Node.js version: v14
- VuePress version: v1.x
- VuePress-theme-reco version: v1.x
- Which package manager did you use for the install(npm/cnpm/yarn)? yarn

**Comment by ZW-L** [comment]
补充一下，是代码块主题颜色丢失了

**Comment by KimYangOfCat** [comment]
可否贴一下你关于代码块的相关设置？是否是保持默认设置没有改变？再贴一下 vuepress 和本主题的版本信息，这样才能方便别人帮你排查问题

**Comment by ZW-L** [comment]
找到原因了，`blogs` 目录下不能有 `css` 的文件夹，会导致代码块不能高亮。

**Comment by KimYangOfCat** [comment]
> 找到原因了，`blogs` 目录下不能有 `css` 的文件夹，会导致代码块不能高亮。

这确实不能，因为主题默认的样式文件也会生成在 CSS 目录下，这会导致覆盖问题

**Comment by ZW-L** [comment]
> > 找到原因了，`blogs` 目录下不能有 `css` 的文件夹，会导致代码块不能高亮。
> 
> 这确实不能，因为主题默认的样式文件也会生成在 CSS 目录下，这会导致覆盖问题

👌
