### ISSUE TITLE
移动端时间线里日期变为NAN

### ISSUE THREAD

**Issue by ChaselLHL** [vuepress-reco/vuepress-theme-reco#37]
#10  Bug report

#### What is actually happening?
移动端时间线里日期变为NAN, 在safari和qq浏览器中测试均复现

#### Other relevant information
![54CCBCBF9B2157C4BDEB46ABF8335ACE](https://user-images.githubusercontent.com/34236185/63260203-e268d880-c2b2-11e9-8c3c-f3ff52f7158b.png)
- Your OS:  Iphone 8 
- Node.js version:  10.15.0
- VuePress version: 1.x
- VuePress-theme-reco version: 1.0.4
- Which package manager did you use for the install(npm/cnpm/yarn)?yarn

**Comment by recoluan** [comment]
感谢你的反馈，问题已经找到原因，将在下个版本中修复
