### ISSUE TITLE
public下新建文件夹存放图片，MD文档中的图片放大功能失效

### ISSUE THREAD

**Issue by LiJunYi2** [vuepress-reco/vuepress-theme-reco#375]
## Bug report
在public文件夹下新建文件存放MD引用的图片，经测试发现图片放大功能失效。

#### Other relevant information

- Your OS:  win0
- Node.js version: 14.15.5
- VuePress version:  1.8.2
- VuePress-theme-reco version:  1.6.6
- Which package manager did you use for the install(npm/cnpm/yarn)?npm

**Comment by recoluan** [comment]
这个问题暂时没有找到解决方案，咱们可以关注一下主题 2.0，后期 1.0 将不再维护了。

http://v2.vuepress-reco.recoluan.com/
