### ISSUE TITLE
README.md配置heroText: null无效，目前已解决

### ISSUE THREAD

**Issue by caoyan0829** [vuepress-reco/vuepress-theme-reco#376]
---
home: true
heroText: null
tagline: null
---

#### 配置heroText: null无效，需要配置tagline: null

![image](https://user-images.githubusercontent.com/31430084/131432108-e5b7ec7d-06fb-43dc-9155-bf2b3371372b.png)
看了下源码，增加配置tagline: null 解决

**Comment by recoluan** [comment]
可以关注一下主题 2.0，1.0 后期将不再维护。

http://v2.vuepress-reco.recoluan.com/
