### ISSUE TITLE
v1.6.6版本引用npm i之后报错每次点击tag跳转404

### ISSUE THREAD

**Issue by a1burning** [vuepress-reco/vuepress-theme-reco#379]
我在1.8.0的vuepress中使用了reco，之后用npm i 安装的时候，标签跳转有问题，控制台报错 找不到$tags，还说pageInfo里面在render的时候解析 this.tags.list.length 报错。后来安装了yarn，用yarn安装不报错了，跳转也正常，还是有一堆的警告。

[vue-router] Route with path "/tag/函数/" contains unencoded characters, make sure your path is correctly encoded before passing it to the router. Use encodeURI to encode static segments of your path.

- Your OS: macbook
- Node.js version: 14.16.1
- VuePress version: 1.8.0
- VuePress-theme-reco version: 1.6.6
- Which package manager did you use for the install(npm/cnpm/yarn)?npm

**Comment by recoluan** [comment]
应该是标签使用中文的原因

**Comment by wencwcoder** [comment]
> 应该是标签使用中文的原因
对，不能使用中文，之前我就遇到过，会发生跳转错误。
