### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by kame000** [vuepress-reco/vuepress-theme-reco#38]
[root@VM_0_7_centos my-blog]# npm run dev

> my-blog@1.0.0 dev /root/my-blog
> vuepress dev docs

wait Extracting site metadata...
/root/my-blog/docs/.vuepress/config.js:76
    '@vuepress/pwa': {
                   ^

SyntaxError: Unexpected token :

默认安装后 npm run dev

**Comment by recoluan** [comment]
问题已经修复，请重新生成一下博客。
