### ISSUE TITLE
container 插件不生效

### ISSUE THREAD

**Issue by bolawen** [vuepress-reco/vuepress-theme-reco#381]
服务运行时:

![image](https://user-images.githubusercontent.com/57985761/134828343-468f4db6-946b-43b1-b038-60645bca9851.png)

服务启动后:

![image](https://user-images.githubusercontent.com/57985761/134828354-edb049e6-7f79-458d-b5d5-c0c47b45ec31.png)

**Comment by recoluan** [comment]
应该是依赖没有安装好吧，试试删除 node_modules 重新安装呢
