### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by lunasaw** [vuepress-reco/vuepress-theme-reco#383]
- [ ] I confirm that this is an issue rather than a question.

## Bug report
✔ Client
  Compiled successfully in 2.15m

✔ Server
  Compiled successfully in 1.41m

wait Rendering static HTML...

<--- Last few GCs --->

[19913:0x103c85000]   196334 ms: Mark-sweep 1332.8 (1424.5) -> 1332.4 (1425.0) MB, 1562.3 / 0.0 ms  (average mu = 0.173, current mu = 0.011) allocation failure scavenge might not succeed
[19913:0x103c85000]   198722 ms: Mark-sweep 1333.1 (1425.0) -> 1332.7 (1425.5) MB, 2370.7 / 0.0 ms  (average mu = 0.084, current mu = 0.007) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1713dab5bf3d]
    1: StubFrame [pc: 0x1713dab60d95]
Security context: 0x2a18f649e6c1 <JSObject>
    2: get [0x2a1829128169] [server-bundle.js:~47639] [pc=0x1713dbe2ab14](this=0x2a18e5d1c599 <VueComponent map = 0x2a18f9385279>)
    3: arguments adaptor frame: 1->0
    4: computedGetter [0x2a1820155f81] [/Users/luna/luna-reco/node_modules/vue/dist/vue.runtime.common.dev.js:~4845] [pc=0x1713dbe1502d](this=0x2a18e5d1c5...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003a853 node::Abort() [/usr/local/Cellar/node@10/10.24.1_1/bin/node]
 2: 0x10003aa21 node::OnFatalError(char const*, char const*) [/usr/local/Cellar/node@10/10.24.1_1/bin/node]
 3: 0x10017db47 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node@10/10.24.1_1/bin/node]
 4: 0x10017dae9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node@10/10.24.1_1/bin/node]
 5: 0x100441e40 v8::internal::Heap::UpdateSurvivalStatistics(int) [/usr/local/Cellar/node@10/10.24.1_1/bin/node]
 6: 0x100443a63 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/Cellar/node@10/10.24.1_1/bin/node]
 7: 0x100441088 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/Cellar/node@10/10.24.1_1/bin/node]
 8: 0x10043fd74 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReas
 
#### What is actually happening?
可以run dev 视图正常，但是run build会node堆栈异常，求解

#### Other relevant information

- Your OS: macos11
- Node.js version: 10.24.1
- VuePress version: 1.5.7
- VuePress-theme-reco version: 
- Which package manager did you use for the install(npm/cnpm/yarn)? npm yarn 均复现

**Comment by recoluan** [comment]
暂时不明确问题原因，尝试一下升级 node 版本试试呢
