### ISSUE TITLE
css 错误

### ISSUE THREAD

**Issue by wencwcoder** [vuepress-reco/vuepress-theme-reco#384]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
![image](https://user-images.githubusercontent.com/52773820/139409467-6678912a-3275-4257-875e-fd4979aaae79.png)
css 加载错误，会导致下面的问题
![image](https://user-images.githubusercontent.com/52773820/139409586-4da426a7-95ad-46e9-b361-2021fee65c64.png)
图标加载不出来

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version: 
- VuePress-theme-reco version: 
- Which package manager did you use for the install(npm/cnpm/yarn)?

**Comment by recoluan** [comment]
这里使用的是 iconfont 提供的cdn，估计是你所使用的网络把阿里的 cdn 给墙了。

**Comment by recoluan** [comment]
1.0 版本的 bug 和功能你再维护了，建议关注一下 2.0 版本。

**Comment by wencwcoder** [comment]
>

**Comment by wencwcoder** [comment]
> 这里使用的是 iconfont 提供的cdn，估计是你所使用的网络把阿里的 cdn 给墙了。

有可能，我是在公司弄的，公司墙了很多网站，我回去试一试。

**Comment by wencwcoder** [comment]
确实如此，公司屏蔽了太多网站，哎

**Comment by wencwcoder** [comment]
> > 这里使用的是 iconfont 提供的cdn，估计是你所使用的网络把阿里的 cdn 给墙了。
> 
> 有可能，我是在公司弄的，公司墙了很多网站，我回去试一试。

确实如此，公司屏蔽了太多网站，哎
