### ISSUE TITLE
想知道markdown渲染用了什么主题

### ISSUE THREAD

**Issue by tangming991** [vuepress-reco/vuepress-theme-reco#386]
![image](https://user-images.githubusercontent.com/62093605/143050690-c2af6175-86bc-4a4a-ad15-13ab26e32be8.png)
我一直想知道怎么渲染成这样

**Comment by recoluan** [comment]
markdown 会渲染出 html，如果想要什么样式，可以自己写css，也可以使用现有的一些开源的主题，其中我用的是 prismjs，并在基础上做了一些调整，外面的类 mac 按钮是用 css 画的，还有其他的主题，可以搜一下
