### ISSUE TITLE
bulid 页面异常

### ISSUE THREAD

**Issue by ThreeLambs** [vuepress-reco/vuepress-theme-reco#387]
yarn dev 正常
yarn build 成功但是页面异常
![Snipaste_2021-12-02_16-50-20](https://user-images.githubusercontent.com/23123048/144388803-5d13fb5e-1958-4882-8777-043144704d8a.png)

**Comment by recoluan** [comment]
你的 index.html 没有在根目录，所以需要设置 base: '/public/'，所以你可以选择增加 base 设置，或者静态文件放在服务器根目录。
