### ISSUE TITLE
I have modified the Home.vue, but find the vuepress-theme-reco take no effect

### ISSUE THREAD

**Issue by zwf193071** [vuepress-reco/vuepress-theme-reco#388]
I have modified the Home.vue, like the picture below:
![image](https://user-images.githubusercontent.com/11342717/146357489-1762ce0f-6ed7-470f-99e6-ed83e5c68dc1.png)
but find the vuepress-theme-reco take no effect

I have also modified the `index.js` also, like the code below:
`module.exports = {
    extend: 'vuepress-theme-reco'
}`
but it gets worse.

Is there any way to rewrite the Home.vue but also keep the vuepress-theme-reco theme?

**Comment by zwf193071** [comment]
`module.exports = {
    extend: '@vuepress/theme-default',
    plugins: [
		require('vuepress-theme-reco'),
	]
}`

I have tried the code above, but still not working

**Comment by recoluan** [comment]
自定义首页可以参考这里：https://vuepress-theme-reco.recoluan.com/views/1.x/home.html
