### ISSUE TITLE
大大，你好，开启valine评论功能，如果 valine 的获取评论的接口报 404 错误的问题

### ISSUE THREAD

**Issue by KitchenLiang** [vuepress-reco/vuepress-theme-reco#39]
能不能参照人家的，他的评论为空不会报错，也是用Valine
https://www.finen.top/blog/others/wheel/vuepress.html#vuepress%E7%BD%91%E7%AB%99

**Comment by KitchenLiang** [comment]
![image](https://user-images.githubusercontent.com/7965306/63909214-70338900-ca54-11e9-9694-c20750a808b1.png)

**Comment by recoluan** [comment]
你好，这个评论为空的时候报错的问题，我先记下来，有空了之后我去看一下好吧，其实他不影响项目本身的，因为只要有了一条评论，就不会报错了。^_^

**Comment by recoluan** [comment]
内部商讨后决定不对这个问题不影响功能，暂不处理。

然后上面的地址对应的 valine 评论功能，我看了一下他的源码，跟我的实现方式差不多，没有看到区别，

**Comment by SigureMo** [comment]
@KitchenLiang 上面的地址我也试了，也是会报错的，这个报错应该跟valine的内部实现有关，该issue可以去valine提一下
