### ISSUE TITLE
publish: false时,该文章的分类仍然会被记录，而tag则正确的隐藏

### ISSUE THREAD

**Issue by zbl666** [vuepress-reco/vuepress-theme-reco#390]
当我一篇文章的publish: false时，我发现该分类在主页仍然能够看到，tag则正确的隐藏。且只有该文章拥有该分类。

**Comment by Arvin-He** [comment]
> 当我一篇文章的publish: false时，我发现该分类在主页仍然能够看到，tag则正确的隐藏。且只有该文章拥有该分类。

此外，分类文章数量统计也存在，建议根据是否发布来计算分类的生成和文章数量统计

**Comment by recoluan** [comment]
> > 当我一篇文章的publish: false时，我发现该分类在主页仍然能够看到，tag则正确的隐藏。且只有该文章拥有该分类。
> 
> 此外，分类文章数量统计也存在，建议根据是否发布来计算分类的生成和文章数量统计

这个功能无法实现，第三方工具做不到这么智能。

**Comment by recoluan** [comment]
> 当我一篇文章的publish: false时，我发现该分类在主页仍然能够看到，tag则正确的隐藏。且只有该文章拥有该分类。

博客功能依赖官方的插件，所以无法修复这个问题，可以关注一下 reco 主题 2.0。
