### ISSUE TITLE
更新到2.0.1版本后，中文标签和分类跳转到空页面

### ISSUE THREAD

**Issue by pennbay** [vuepress-reco/vuepress-theme-reco#395]
#### What is actually happening?
更新到2.0.1版本后，文章中若含有中文标签和分类，那么点击该标签或分类会跳转到空页面，而英文标签和分类则无此问题。
 比如，@recoluan 的[网站](https://www.recoluan.com/)，点击英文标签是正常的，但点击中文标签页面空白。

点击英文标签正常：
![image](https://user-images.githubusercontent.com/26505726/149474684-550b8adf-5d02-4b7f-b859-4d56927ed423.png)

点击中文标签显示空白：
![image](https://user-images.githubusercontent.com/26505726/149474891-f0d6385d-3b51-413d-a7ac-09878d85754b.png)

#### Other relevant information

- Your OS: Microsoft Edge version 97.0.1072.55
- Node.js version: v14.17.0
- VuePress version: v2.0.0-beta.27
- VuePress-theme-reco version: v2.0.1-alpha.18
- Which package manager did you use for the install(npm/cnpm/yarn)?yarn

**Comment by ATQQ** [comment]
提供一个简单的解决办法

添加文件[.vuepress/enhanceApp.js](https://www.vuepress.cn/guide/basic-config.html#%E5%BA%94%E7%94%A8%E7%BA%A7%E5%88%AB%E7%9A%84%E9%85%8D%E7%BD%AE)，写入以下内容
```js
export default ({
    router, // 当前应用的路由实例
}) => {
    // 解决中文路由无法被正确加载的问题
    router.beforeEach((to, from, next) => {
        if (decodeURIComponent(to.path) !== to.path) {
            return next({
                ...to,
                path: decodeURIComponent(to.path),
                fullPath: decodeURIComponent(to.fullPath)
            })
        }
        next()
    })
}
```

相关资料
* vue-router [beforEach钩子](https://router.vuejs.org/zh/guide/advanced/navigation-guards.html#%E5%85%A8%E5%B1%80%E5%89%8D%E7%BD%AE%E5%AE%88%E5%8D%AB)
* [vuepress 应用级配置](https://www.vuepress.cn/guide/basic-config.html#%E5%BA%94%E7%94%A8%E7%BA%A7%E5%88%AB%E7%9A%84%E9%85%8D%E7%BD%AE)

**Comment by duktig666** [comment]
> 

版本1.6.10
添加了 `.vuepress/enhanceApp.js` 文件，中文路由依然不能正常跳转

**Comment by duktig666** [comment]
vuepress-plugin-permalink-pinyin 这个插件使用默认的永久链接模式可以，但是如果修改永久链接模式为如下时会失效：
```js
// 永久链接格式
permalink: "/:year/:month/:day/:slug",
```

**Comment by ATQQ** [comment]
> > 
> 
> 版本1.6.10 添加了 `.vuepress/enhanceApp.js` 文件，中文路由依然不能正常跳转

我这边是1.5.7，明早 我跑1.6.10看看ε(*･ω･)_/ﾟ:･☆

**Comment by duktig666** [comment]
> > > 
> > 
> > 
> > 版本1.6.10 添加了 `.vuepress/enhanceApp.js` 文件，中文路由依然不能正常跳转
> 
> 我这边是1.5.7，明早 我跑1.6.10看看ε(*･ω･)_/ﾟ:･☆

请问 1.6.10 可以吗

**Comment by ATQQ** [comment]
> > > > 
> > > 
> > > 
> > > 版本1.6.10 添加了 `.vuepress/enhanceApp.js` 文件，中文路由依然不能正常跳转
> > 
> > 
> > 我这边是1.5.7，明早 我跑1.6.10看看ε(*･ω･)_/ﾟ:･☆
> 
> 请问 1.6.10 可以吗

刚试了一下，也有问题，我是解决中文标签和分类用的

我去看看2.0的解决

**Comment by ATQQ** [comment]
2.0 是转成了 拼音 [查看源码](https://github.com/vuepress-reco/vuepress-theme-reco-next/blob/3d16a822524b3447dc90feb329a8c667a9988571/packages/%40vuepress-reco/shared/src/helpers/toPinYin.ts#L6)

**Comment by ATQQ** [comment]
我再debug看看中文路由的实际结果

**Comment by duktig666** [comment]
> 2.0 是转成了 拼音 [查看源码](https://github.com/vuepress-reco/vuepress-theme-reco-next/blob/3d16a822524b3447dc90feb329a8c667a9988571/packages/%40vuepress-reco/shared/src/helpers/toPinYin.ts#L6)

1.6.10 使用拼音插件 vuepress-plugin-permalink-pinyin ，我发现配置如下永久链接不生效：
```
// 永久链接格式
permalink: "/:year/:month/:day/:slug",
```

**Comment by ATQQ** [comment]
刚看了一下，定位到bug原因了。明天抽空fix一下。

decode的会被重定向到encode的路由

encode的路由又会被钩子decode

所以就爆栈了 ，无法正常跳转

**Comment by ATQQ** [comment]
@duktig666 


1.6.10  临时解决方案可以用下面这个，亲测没问题了，bug原因如上所述

.vuepress/enhanceApp.js
```js
export default (ctx) => {
    ctx.router.beforeEach((to, from, next) => {
        // 解决中文标签/分类路由无法被正确加载的问题
        if (!(/\.html$/.test(to.path)) && decodeURIComponent(to.path) !== to.path) {
            return next({
                ...to,
                path: decodeURIComponent(to.path)
            })
        }
        // 不特殊处理.html
        next()
    })

    // 临时解决，防止内部调用钩子再处理
    ctx.router.beforeEach = () => {
        return
    }
}
```

**Comment by ATQQ** [comment]
fix pr:https://github.com/vuepress-reco/vuepress-theme-reco/pull/399

**Comment by duktig666** [comment]
> @duktig666
> 
> 1.6.10 临时解决方案可以用下面这个，亲测没问题了，bug原因如上所述
> 
> .vuepress/enhanceApp.js
> 
> ```js
> export default (ctx) => {
>     ctx.router.beforeEach((to, from, next) => {
>         // 解决中文标签/分类路由无法被正确加载的问题
>         if (!(/\.html$/.test(to.path)) && decodeURIComponent(to.path) !== to.path) {
>             return next({
>                 ...to,
>                 path: decodeURIComponent(to.path)
>             })
>         }
>         // 不特殊处理.html
>         next()
>     })
> 
>     // 临时解决，防止内部调用钩子再处理
>     ctx.router.beforeEach = () => {
>         return
>     }
> }
> ```

测试，**1.6.10版本可以成功跳转**。

但是还存在一个问题，如果设置了永久链接的格式如下，依然会跳转失败：
```js
// 永久链接格式
permalink: "/:year/:month/:day/:slug"
```
具体报错如下图：
![1643097032(1)](https://user-images.githubusercontent.com/53132746/150934199-352e491f-5cbd-43d1-852f-40074abef855.png)

**Comment by ATQQ** [comment]
报错 信息一样 原因应该差不都

晚点抽空看看这个

**Comment by duktig666** [comment]
> 在你的仓库中的话可以 迭代一下
> 
> .vuepress/enhanceApp.js
> 
> ```js
> export default (ctx) => {
>   const routes = ctx.router.getRoutes()
>   
>   ctx.router.beforeEach((to, from, next) => {
>     // 解决decode后反复重定向的问题
>     const route = routes.find((v) => v.regex.test(to.path))
> 
>     // .html有重定向路由，无需特殊处理
>     if (/\.html$/.test(to.path)) {
>       return next()
>     }
> 
>     // 不特殊处理 非通配符的 没有重定向的路由
>     if (route && route.path !== '*' && !route.redirect) {
>       return next()
>     }
> 
>     // 解决中文标签/分类路由无法被正确加载的问题
>     if (decodeURIComponent(to.path) !== to.path) {
>       return next(
>         Object.assign({}, to, {
>           path: decodeURIComponent(to.path),
>           fullPath: decodeURIComponent(to.fullPath)
>         })
>       )
>     }
> 
>     next()
>   })
> 
>   // 临时解决，防止内部调用钩子再处理
>   ctx.router.beforeEach = () => {
>     return
>   }
> }
> 

经过测试已经成功解决了这个问题

**Comment by recoluan** [comment]
@pennbay 2.x 的最新版本已经解决中文路径的问题了，可以尝试一下。
