### ISSUE TITLE
1.6.10 配置代码主题不生效 和 禁用活动的标题链接失效

### ISSUE THREAD

**Issue by duktig666** [vuepress-reco/vuepress-theme-reco#397]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
1. 配置代码主题不生效，修改配置
module.exports = {
  theme: 'reco',
  themeConfig: {
    /**
     * support for
     * 'default'
     * 'funky'
     * 'okaidia'
     * 'solarizedlight'
     * 'tomorrow'
     */
    codeTheme: 'solarizedlight' // default 'tomorrow'
  }
}

不管如何设置，样式不变

prism代码高亮样式 详情参看：[https://cloud.tencent.com/developer/article/1622399](https://cloud.tencent.com/developer/article/1622399)

2. 禁用活动的标题链接失效
如下操作失效：
```js
// .vuepress/config.js
module.exports = {
  themeConfig: {
    activeHeaderLinks: false, // 默认值：true
  }
}
```

官方参看：[活动的标题链接](https://vuepress.vuejs.org/zh/theme/default-theme-config.html#%E6%B4%BB%E5%8A%A8%E7%9A%84%E6%A0%87%E9%A2%98%E9%93%BE%E6%8E%A5)

#### Other relevant information

- Your OS: win10
- Node.js version: v12.13.1
- VuePress version: 默认
- VuePress-theme-reco version: 1.6.10
- Which package manager did you use for the install(npm/cnpm/yarn)?   npm

**Comment by recoluan** [comment]
因为 cdn 不友好，这个功能已经下线了。
