### ISSUE TITLE
首页的分类样式有点low 标签页建议增加个全部选项 

### ISSUE THREAD

**Issue by Mrli2016** [vuepress-reco/vuepress-theme-reco#41]
1. 首页的分类样式真有点难看
2. 标签页的体验不够好 应该增加个全部按钮 直接进来的时候应该默认展示全部 点击标签后才进行过滤 然后点击全部的时候能看到所有文章

**Comment by recoluan** [comment]
第二天条条建议接受，第一条建议你可以给出更佳详细的修改建议

**Comment by Mrli2016** [comment]
> 第二天条条建议接受，第一条你可以给出更加详细的修改建议

唔 第一条的我也没啥建议 只是说我的感受而已 第一眼看过去有点简陋 跟其他UI的设计差别有点大 希望能改进

**Comment by Xuminhua** [comment]
很中肯的意见，两条都有同感，支持一下～

关于第一条，我尝试把边框线去掉, 感觉舒服一点点
![1](https://user-images.githubusercontent.com/10073763/64511830-afe15700-d317-11e9-87f1-a92e3ef2917f.PNG)

**Comment by recoluan** [comment]
已在 `1.1.0` 版本中添加此功能。
