### ISSUE TITLE
希望能加入再次自定义功能！类似vuepress官方默认主题自定义

### ISSUE THREAD

**Issue by ameibj** [vuepress-reco/vuepress-theme-reco#42]
修改默认主题
你可以使用 vuepress eject [targetDir] 这个命令来将默认主题的源码复制到 .vuepress/theme 文件夹下，从而可以对默认主题进行任意的修改。需要注意的是一旦 eject，即使升级 VuePress 你也无法再获得 VuePress 对默认主题的更新。

**Comment by ameibj** [comment]
比如我想把首页的 个人信息放到左侧，或者page 页 里面增加个自定义的背景音乐等等。希望能在你的基础上扩展

**Comment by recoluan** [comment]
你好，你说的 `eject` 功能会在脚手架中加入，只是目前的开发时间有限，所以需要再等等。

**Comment by ameibj** [comment]
sorry，刚我根据你步骤下了项目，和你 demo的UI 有点出入哈哈，还demo的很美好啊!,其实我是希望你demo的那个UI 做个性化的 增加内容！ 哈哈，估计你那个私有化了！

**Comment by ameibj** [comment]
另外：恕我愚蠢，我按照你 文档那种下载方法安装，没有效果啊。应该是没把你的 主题组件加到我的主题中；
npm install vuepress-theme-reco -dev--save
module.exports = {
  theme: 'reco'
}

**Comment by recoluan** [comment]
你是通过 `vuepress-theme-reco-cli` 生成的项目对吧，那里是原来的默认样式，如果你希望看到的是我的博客的样式，可以通过 [配置](https://vuepress-theme-reco.recoluan.com/views/1.x/home.html#%E5%8D%9A%E5%AE%A2%E9%A3%8E%E6%A0%BC%E9%A6%96%E9%A1%B5%E8%AE%BE%E7%BD%AE) 来切换首页的风格。

但是你说的私有化，我没太明白你的意思。

**Comment by ameibj** [comment]
> 但是你说的私有化，我没太明白你的意思。

我的意思是，我想要你 demo 中个人博客的那种 ui效果。

**Comment by recoluan** [comment]
> > 但是你说的私有化，我没太明白你的意思。
> 
> 我的意思是，我想要你 demo 中个人博客的那种 ui效果。

你点击我给你的配置链接，就可以看到怎么去设置我的个人博客的那种UI了。

还有，配置完后，你要重新启动项目才可以的。

**Comment by ameibj** [comment]
sorry，是不是这样的，我在 官方默认的主题上，在npm 你的 主题 npm install vuepress-theme-reco -dev--save，
然后配置，是不能生效的。 需要在你  脚手架的项目上做 config 里 配置 blog 模式

**Comment by ameibj** [comment]
![image](https://user-images.githubusercontent.com/16263441/64309238-80a4b000-cfce-11e9-90d3-b1df9ac28a46.png)
 我在默认主题的基础上这种方式引入主题并设置，没有成功。请问是因为最后找不到对应的主题路径的问题？ 谢谢！！！

**Comment by recoluan** [comment]
是可以解析的，因为很多人都在用，应该是你某一步操作不当导致的，你去项目官网加我微信，把项目发我，我给你看一下吧。

**Comment by ameibj** [comment]
哦，基本没写东西。只根据官网，下载了官方的主题。如果这样，那应该是我个例，我自己排查下吧。谢谢了！

**Comment by recoluan** [comment]
好的，有问题随时沟通。
