### ISSUE TITLE
升级到1.0.8-alpha.4版本显示can't found ./recoConfig.js

### ISSUE THREAD

**Issue by zkkysqs** [vuepress-reco/vuepress-theme-reco#43]
页面直接gg了，控制台显示：Error: Cannot find module './recoConfig.js'
亲爱的，可以及时更新一下API文档吗？ @recoluan

**Comment by recoluan** [comment]
> recoConfig

你好，我这没有出现这个问题，你可以把项目发给我，我看一下。

还有，每次更新和添加东西都会更新文档的，，目前你觉得具体哪一块还不完善？
