### ISSUE TITLE
[1.x] 移动端的frontMatter的数据不显示

### ISSUE THREAD

**Issue by LaiBaoYuan** [vuepress-reco/vuepress-theme-reco#44]
![image](https://user-images.githubusercontent.com/89441249/160375038-fb148bb3-0da4-47fc-84a4-1cdf0057e711.png)

<img width="753" alt="image" src="https://user-images.githubusercontent.com/89441249/160374978-2064b83e-a830-4ea3-bc6b-56fe0f504504.png">
<img width="313" alt="image" src="https://user-images.githubusercontent.com/89441249/160375097-fd40cc55-8219-4e8f-90ba-fc2770908d5a.png">
日期格式都是按照文档标准来填写的还是不显示，看了手机控制台日志爆错了，作者看到记得修复一下

**Comment by lbyworkspace** [comment]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/89441249/160375302-bf4d38e3-fceb-4c13-8fd5-d13e9e0b8d08.png">
pc中切换移动端是没有问题的，我的机型是iphone13pro
