### ISSUE TITLE
 从加密页面切换到非加密页面，加密输入框还在

### ISSUE THREAD

**Issue by happylql** [vuepress-reco/vuepress-theme-reco#45]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
 从加密页面切换到非加密页面，加密输入框还在

#### Other relevant information
none

- Your OS: 
- Node.js version: 11.3.0
- VuePress version: 1.0.4
- VuePress-theme-reco version: 1.x
- Which package manager did you use for the install(npm/cnpm/yarn)?yarn

**Comment by recoluan** [comment]
好的，感谢你的建议

**Comment by recoluan** [comment]
请升级 `1.1.0` 版本。
