### ISSUE TITLE
categories 设置中文 自动转化为拼音

### ISSUE THREAD

**Issue by houhoz** [vuepress-reco/vuepress-theme-reco#45]
categories 设置中文 分类链接自动转化为拼音

```md
...
categories:
  - 生活
...
```
自动转化为shenghuo

**Comment by houhoz** [comment]
https://houhoz.github.io/categories/shenghuo/1/
上述链接可复现

**Comment by recoluan** [comment]
这个是正常的，中文路由某些情况会出现跳转问题，所以做的转化。
