### ISSUE TITLE
首页分页

### ISSUE THREAD

**Issue by vxhly** [vuepress-reco/vuepress-theme-reco#46]
各大博客平台上，首页的分页也是很常见吧！找了找文档没有写，于是乎就看了源代码，源代码中直接显示头10条 ，其余的隐藏，这样的方式可能不太好，首先就造成无用的 DOM 树残留在页面上，扯远了，，最后还是希望能够有个分页功能能够的指定去看哪一页的内容

**Comment by recoluan** [comment]
好的，感谢你的建议，下一个版本会修复这两块

**Comment by recoluan** [comment]
已在 `1.1.0` 版本中添加此功能。

**Comment by vxhly** [comment]
![image](https://user-images.githubusercontent.com/17906558/67265902-72a8e100-f4e1-11e9-92d8-1c48b3edab8f.png)
![image](https://user-images.githubusercontent.com/17906558/67266068-dfbc7680-f4e1-11e9-8c63-afd23c367f6b.png)

好的，回到DOM树生成的问题来，
问题一：如果我有100篇文章，那么就生成了100个dom，这势必会在加载的时候造成资源的浪费，用v-if都比用v-show好吧
问题二：.abstract-item 被这个样式覆盖了，分页功能失效，样式是对的

**Comment by recoluan** [comment]
文章列表的阅读数量只有在首次渲染的时候才能获取，如果用 v-if 就获取不到了第一页之后的浏览量的了，但是浏览量，大多数人又需要这个东西，后期看看通过通过参数去动态配置这一块吧
