### ISSUE TITLE
怎么删除主页头部的全屏按钮

### ISSUE THREAD

**Issue by hpstream** [vuepress-reco/vuepress-theme-reco#48]
![image](https://user-images.githubusercontent.com/18394192/65852831-f90e4f00-e389-11e9-9b54-c3df984af996.png)
大佬
移动端显示有些问题，
主要的全屏按钮怎么去掉

**Comment by vxhly** [comment]
写一条 css 不就好了，display：none

**Comment by recoluan** [comment]
如果你只是想单纯地删除这个按钮，可以参照楼上的建议。
