### ISSUE TITLE
alpha.6的版本，从首页右侧的标签列表栏点击其中一个标签跳转到标签页时显示的是全部，而不是对应的标签信息

### ISSUE THREAD

**Issue by ghost** [vuepress-reco/vuepress-theme-reco#50]
- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version: 
- VuePress-theme-reco version: 
- Which package manager did you use for the install(npm/cnpm/yarn)?

**Comment by recoluan** [comment]
你好，`1.0.9-alpha.8` 中已经修复了。
