### ISSUE TITLE
cli初始化，报错，页面显示404

### ISSUE THREAD

**Issue by hanghang0321** [vuepress-reco/vuepress-theme-reco#51]
![image](https://user-images.githubusercontent.com/44964998/164611510-2cce89db-0007-4f39-9da5-192c4636f508.png)
![image](https://user-images.githubusercontent.com/44964998/164611614-c911eed3-c4aa-493d-bba5-91e97c3d31ea.png)

**Comment by censujiang** [comment]
我也遇到这个问题了

**Comment by recoluan** [comment]
同学，将 vuepress 和 reco 主题都升级到最新的 beta 版本，分别是 2.0.0-beta.39 和 2.0.0-beta.5，清除一下 node_modules ，lock 文件，以及 .vuepress 文件夹下的两个缓存文件夹，重新 install 。

**Comment by googidaddy** [comment]
> 同学，将 vuepress 和 reco 主题都升级到最新的 beta 版本，分别是 2.0.0-beta.39 和 2.0.0-beta.5，清除一下 node_modules ，lock 文件，以及 .vuepress 文件夹下的两个缓存文件夹，重新 install 。

建议改一下官网安装指南，直接最新。

**Comment by janeluck** [comment]
> 

vuepress升级到最新的2.0.0-beta.45，还是不行嘞，构建时会报"[vite] Internal server error: Failed to resolve import "@vuepress/client/app" from ".vuepress/.temp/vite-root/index.htm"

**Comment by recoluan** [comment]
同学们，大家使用 vuepress@2.0.0-beta.46 和 vuepress-theme-reco@2.0.0-beta.16 试一下呢（记得清除缓存）。
