### ISSUE TITLE
建议增加个canvas-ribbon彩带背景，博客空白页不会留白太多，看的不会过于简陋

### ISSUE THREAD

**Issue by ghost** [vuepress-reco/vuepress-theme-reco#51]

**Comment by recoluan** [comment]
好的，收到你的建议，后面会通过插件的方式实现。

**Comment by SigureMo** [comment]
@ghost 可以试下这个 [vuepress-plugin-ribbon](https://github.com/SigureMo/vuepress-plugin-ribbon)

**Comment by zengchulin** [comment]
> @ghost 可以试下这个 [vuepress-plugin-ribbon](https://github.com/SigureMo/vuepress-plugin-ribbon)

谢谢

**Comment by recoluan** [comment]
@SigureMo good work
