### ISSUE TITLE
增加博客封面图

### ISSUE THREAD

**Issue by cheliox** [vuepress-reco/vuepress-theme-reco#58]
希望增加博客封面图，以前用的hexo主题是在md文件开头用 thumbnail 配置的，居中等比例缩放到一定宽度

**Comment by recoluan** [comment]
你好，你可以以摘要的方式设置封面。

**Comment by recoluan** [comment]
好的，我做一下记录。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Elio <notifications@github.com>
发送时间: Friday, October 11, 2019 5:53:09 PM
收件人: vuepress-reco/vuepress-theme-reco <vuepress-theme-reco@noreply.github.com>
抄送: reco_luan <recoluan@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [vuepress-reco/vuepress-theme-reco] 增加博客封面图 (#58)


你好，你可以以摘要的方式设置封面。

用摘要的话会出现在正文，而且也是不能缩放，图片大点就超出框了

―

**Comment by Louis-XIV** [comment]
我就是用摘要做缩略图，并在index.styl里面加上这一段就行了
// 首页列表中的摘要缩略图
.home-blog-wrapper .blog-list img
	max-width 400px

	@media only screen and (max-device-width :480px)
		max-width 400px
		width 100%
// 分类、标签列表的摘要缩略图
div.abstract-wrapper.list div.abstract-item img
	max-width 400px

	@media only screen and (max-device-width :480px)
		max-width 400px
		width 100%
