### ISSUE TITLE
建议增加用户登录功能阅读草稿状态文档

### ISSUE THREAD

**Issue by samuel778** [vuepress-reco/vuepress-theme-reco#59]
## Feature request
增加管理员登录功能，草稿状态文章，私密状态文章
#### What problem does this feature solve?
有些文章，还没写完并不想马上公开，或者并不想公开私密阅读

#### How should this be implemented in your opinion?
1、增加管理员登录功能。
2、对于文章md文件的配置头部，增加文章发布状态，1，发布，2，草稿，3，私密。

#### Are you willing to work on this yourself?
NO

**Comment by recoluan** [comment]
你好朋友，下面是针对你的问题的回复：
1. vuepress 本身是静态网站生成器，像你说的管理员登录这种功能，我目前理解的是无法实现的，你有建议的话可以说一下；
2. 增加发布状态这个建议是比较好的，目前主要是没有草稿状态。文章目前是有加密功能的，详情见项目文档，虽然目前还有一些小bug，但是可以简单使用。

**Comment by samuel778** [comment]
> * 身是静态网站生成器，像你说的管理员登录这种功能，我目前理解的是无法实现的，你有建议的话可以说一下；
> * 增加发布状态这个建议是比较好的，目前主要是没有草稿状态。文章目前是有加密功能的，详情见项目文档

设置固定密码，在代码中明文配置，但编译后需要自动加密，就算加密串被人获取，破解也需要一定的功夫。有一定的安全保护即可。
再简单一点，可以让用户利用其它小工具，自行提供加密串，

**Comment by Louis-XIV** [comment]
我也是有相同的诉求，草稿状态和私密状态，可能有些文章并不想完全公开。

**Comment by recoluan** [comment]
最新版已经支持发布状态，草稿和私密可以理解为一个状态：就是不希望对外开放，所以通过在 `front-matter` 设置 `publish: false` 来禁止发布当前文章，见 [文档](https://vuepress-theme-reco.recoluan.com/views/1.x/frontMatter.html#publish)。

当然私密性也可以通过设置文章加密功能来实现，见 [文档](https://vuepress-theme-reco.recoluan.com/views/1.x/password.html#%E6%96%87%E7%AB%A0%E5%8A%A0%E5%AF%86)。
