### ISSUE TITLE
分类和标签如果有用到中文，点击时页面不存在

### ISSUE THREAD

**Issue by ginteo** [vuepress-reco/vuepress-theme-reco#59]
1. 在首页的博客列表中如果有中文标签或者分类，直接从博客列表中点击分类或标签页面不存在。如果是从首页的个人信息下面的分类或标签中点击是没问题的，看了下此处页面路由是拼音，但是在博客列表中的分类或标签在页面上路由显示是中文
2. 如果在导航栏有设置分类和标签，从导航样点击分类或标签时页面不存在
3. 建议向hexo一样通过命令生成自带当前时间或标签、分类的md文件

**Comment by xiaolannuoyi** [comment]
不支持中文文件名啊 跳转不好使 怎么才能好使呢？
