### ISSUE TITLE
vuess加载失败

### ISSUE THREAD

**Issue by duktig666** [vuepress-reco/vuepress-theme-reco#60]
**Describe the bug**
[vuepress:sw] Error during service worker registration: TypeError: Failed to register a ServiceWorker for scope ('https://www.duktig.cn/') with script ('https://www.duktig.cn/service-worker.js'): ServiceWorker script evaluation failed

![image](https://user-images.githubusercontent.com/53132746/169705141-b826b8c5-24b3-4220-86f8-85b9ca53e495.png)

**Desktop (please complete the following information):**
 - OS:win10
 - Browser chrome

version:1.6.10

**Comment by recoluan** [comment]
看着不像是 vssue 的问题，更像是 ga 检测的问题，能提供更详细的信息吗？可以去 QQ 群 @我。

**Comment by duktig666** [comment]
之前一直没解决掉，我就使用 [Valine](https://valine.js.org/) 了

**Comment by recoluan** [comment]
> 两个QQ群都满了

群3还没有满。
