### ISSUE TITLE
2.x版本初始化 ‘useThemeLocaleData() is called without provider’

### ISSUE THREAD

**Issue by zy823957866** [vuepress-reco/vuepress-theme-reco#62]
![%CX{NH 5N3YB}RF8} GQZP8](https://user-images.githubusercontent.com/19662251/170854475-ee113115-0e18-4422-857f-3468f1544737.png)

**Comment by recoluan** [comment]
使用 vuepress@2.0.0-beta.46 和 vuepress-theme-reco@2.0.0-beta.16 试一下呢（记得清除缓存）。

**Comment by dselegent** [comment]
> 

没有用
