### ISSUE TITLE
2.0.0-beta.6，本地运行无问题，打包失败，报错

### ISSUE THREAD

**Issue by zhanggin** [vuepress-reco/vuepress-theme-reco#63]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/84329520/170989093-6695d438-3566-4c2b-b45d-597bfabc9fb6.png">

```json
  "dependencies": {
    "vuepress": "^2.0.0-beta.46",
    "vuepress-theme-reco": "^2.0.0-beta.6"
  }
```

切换到webpack打包还是失败，报错

**Comment by shichaohui** [comment]
2.0.0-beta.8 也存在这个问题，有办法解决吗？

**Comment by recoluan** [comment]
请更新至 2.0.0-beta.16。
