### ISSUE TITLE
如何实现左边侧边栏三级菜单

### ISSUE THREAD

**Issue by chenshuaikang** [vuepress-reco/vuepress-theme-reco#64]
如题，在reco的主题中如何才能实现左边的侧边栏可以展示三级菜单？

**Comment by recoluan** [comment]
这个暂时不考虑支持。右侧目录，仅做文章大概位置的快捷键使用，且支持深度较大之后会影响美观。
> 个人见解：从读者的角度，三级目录的内容太长，影响阅读体验。
