### ISSUE TITLE
解决valine评论不显示问题

### ISSUE THREAD

**Issue by aoaoms** [vuepress-reco/vuepress-theme-reco#67]
表现：打开站点首页浏览数和valine 评论均不显示。

原因：是cdn.jsdelivr.net 挂了（具体原因自己查）。这个请求的av-min.js 是用于获取leancloud的服务。打开站点控制台可以看到错误。

解决：更换CDN服务地址；在本地库文件 valine.pure.min.js 和 valine.min.js 中修改：
//cdn.jsdelivr.net/npm/leancloud-storage@3/dist/av-min.js
为：
//unpkg.com/leancloud-storage@3.15.0/dist/av-min.js

打包部署，OK~ 正常啦！

**Comment by recoluan** [comment]
2.x 已经通过更新 valine@1.4.18 解决，1.x 暂时还没有更新 valine 版本。
