### ISSUE TITLE
bundler配置优化

### ISSUE THREAD

**Issue by lcx12901** [vuepress-reco/vuepress-theme-reco#70]
vuepress-theme-reco@2.0.0-beta.16，此版本bundler配置被强行覆盖，导致配置不生效
![-7140c6220d48ceea.jpg](https://user-images.githubusercontent.com/50073681/172436115-35bd7135-6b92-4c0e-a898-22c78980e59f.jpg)

**Comment by xinlanlan** [comment]
<img width="388" alt="image" src="https://user-images.githubusercontent.com/23093206/203105275-abc3aadc-e1cd-4631-9684-9d34d899807f.png">
这样配置还是不生效
