### ISSUE TITLE
2.0.0-beta.16 本地无法启动，@vuepress-reco/vuepress-plugin-page 报错

### ISSUE THREAD

**Issue by liuxm-ght** [vuepress-reco/vuepress-theme-reco#72]
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/65209905/175887326-523c9080-f54e-4faa-9089-e6ad19dcfdba.png">

**Comment by comradeWong** [comment]
我之前也有同样的问题，然后我尝试把package.json中的依赖包版本升级到最新，重新安装依赖，然后可以正常启动了。
 "vuepress": "2.0.0-beta.48",
 "vuepress-theme-reco": "2.0.0-beta.19"
