### ISSUE TITLE
文章设置为不发布但还是会在标签列表里展示出来

### ISSUE THREAD

**Issue by Louis-XIV** [vuepress-reco/vuepress-theme-reco#72]
- [x] I confirm that this is an issue rather than a question.

## Bug report
设置 publish: false，在首页是不显示该文章了，但是在标签列表里还是会显示

**Comment by SigureMo** [comment]
确实有这问题，应该很快就能解决哒~:smile:

**Comment by recoluan** [comment]
修复会在下一个版本中体现。
