### ISSUE TITLE
2.0.0-beta.19版本 pnpm 安装后，运行报错，yarn安装运行却不报错

### ISSUE THREAD

**Issue by AnyFork** [vuepress-reco/vuepress-theme-reco#74]
**Describe the bug**
pnpm 安装后，运行报错，yarn安装运行却不报错

![image](https://user-images.githubusercontent.com/49142023/177023596-917f6a90-c702-47f3-a3a4-9b6b88f1748b.png)

**Comment by recoluan** [comment]
需要根据提示手动安装一些依赖，比如你的报错里，是缺少 @vuepress/client，在
跟 vuepress 同级安装一下就行了，如果后面还有类似报错，同样方法处理，这个问题是 pnpm 处理 node_modules 的策略导致的，目前无解，后面我看一下 pnpm 是否有配置可以处理这个问题。

**Comment by AnyFork** [comment]
> 需要根据提示手动安装一些依赖，比如你的报错里，是缺少 @vuepress/client，在 跟 vuepress 同级安装一下就行了，如果后面还有类似报错，同样方法处理，这个问题是 pnpm 处理 node_modules 的策略导致的，目前无解，后面我看一下 pnpm 是否有配置可以处理这个问题。

 确实，通过安装了依赖，可以正常运行了，还是用npm 或者 yarn 稳妥一点。
