### ISSUE TITLE
2.x 全局样式问题

### ISSUE THREAD

**Issue by AnyFork** [vuepress-reco/vuepress-theme-reco#77]
你好，2.x版本是否可以定义全局样式文件呢？vuepress 2.x 默认是在.vuepress/styles目录下定义index.scss样式，覆盖默认样式，但reco 2.x好像是独立主题，此设置无效，就目前版本而言，如何做能实现默认样式覆盖。

**Comment by recoluan** [comment]
reco 主题用的是 css，并使用 postcss 插件实现 css 嵌套能力（类scss），所以你需要使用 css 来覆盖主题样式。
