### ISSUE TITLE
features板块不成功

### ISSUE THREAD

**Issue by ghost** [vuepress-reco/vuepress-theme-reco#81]
features板块页面上没有生成，请问作者怎么才能成功？

**Comment by yaozongbin** [comment]
I also want to solve this problem

**Comment by recoluan** [comment]
目前没有feature模块

**Comment by recoluan** [comment]
features 的[文档](https://vuepress-theme-reco.recoluan.com/docs/theme/frontmatter-home.html#features)，vuepress 升级到 rc.9，主题升级到 rc.8。
