### ISSUE TITLE
你的网站有时候打不开哦

### ISSUE THREAD

**Issue by lookroot** [vuepress-reco/vuepress-theme-reco#83]
- [x] I confirm that this is an issue rather than a question.

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version: 
- VuePress-theme-reco version: 
- Which package manager did you use for the install(npm/cnpm/yarn)?

**Comment by lookroot** [comment]
就是一直在吐泡泡 很久才进去




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SigureMo"<notifications@github.com&gt;; 
发送时间: 2019年10月31日(星期四) 下午5:52
收件人: "vuepress-reco/vuepress-theme-reco"<vuepress-theme-reco@noreply.github.com&gt;; 
抄送: "1270799700"<1270799700@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vuepress-reco/vuepress-theme-reco] 你的网站有时候打不开哦 (#83)




你是说文档嘛？是加载太久嘛？可能是因为github服务器的原因导致加载较慢，但我没遇到打不开的情况呀……

**Comment by SigureMo** [comment]
@lookroot 唔 很久的话是正常的，毕竟是 github 的服务器……不过文档已经开启 PWA 了，第一次加载完成后，下一次应该不会太慢的

**Comment by lookroot** [comment]
好的哦------------------ 原始邮件 ------------------
发件人: "SigureMo"<notifications@github.com>
发送时间: 2019年10月31日(星期四) 晚上6:56
收件人: "vuepress-reco/vuepress-theme-reco"<vuepress-theme-reco@noreply.github.com>;
抄送: "lookroot"<1270799700@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [vuepress-reco/vuepress-theme-reco] 你的网站有时候打不开哦 (#83)



@lookroot 唔 很久的话是正常的，毕竟是 github 的&#x670D;务器……不过文档已经开启 PWA 了，第一次加载完成后，下一次应该不会太慢的
 
&mdash;
