### ISSUE TITLE
[1.x] 1.6.14 右边侧边栏会与页面一起滚动

### ISSUE THREAD

**Issue by yangtonggui** [vuepress-reco/vuepress-theme-reco#84]
vuepress-theme-reco升级到1.6.14后 当左边，右边侧边栏同时存在的情况下,  右边侧边栏会与页面一起滚动的问题
问题复现地址  http://119.3.228.178/yangtg/docs/base/css.html#%E8%AF%AD%E6%B3%95

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/44868434/178637071-06c8d5d4-14c1-4f0a-a5c0-7a36123c7237.png">

**Comment by LeafTyrion** [comment]
老哥，这个问题怎么解决的呢，我这边侧边栏乱滚

**Comment by LeafTyrion** [comment]
复现地址：https://leaftyrion.github.io/note/database/redis/00_install.html

**Comment by recoluan** [comment]
It's not a bug, that's how the functionality is designed.
