### ISSUE TITLE
[1.x] 1.6.14 loading-page插件是失效了吗还是没有跑

### ISSUE THREAD

**Issue by StriveJia** [vuepress-reco/vuepress-theme-reco#85]
不知道大家的是不是这样的问题，我的loading-page显示应用成功但没有效果
![image](https://user-images.githubusercontent.com/107020936/178642006-b6f373cb-8e63-483b-b3aa-870b7de83fbe.png)

**Comment by recoluan** [comment]
loading page 已经移除了。
