### ISSUE TITLE
关于背景乐

### ISSUE THREAD

**Issue by yayxs** [vuepress-reco/vuepress-theme-reco#88]
大佬，请问可以支持背景乐吗

**Comment by SigureMo** [comment]
音乐插件呀？会有的~

**Comment by yayxs** [comment]
文章置顶功能也蛮实用的

**Comment by SigureMo** [comment]
嗯 这个以后应该也会有

**Comment by yayxs** [comment]
好的，谢谢你--

**Comment by recoluan** [comment]
1. 置顶功能请更新至 1.1.4 获取；
2. 音乐插件请关注 [vuepress-plugin-bgm-player](https://github.com/vuepress-reco/vuepress-plugin-bgm-player)。
