### ISSUE TITLE
[1.x] 配置algolia，isAlgoliaSearch为undefined,未加载组件AlgoliaSearchBox

### ISSUE THREAD

**Issue by AnyFork** [vuepress-reco/vuepress-theme-reco#90]
**Describe the bug**
1.X配置algolia，isAlgoliaSearch为undefined,未加载组件AlgoliaSearchBox
 已测出bug，如下：
![image](https://user-images.githubusercontent.com/49142023/179344599-3bac978a-3cc9-4048-afec-287af691ac5e.png)

**Comment by recoluan** [comment]
Can you submit a PR to resolve this issue?

**Comment by recoluan** [comment]
Upgrade to 1.6.15
