### ISSUE TITLE
关于首页分页的问题

### ISSUE THREAD

**Issue by yuanchen1** [vuepress-reco/vuepress-theme-reco#95]
当点击到第二页进入一篇文章，退出文章的时候分页又会自动跳到第一页，这个问题能解决吗?

**Comment by recoluan** [comment]
这个 bug 已经存在 to-do list，不过目前没有时间去解决，估计会在未来第二个版本中尝试去解决这个问题

**Comment by recoluan** [comment]
请更新至 1.1.4
