### ISSUE TITLE
[1.x] 右侧子菜单不会随着滚动条滚动

### ISSUE THREAD

**Issue by maicFir** [vuepress-reco/vuepress-theme-reco#95]
- 当我添加子菜单后，右侧显示子菜单了，但是子菜单并不是fixed固定在最右侧，内容滑到最底部，右侧子菜单始终在最顶部
- 我用的主题版本是
```js
  "devDependencies": {
    "vuepress-theme-reco": "^1.6.15"
  }
```
themeConfig.js
```ts
import { DefaultThemeConfig } from 'vuepress/config';
import nav from './navConfig';
import { sidebar } from './slidebar';
interface themeConfigExtends {
  subSidebar: string;
  author: string;
}
const themeConfig: DefaultThemeConfig & themeConfigExtends = {
  nav,
  sidebar,
  smoothScroll: true,
  subSidebar: 'auto', // 打开子侧边栏
  sidebarDepth: 4,
  author: 'Maic'
};
export default themeConfig;

```

**Comment by maicFir** [comment]
找到原因了，由于默认父级元素设置`transform: translateY(0px)`产生堆叠上下文，导致fixed设置失效

**Comment by zstu0210** [comment]
大佬 我也有这个问题  这样怎么解决啊

**Comment by maicFir** [comment]
> 大佬 我也有这个问题 这样怎么解决啊

f12审核右侧子菜单，把子菜单设置的transform改成none就可以了，主要原因是transform设置导致fixed失效了

**Comment by JuHuaYiJing** [comment]
> > 大佬 我也有这个问题 这样怎么解决啊
> 
> f12审核右侧子菜单，把子菜单设置的transform改成none就可以了，主要原因是transform设置导致fixed失效了

大佬问下为啥项目部署到gitee之后为什么同样有transform属性，却不会有堆叠上下文的问题呢

**Comment by maicFir** [comment]
> > > 大佬 我也有这个问题 这样怎么解决啊
> > 
> > 
> > f12审核右侧子菜单，把子菜单设置的transform改成none就可以了，主要原因是transform设置导致fixed失效了
> 
> 大佬问下为啥项目部署到gitee之后为什么同样有transform属性，却不会有堆叠上下文的问题呢

重置父级元素元素`.page`样式，将父级元素`main`标签的内联样式覆盖,参考[palette.styl](https://github.com/maicFir/maicFir.github.io/blob/dev1.0/docs/.vuepress/styles/palette.styl)

**Comment by yxzlwz** [comment]
> > > > 大佬 我也有这个问题 这样怎么解决啊
> > > 
> > > 
> > > f12审核右侧子菜单，把子菜单设置的transform改成none就可以了，主要原因是transform设置导致fixed失效了
> > 
> > 
> > 大佬问下为啥项目部署到gitee之后为什么同样有transform属性，却不会有堆叠上下文的问题呢
> 
> 重置父级元素元素`.page`样式，将父级元素`main`标签的内联样式覆盖,参考[palette.styl](https://github.com/maicFir/maicFir.github.io/blob/dev1.0/docs/.vuepress/styles/palette.styl)

![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/75941562/fe876888-595c-4eea-bf7a-28d43561b5bb)

![image](https://github.com/vuepress-reco/vuepress-theme-reco/assets/75941562/274771a0-41f8-4955-a1d3-0b383b72423f)

设置这个css后问题仍存在，求解
