### ISSUE TITLE
How to change the theme colors

### ISSUE THREAD

**Issue by anarchical** [vuepress-reco/vuepress-theme-reco#96]
一开始像1.x版本那样新建 palette.styl 文件并添加 $accentColor = #xxxx 后发现行不通，请问一下2.x版本应该如何去更改主题颜色呢

**Comment by recoluan** [comment]
2.x uses tailwindcss to develop styles, custom methods coming soon.

**Comment by LoveqLRC** [comment]
现在有解决方案了吗？还有就是图片无法点击放大

**Comment by recoluan** [comment]
You can change the color of theme reference [docs](https://github.com/vuepress-reco/vuepress-theme-reco/issues/96#issue-1309081753).
