### ISSUE TITLE
[2.x] 导航内置图标不生效

### ISSUE THREAD

**Issue by heteng99** [vuepress-reco/vuepress-theme-reco#97]
```
navbar: [{ text: 'Home', link: '/', icon: 'reco-home' }]
```
像这样配置，没有图标出现  
配置参考了 [1.x](https://vuepress-reco-doc.vercel.app/views/1.x/configJs.html) 文档，2.x 好像没了？

**Comment by recoluan** [comment]
The icons are not the same as 1.x, please refer to here.

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/18067907/180635368-c98fd2b9-70e1-41db-b301-febbc7e8f5bf.png">
