### ISSUE TITLE
Tabs and pageviews are displayed incorrectly.

### ISSUE THREAD

**Issue by vlssu** [vuepress-reco/vuepress-theme-reco#99]
- [x] I confirm that this is an issue rather than a question.

## Bug report
none

#### What is actually happening?

Refresh after visiting the article page on the blog homepage, or directly visit the article page, the tag and pageviews amount will show errors.

Video of steps to reproduce: https://user-images.githubusercontent.com/43847794/180485804-e614d36c-6c71-4ef1-b766-3da2e1fd2a0e.mp4

#### Steps to reproduce
1. Click the copy directly on the blog homepage
2. Refresh the page and it will appear

#### Other relevant information

- Your OS: Ubuntu 20.04
- Node.js version: v16.15.1
- VuePress version: 2.0.0-beta.48
- VuePress-theme-reco version: 2.0.0-beta.24
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? yarn v1.22.17

**Comment by recoluan** [comment]
What's the meaning of "copy"?

**Comment by vlssu** [comment]
> What's the meaning of "copy"? And there is something wrong with this video.

![Screenshot_20220723_184426](https://user-images.githubusercontent.com/43847794/180601862-e40134c1-efa9-463d-afaa-14a178f45fb0.jpg)

**Comment by recoluan** [comment]
Ok, I got it.
